export type PublicSeoRoute = {
  path: string;
  label: string;
  description: string;
  changeFrequency: "weekly" | "monthly";
  priority: number;
  lastModified?: string;
  llmsSection?: "Hiring and Vetting" | "Services and Role Discovery" | "Tools" | "For Virtual Assistants" | "Editorial Resources" | "Optional";
};

export const PUBLIC_SEO_ROUTES: PublicSeoRoute[] = [
  {
    path: "",
    label: "Home",
    description: "Overview of the platform and its approach to hiring vetted Filipino virtual assistants.",
    changeFrequency: "weekly",
    priority: 1,
    llmsSection: "Hiring and Vetting",
  },
  {
    path: "/hire",
    label: "Hire a Virtual Assistant",
    description: "Submit a private role brief and start the matching process.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Hiring and Vetting",
  },
  {
    path: "/find-talent",
    label: "Find Talent",
    description: "Browse approved virtual assistant talent available for public discovery.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Hiring and Vetting",
  },
  {
    path: "/services",
    label: "Virtual Assistant Services",
    description: "Directory of virtual assistant specialties and service categories.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Services and Role Discovery",
  },
  {
    path: "/pricing",
    label: "Pricing",
    description: "Current client pricing structure, service models, and cost guidance.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Hiring and Vetting",
  },
  {
    path: "/managed-vs-direct-hire",
    label: "Managed vs Direct Hire",
    description: "Comparison of the platform's managed-service and direct-hire options.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Hiring and Vetting",
  },
  {
    path: "/how-vetting-works",
    label: "How Vetting Works",
    description: "Explanation of the structured candidate screening, recruiter review, approval, and privacy process.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Hiring and Vetting",
  },
  {
    path: "/faq",
    label: "FAQ",
    description: "Current answers about hiring, vetting, pricing, privacy, applications, and platform use.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Hiring and Vetting",
  },
  {
    path: "/about",
    label: "About",
    description: "Background on VirtualAssistant.com.ph.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Optional",
  },
  {
    path: "/privacy",
    label: "Privacy Policy",
    description: "Privacy practices for the platform.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Optional",
  },
  {
    path: "/terms",
    label: "Terms",
    description: "Platform terms and operating rules.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Optional",
  },
  {
    path: "/contact",
    label: "Contact",
    description: "Public contact page.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Optional",
  },
  {
    path: "/jobs",
    label: "Jobs",
    description: "Public virtual assistant job opportunities.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "For Virtual Assistants",
  },
  {
    path: "/industries",
    label: "Industries",
    description: "Virtual assistant support organized by industry.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Services and Role Discovery",
  },
  {
    path: "/software",
    label: "Software Experience",
    description: "Virtual assistant pages organized around software and platform experience.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Services and Role Discovery",
  },
  {
    path: "/blog",
    label: "Blog",
    description: "Guides about hiring, managing, budgeting for, and working with Filipino virtual assistants.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Editorial Resources",
  },
  {
    path: "/research/virtual-assistant-rates-philippines-2026",
    label: "2026 Virtual Assistant Rate & Skills Report",
    description: "First-party aggregate data on preferred USD hourly rates, experience, specialties, skills, and tools in VirtualAssistant.com.ph candidate profiles.",
    changeFrequency: "monthly",
    priority: 0.82,
    lastModified: "2026-09-22",
    llmsSection: "Editorial Resources",
  },
  {
    path: "/for-virtual-assistants",
    label: "For Virtual Assistants",
    description: "Information for Filipino virtual assistants using the platform.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "For Virtual Assistants",
  },
  {
    path: "/tools",
    label: "Virtual Assistant Tools",
    description: "Hub for hiring and cost-planning tools.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Tools",
  },
  {
    path: "/tools/virtual-assistant-cost-calculator",
    label: "Virtual Assistant Cost Calculator",
    description: "Estimate virtual assistant compensation and service costs using current configurable inputs.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Tools",
  },
  {
    path: "/tools/virtual-assistant-hourly-to-monthly-calculator",
    label: "Hourly to Monthly Calculator",
    description: "Convert an hourly virtual assistant rate and weekly hours into an estimated monthly amount.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Tools",
  },
  {
    path: "/tools/virtual-assistant-job-description-generator",
    label: "Job Description Generator",
    description: "Build a virtual assistant job description from role requirements.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Tools",
  },
  {
    path: "/tools/what-type-of-va-do-i-need",
    label: "What Type of VA Do I Need?",
    description: "Guided tool for identifying the type of virtual assistant that fits a workload.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Services and Role Discovery",
  },
  {
    path: "/authors/christ-hemsworthy",
    label: "Christ Hemsworthy",
    description: "Author profile for published editorial content.",
    changeFrequency: "monthly",
    priority: 0.8,
  },
  {
    path: "/authors/editorial-team",
    label: "Editorial Team",
    description: "Editorial team profile for published site content.",
    changeFrequency: "monthly",
    priority: 0.8,
  },
  {
    path: "/editorial-policy",
    label: "Editorial Policy",
    description: "Standards governing published editorial content.",
    changeFrequency: "monthly",
    priority: 0.8,
    llmsSection: "Editorial Resources",
  },
];
