import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { addBenchMemberAction, updateBenchMemberAction } from "@/app/actions/vetting";
import { VA_CATEGORIES, DEFAULT_BENCH_TARGET } from "@/lib/constants";

export default async function RecruiterBench(){
  await requireRole("recruiter");const admin=createAdminClient();
  const [{data:members},{data:approvedRows}]=await Promise.all([
    admin.from("bench_memberships").select("*").order("category").order("priority",{ascending:false}),
    admin.from("va_vetting").select("va_id,stage").in("stage",["approved","bench"]).limit(200)
  ]);
  const allIds=[...new Set([...(members||[]).map((x:any)=>x.va_id),...(approvedRows||[]).map((x:any)=>x.va_id)])];
  const [{data:profiles},{data:vas}]=allIds.length?await Promise.all([
    admin.from("profiles").select("id,full_name").in("id",allIds),
    admin.from("va_profiles").select("user_id,headline,primary_category,weekly_hours,availability_status").in("user_id",allIds)
  ]):[{data:[]},{data:[]}];
  const pm=new Map((profiles||[]).map((p:any)=>[p.id,p]));const vm=new Map((vas||[]).map((v:any)=>[v.user_id,v]));
  const active=(members||[]).filter((x:any)=>x.status==="active");
  const counts=new Map<string,number>();active.forEach((x:any)=>counts.set(x.category,(counts.get(x.category)||0)+1));
  const memberIds=new Set((members||[]).map((x:any)=>x.va_id));
  const availableApproved=(approvedRows||[]).filter((x:any)=>!memberIds.has(x.va_id));
  return <>
    <div className="page-head"><div><h1>Approved talent pool</h1><p>Keep approved, currently usable Virtual Assistants available in the categories you sell most often. Coverage gaps become recruiting priorities before a client request arrives.</p></div></div>
    <div className="bench-grid">{VA_CATEGORIES.map((category,index)=>{const count=counts.get(category)||0;const pct=Math.min(100,Math.round((count/DEFAULT_BENCH_TARGET)*100));return <div className="card" key={`${String(category)}-${index}`}><div className="row-between"><strong>{category}</strong><span className={`badge ${count>=3?"badge-success":count?"badge-warning":""}`}>{count}/{DEFAULT_BENCH_TARGET}</span></div><div className="progress progress-green" style={{margin:"12px 0 7px"}}><span style={{width:`${pct}%`}}/></div><span className="small muted">{count>=5?"Coverage target met":count>=3?"Healthy coverage":`${Math.max(0,3-count)} more needed for minimum coverage`}</span></div>})}</div>
    <div className="card" style={{marginTop:18}}><div className="row-between" style={{marginBottom:14}}><div><h3 style={{margin:0}}>Talent pool members</h3><span className="small muted">Pause someone without removing their approval history.</span></div><Link className="btn btn-sm" href="/workspace/recruiter/queue">Review candidates</Link></div>{members?.length?<div className="table-wrap responsive-table"><table><thead><tr><th>Virtual Assistant</th><th>Category</th><th>Priority</th><th>Hours</th><th>Availability</th><th>Status</th><th></th></tr></thead><tbody>{members.map((m:any)=>{const p=pm.get(m.va_id) as any;const va=vm.get(m.va_id) as any;return <tr key={m.id}><td data-label="Virtual Assistant"><strong>{p?.full_name||"Virtual Assistant"}</strong><div className="small muted">{va?.headline||va?.primary_category}</div></td><td data-label="Category">{m.category}</td><td data-label="Priority">{m.priority}/5</td><td data-label="Hours">{va?.weekly_hours?`${va.weekly_hours}/week`:"Not set"}</td><td data-label="Availability">{va?.availability_status||"unknown"}</td><td data-label="Status"><span className={`badge ${m.status==="active"?"badge-success":""}`}>{m.status}</span></td><td data-label="Action"><div className="row wrap"><Link className="btn btn-sm" href={`/workspace/recruiter/candidates/${m.va_id}`}>View profile</Link><form action={updateBenchMemberAction}><input type="hidden" name="membership_id" value={m.id}/><input type="hidden" name="status" value={m.status==="active"?"paused":"active"}/><button className="btn btn-sm" type="submit">{m.status==="active"?"Pause":"Activate"}</button></form></div></td></tr>})}</tbody></table></div>:<div className="empty">No VAs are in the active talent pool yet.</div>}</div>
    <div className="card" style={{marginTop:18}}><h3>Approved Virtual Assistants ready for the talent pool</h3><p className="small muted">This is delegable. Once admin approves a finalist, the recruiter can place them into the category pool that needs coverage.</p>{availableApproved.length?<div className="table-wrap responsive-table"><table><thead><tr><th>Virtual Assistant</th><th>Primary category</th><th>Add to talent pool</th></tr></thead><tbody>{availableApproved.map((row:any)=>{const p=pm.get(row.va_id) as any;const va=vm.get(row.va_id) as any;return <tr key={row.va_id}><td data-label="Virtual Assistant"><strong>{p?.full_name||"Virtual Assistant"}</strong><div className="small muted">{va?.headline||"Virtual Assistant"}</div></td><td data-label="Primary category">{va?.primary_category||"Not set"}</td><td data-label="Add to talent pool"><div className="row wrap"><Link className="btn btn-sm" href={`/workspace/recruiter/candidates/${row.va_id}`}>View profile</Link><form action={addBenchMemberAction} className="row wrap"><input type="hidden" name="va_id" value={row.va_id}/><select name="category" defaultValue={va?.primary_category||VA_CATEGORIES[0]} style={{border:"1px solid var(--line)",borderRadius:8,padding:"7px 8px"}}>{VA_CATEGORIES.map((x,index)=><option key={`${String(x)}-${index}`}>{x}</option>)}</select><select name="priority" defaultValue="3" style={{border:"1px solid var(--line)",borderRadius:8,padding:"7px 8px"}}><option value="5">Priority 5</option><option value="4">Priority 4</option><option value="3">Priority 3</option><option value="2">Priority 2</option><option value="1">Priority 1</option></select><button className="btn btn-sm btn-primary" type="submit">Add to talent pool</button></form></div></td></tr>})}</tbody></table></div>:<div className="empty">No approved VAs are waiting for a talent-pool category.</div>}</div>
  </>;
}
