import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, LockKeyhole } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { canonicalPath } from "@/lib/seo-url";

export const metadata: Metadata = { title: "How VA Vetting Works", description: "See the screening steps required before a virtual assistant can appear in the VirtualAssistant.com.ph public talent directory.", keywords: ["virtual assistant vetting process", "how are virtual assistants screened", "vetted filipino virtual assistants"] , alternates: { canonical: canonicalPath("/how-vetting-works") }};

export default function VettingPage(){const steps=[["Structured profile","Experience, specialty, skills, tools, industries, languages, availability, and resume completeness."],["Category skills test","A practical screening tied to the VA’s primary specialty, with a defined passing threshold."],["Video introduction","A short private introduction used to assess communication and client-facing readiness."],["Recruiter review","A five-part scorecard covering role skills, communication, judgment, reliability, and client readiness."],["Final approval","An admin reviews the recruiter evidence before the VA is approved for public discovery."],["Availability gate","Only approved VAs marked available and opted into the directory can appear publicly."]];return <><SiteHeader/><main id="main-content">
  <section className="section public-hero-small"><div className="container"><h1 className="public-page-title">“Vetted” should mean more than a profile badge.</h1><p className="public-lede">VirtualAssistant.com.ph uses a staged screening workflow before a VA can appear in the public directory. The goal is to reduce weak-fit filtering for clients while keeping private candidate evidence protected.</p><div className="row wrap"><Link className="btn btn-primary" href="/find-talent">Browse VAs</Link><Link className="btn" href="/hire">Get a managed VA</Link></div></div></section>
  <section className="section section-white"><div className="container"><div className="vetting-steps">{steps.map(([title,copy],i)=><div className="vetting-step" key={title}><div className="vetting-step-number-wrap"><div className="vetting-step-number">{String(i+1).padStart(2,"0")}</div><CheckCircle2 className="vetting-step-check" size={16}/></div><div><h2>{title}</h2><p className="muted">{copy}</p></div></div>)}</div></div></section>
  <section className="section"><div className="container grid-2"><div className="card"><LockKeyhole/><h2>What stays private</h2><p className="muted">Raw test answers, recruiter notes, video URLs, uploaded resumes, contact information, and internal review comments are not published in the talent directory.</p></div><div className="card"><CheckCircle2/><h2>What clients can verify</h2><p className="muted">Public profiles show the approved status, category, experience, skills, tools, industries, languages, availability, schedule preferences, and the milestones completed in the screening process.</p></div></div></section>
</main><SiteFooter/></>}
