import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createTaskAction, reviewTimeEntryAction, toggleChecklistAction, updateTaskStatusAction } from "@/app/actions/workroom";
import { money } from "@/lib/format";
import { PlacementReviewPanel } from "@/components/placement-review-panel";

function timeStatus(status:string){ return status==="approved"?"Approved":status==="changes_requested"?"Changes requested":"Pending review"; }

export default async function ClientWorkroomPage(){
  const {user}=await requireRole("client"); const supabase=await createClient();
  const {data:rooms}=await supabase.from("workrooms").select("*,jobs(title,hours_per_week,min_hourly_rate,timezone,overlap_hours,onboarding_plan,engagement_length),applications(profile_snapshot)").eq("client_id",user.id).order("created_at",{ascending:false});
  const ids=(rooms||[]).map((r:any)=>r.id); const applicationIds=(rooms||[]).map((r:any)=>r.application_id);
  let tasks:any[]=[];let checks:any[]=[];let time:any[]=[];let conversations:any[]=[];let reviews:any[]=[];let publicVas:any[]=[];
  if(ids.length){const vaIds=(rooms||[]).map((r:any)=>r.va_id);const results=await Promise.all([supabase.from("workroom_tasks").select("*").in("workroom_id",ids).order("created_at"),supabase.from("workroom_checklist").select("*").in("workroom_id",ids).order("sort_order"),supabase.from("time_entries").select("*").in("workroom_id",ids).order("work_date",{ascending:false}),supabase.from("conversations").select("id,application_id").in("application_id",applicationIds),supabase.from("reviews").select("*").in("workroom_id",ids),supabase.from("public_va_directory").select("user_id,slug").in("user_id",vaIds)]);tasks=results[0].data||[];checks=results[1].data||[];time=results[2].data||[];conversations=results[3].data||[];reviews=results[4].data||[];publicVas=results[5].data||[];}
  const conversationMap=new Map(conversations.map((c:any)=>[c.application_id,c.id]));
  const publicVaIds=new Set(publicVas.map((v:any)=>v.user_id));
  return <><div className="page-head"><div><h1>Workroom</h1><p>Run active placements with the agreed hire terms, onboarding, tasks, reviewed time, and the correct candidate conversation.</p></div></div>{rooms?.length?<div className="stack">{rooms.map((r:any)=>{const roomTasks=tasks.filter((t)=>t.workroom_id===r.id);const roomChecks=checks.filter((c)=>c.workroom_id===r.id);const roomTime=time.filter((t)=>t.workroom_id===r.id);const total=roomTime.reduce((sum,t)=>sum+Number(t.hours||0),0);const approvedHours=roomTime.filter((t)=>t.status==="approved").reduce((sum,t)=>sum+Number(t.hours||0),0);const thread=conversationMap.get(r.application_id);return <div className="card stack" key={r.id}>
    <div className="row-between wrap"><div><span className="badge badge-success">{r.status}</span><h2 style={{margin:"8px 0 3px"}}>{r.jobs?.title}</h2><span className="muted">Working with {r.applications?.profile_snapshot?.full_name||"Virtual Assistant"}</span></div><Link className="btn btn-primary" href={thread?`/workspace/client/messages?thread=${thread}`:"/workspace/client/messages"}>Open this conversation</Link></div>
    <section className="card hire-terms-card"><div className="row-between wrap"><div><h3 style={{margin:0}}>Confirmed hire terms</h3><p className="small muted" style={{margin:"4px 0 0"}}>These are the terms recorded when the hire was confirmed.</p></div></div><div className="grid-3" style={{marginTop:12}}><div><span className="small muted">Agreed rate</span><strong style={{display:"block"}}>{money(r.agreed_hourly_rate||r.jobs?.min_hourly_rate)}/hr</strong></div><div><span className="small muted">Start date</span><strong style={{display:"block"}}>{r.start_date||"Not recorded"}</strong></div><div><span className="small muted">Agreed schedule</span><strong style={{display:"block"}}>{r.agreed_schedule||"Not recorded"}</strong></div></div></section>
    <div className="grid-3"><div className="card"><div className="small muted">Expected hours</div><strong>{r.jobs?.hours_per_week?`${r.jobs.hours_per_week}/week`:"Flexible"}</strong></div><div className="card"><div className="small muted">Approved time</div><strong>{approvedHours.toFixed(2)} hrs</strong></div><div className="card"><div className="small muted">Total submitted</div><strong>{total.toFixed(2)} hrs</strong></div></div>
    <div className="grid-2"><section className="card"><h3>Onboarding checklist</h3><div className="checklist">{roomChecks.map((c:any)=><form action={toggleChecklistAction} className="check-item" key={c.id}><div className={`check-icon ${c.completed_at?"done":""}`}>{c.completed_at?"✓":""}</div><div><strong className="small">{c.title}</strong></div><input type="hidden" name="checklist_id" value={c.id}/><input type="hidden" name="done" value={c.completed_at?"1":"0"}/><button className="btn btn-sm" type="submit">{c.completed_at?"Reopen":"Complete"}</button></form>)}</div>{r.jobs?.onboarding_plan?<p className="small muted"><strong>Plan:</strong> {r.jobs.onboarding_plan}</p>:null}</section><section className="card"><h3>Create a task</h3><form action={createTaskAction} className="stack"><input type="hidden" name="workroom_id" value={r.id}/><div className="field"><label>Task</label><input name="title" required placeholder="Prepare weekly lead report"/></div><div className="field"><label>Details</label><textarea name="description" placeholder="What needs to be done and what does done look like?"/></div><div className="field"><label>Due date</label><input type="date" name="due_date"/></div><button className="btn btn-primary" type="submit">Assign task</button></form></section></div>
    <section className="card"><div className="row-between wrap"><h3 style={{margin:0}}>Tasks</h3><span className="small muted">{roomTasks.filter((t)=>t.status==="done").length} of {roomTasks.length} done</span></div>{roomTasks.length?<div className="table-wrap responsive-table" style={{marginTop:12}}><table><thead><tr><th>Task</th><th>Due</th><th>Status</th></tr></thead><tbody>{roomTasks.map((t:any)=><tr key={t.id}><td data-label="Task"><strong>{t.title}</strong><div className="small muted">{t.description}</div></td><td data-label="Due">{t.due_date||"No date"}</td><td data-label="Status"><form action={updateTaskStatusAction} className="row"><input type="hidden" name="task_id" value={t.id}/><label className="sr-only" htmlFor={`client-task-${t.id}`}>Task status</label><select id={`client-task-${t.id}`} name="status" defaultValue={t.status} className="compact-select"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="review">Review</option><option value="done">Done</option></select><button className="btn btn-sm" type="submit">Save</button></form></td></tr>)}</tbody></table></div>:<div className="empty">No tasks yet.</div>}</section>
    {roomTime.length?<section className="card"><div className="row-between wrap"><div><h3 style={{margin:0}}>Time entries</h3><p className="small muted" style={{margin:"4px 0 0"}}>Approve accurate entries or request a specific correction.</p></div></div><div className="table-wrap responsive-table" style={{marginTop:12}}><table><thead><tr><th>Date</th><th>Hours</th><th>Work note</th><th>Status</th><th>Review</th></tr></thead><tbody>{roomTime.slice(0,20).map((t:any)=><tr key={t.id}><td data-label="Date">{t.work_date}</td><td data-label="Hours">{Number(t.hours).toFixed(2)}</td><td data-label="Work note">{t.note||"No note"}</td><td data-label="Status"><span className={`badge ${t.status==="approved"?"badge-success":t.status==="changes_requested"?"badge-warning":""}`}>{timeStatus(t.status)}</span>{t.client_note?<div className="small muted" style={{marginTop:5}}>{t.client_note}</div>:null}</td><td data-label="Review">{t.status==="approved"?<span className="small muted">Locked after approval</span>:t.status==="changes_requested"?<span className="small muted">Waiting for Virtual Assistant correction</span>:<details className="time-review"><summary className="btn btn-sm">Review</summary><form action={reviewTimeEntryAction} className="stack time-review-panel"><input type="hidden" name="time_entry_id" value={t.id}/><div className="field"><label>Correction note (required only if requesting changes)</label><textarea name="client_note" maxLength={500} placeholder="Example: Please split the 6 hours across the two dates worked."/></div><div className="row wrap"><button className="btn btn-sm btn-primary" name="decision" value="approve">Approve</button><button className="btn btn-sm" name="decision" value="changes">Request changes</button></div></form></details>}</td></tr>)}</tbody></table></div></section>:null}
    <PlacementReviewPanel workroomId={r.id} viewerRole="client" counterpartyLabel={r.applications?.profile_snapshot?.full_name||"this Virtual Assistant"} ownReview={reviews.find((review:any)=>review.workroom_id===r.id&&review.reviewer_id===user.id)||null} receivedReview={reviews.find((review:any)=>review.workroom_id===r.id&&review.reviewer_id===r.va_id)||null} vaProfileIsPublic={publicVaIds.has(r.va_id)}/>
  </div>})}</div>:<div className="card empty">No active placements yet. A workroom is created only after you confirm a Virtual Assistant’s final rate, start date, and schedule.</div>}</>;
}
