import type { NextConfig } from "next";

const ROLE_RESOURCE_CONSOLIDATIONS = [
  { service: "admin-inbox", base: "administrative-virtual-assistant", article: "an" },
  { service: "digital-marketing-virtual-assistant", base: "digital-marketing-virtual-assistant", article: "a" },
  { service: "social-media", base: "social-media-virtual-assistant", article: "a" },
  { service: "accounting-virtual-assistant", base: "accounting-virtual-assistant", article: "an" },
  { service: "it-virtual-assistant", base: "it-virtual-assistant", article: "an" },
  { service: "research-data", base: "data-entry-research-virtual-assistant", article: "a" },
  { service: "graphic-design", base: "graphic-design-virtual-assistant", article: "a" },
  { service: "recruitment-hr", base: "recruitment-hr-virtual-assistant", article: "a" },
  { service: "project-coordination", base: "project-coordination-virtual-assistant", article: "a" },
  { service: "personal-assistant", base: "personal-virtual-assistant", article: "a" },
  { service: "phone-receptionist", base: "virtual-receptionist", article: "a" },
  { service: "property-management-virtual-assistant", base: "property-management-virtual-assistant", article: "a" },
  { service: "crm", base: "crm-virtual-assistant", article: "a" },
  { service: "email-marketing", base: "email-marketing-virtual-assistant", article: "an" },
  { service: "wordpress", base: "wordpress-virtual-assistant", article: "a" },
  { service: "creative-virtual-assistant", base: "creative-virtual-assistant", article: "a" },
  { service: "logistics-virtual-assistant", base: "logistics-virtual-assistant", article: "a" },
  { service: "general-virtual-assistant", base: "general-virtual-assistant", article: "a" },
  { service: "small-business-virtual-assistant", base: "small-business-virtual-assistant", article: "a" },
  { service: "payroll-virtual-assistant", base: "payroll-virtual-assistant", article: "a" },
  { service: "operations", base: "operations-virtual-assistant", article: "an" },
  { service: "calendar", base: "calendar-management-virtual-assistant", article: "a" },
  { service: "airbnb-virtual-assistant", base: "airbnb-virtual-assistant", article: "an" },
  { service: "pinterest-virtual-assistant", base: "pinterest-virtual-assistant", article: "a" },
  { service: "content-writing", base: "content-writing-virtual-assistant", article: "a" }
] as const;

const roleResourceConsolidationRedirects = ROLE_RESOURCE_CONSOLIDATIONS.flatMap(({ service, base, article }) => {
  const servicePath = "/service/" + service;
  const definition = "/resources/what-does-" + article + "-" + base + "-do";
  const tasks = "/resources/" + base + "-tasks";
  const hiring = "/resources/how-to-hire-" + article + "-" + base;
  const interview = "/resources/" + base + "-interview-questions";
  const cost = "/resources/" + base + "-cost-philippines";
  const tools = "/resources/best-tools-for-" + base;
  const core = service === "payroll-virtual-assistant"
    ? [
        { source: definition, destination: "/blog/what-does-a-payroll-virtual-assistant-do", permanent: true },
        { source: tasks, destination: "/blog/what-does-a-payroll-virtual-assistant-do", permanent: true },
        { source: hiring, destination: "/blog/how-to-hire-a-payroll-virtual-assistant", permanent: true },
        { source: interview, destination: "/blog/how-to-hire-a-payroll-virtual-assistant", permanent: true },
        { source: cost, destination: "/blog/payroll-virtual-assistant-cost-philippines", permanent: true },
        { source: tools, destination: servicePath, permanent: true },
      ]
    : [
        { source: definition, destination: servicePath, permanent: true },
        { source: tasks, destination: servicePath, permanent: true },
        { source: interview, destination: hiring, permanent: true },
        { source: tools, destination: servicePath, permanent: true },
      ];
  return core.flatMap((redirect) => [redirect, { ...redirect, source: redirect.source + "/" }]);
});

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "Content-Security-Policy", value: "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://challenges.cloudflare.com https://vercel.live; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://www.google-analytics.com https://*.google-analytics.com https://challenges.cloudflare.com https://vercel.live; frame-src https://challenges.cloudflare.com https://vercel.live; worker-src 'self' blob:; manifest-src 'self'; media-src 'self' https:; upgrade-insecure-requests" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
          { key: "Strict-Transport-Security", value: "max-age=31536000; includeSubDomains" }
        ]
      }
    ];
  },
  async redirects() {
    return [
      ...roleResourceConsolidationRedirects,
      // Editorial topics belong in the blog. Preserve today's temporary URLs with one-hop permanent redirects.
      { source: "/virtual-assistant-companies-philippines", destination: "/blog/virtual-assistant-companies-philippines", permanent: true },
      { source: "/virtual-assistant-companies-philippines/", destination: "/blog/virtual-assistant-companies-philippines", permanent: true },
      { source: "/virtual-assistant-websites", destination: "/blog/virtual-assistant-websites", permanent: true },
      { source: "/virtual-assistant-websites/", destination: "/blog/virtual-assistant-websites", permanent: true },
      { source: "/what-is-a-virtual-assistant", destination: "/blog/what-is-a-virtual-assistant", permanent: true },
      { source: "/what-is-a-virtual-assistant/", destination: "/blog/what-is-a-virtual-assistant", permanent: true },
      { source: "/industries/nonprofits", destination: "/blog/virtual-assistant-for-nonprofits", permanent: true },
      { source: "/industries/nonprofits/", destination: "/blog/virtual-assistant-for-nonprofits", permanent: true },
      { source: "/resources/how-to-apply-as-a-virtual-assistant", destination: "/blog/how-to-apply-as-a-virtual-assistant", permanent: true },
      { source: "/resources/how-to-apply-as-a-virtual-assistant/", destination: "/blog/how-to-apply-as-a-virtual-assistant", permanent: true },
      { source: "/resources/virtual-assistant-resume-sample", destination: "/blog/virtual-assistant-resume-sample", permanent: true },
      { source: "/resources/virtual-assistant-resume-sample/", destination: "/blog/virtual-assistant-resume-sample", permanent: true },
      { source: "/resources/virtual-assistant-portfolio-examples", destination: "/blog/virtual-assistant-portfolio-examples", permanent: true },
      { source: "/resources/virtual-assistant-portfolio-examples/", destination: "/blog/virtual-assistant-portfolio-examples", permanent: true },
      { source: "/resources/virtual-assistant-skills", destination: "/blog/virtual-assistant-skills", permanent: true },
      { source: "/resources/virtual-assistant-skills/", destination: "/blog/virtual-assistant-skills", permanent: true },
      { source: "/resources/virtual-assistant-requirements-philippines", destination: "/blog/virtual-assistant-requirements-philippines", permanent: true },
      { source: "/resources/virtual-assistant-requirements-philippines/", destination: "/blog/virtual-assistant-requirements-philippines", permanent: true },
      { source: "/resources/how-to-become-a-virtual-assistant-philippines", destination: "/blog/how-to-become-a-virtual-assistant-philippines", permanent: true },
      { source: "/resources/how-to-become-a-virtual-assistant-philippines/", destination: "/blog/how-to-become-a-virtual-assistant-philippines", permanent: true },
      { source: "/resources/virtual-assistant-no-experience", destination: "/blog/become-virtual-assistant-no-experience", permanent: true },
      { source: "/resources/virtual-assistant-no-experience/", destination: "/blog/become-virtual-assistant-no-experience", permanent: true },
      { source: "/resources/virtual-assistant-training-guide", destination: "/blog/virtual-assistant-training-guide", permanent: true },
      { source: "/resources/virtual-assistant-training-guide/", destination: "/blog/virtual-assistant-training-guide", permanent: true },
      { source: "/resources/virtual-assistant-certification-guide", destination: "/blog/virtual-assistant-certification-guide", permanent: true },
      { source: "/resources/virtual-assistant-certification-guide/", destination: "/blog/virtual-assistant-certification-guide", permanent: true },
      { source: "/resources/virtual-assistant-cover-letter", destination: "/blog/virtual-assistant-cover-letter", permanent: true },
      { source: "/resources/virtual-assistant-cover-letter/", destination: "/blog/virtual-assistant-cover-letter", permanent: true },
      { source: "/resources/best-laptop-for-virtual-assistant", destination: "/blog/best-laptop-for-virtual-assistant", permanent: true },
      { source: "/resources/best-laptop-for-virtual-assistant/", destination: "/blog/best-laptop-for-virtual-assistant", permanent: true },
      { source: "/resources/freelance-platforms-for-virtual-assistants", destination: "/blog/freelance-platforms-for-virtual-assistants", permanent: true },
      { source: "/resources/freelance-platforms-for-virtual-assistants/", destination: "/blog/freelance-platforms-for-virtual-assistants", permanent: true },
      { source: "/resources/how-to-start-a-virtual-assistant-business", destination: "/blog/how-to-start-a-virtual-assistant-business", permanent: true },
      { source: "/resources/how-to-start-a-virtual-assistant-business/", destination: "/blog/how-to-start-a-virtual-assistant-business", permanent: true },
      { source: "/resources/virtual-assistant-side-hustle-business-guide", destination: "/blog/how-to-start-a-virtual-assistant-business", permanent: true },
      { source: "/resources/virtual-assistant-side-hustle-business-guide/", destination: "/blog/how-to-start-a-virtual-assistant-business", permanent: true },
      // In-app client/VA messaging was removed; coordination runs through the
      // recruiter. Old notification links and bookmarks land on support.
      { source: "/workspace/client/messages", destination: "/workspace/client/support", permanent: false },
      { source: "/workspace/va/messages", destination: "/workspace/va/support", permanent: false },
      // Correct newly generated resource slugs that used "a" before vowel-sound roles.
      { source: "/resources/what-does-a-administrative-virtual-assistant-do", destination: "/service/admin-inbox", permanent: true },
      { source: "/resources/what-does-a-administrative-virtual-assistant-do/", destination: "/service/admin-inbox", permanent: true },
      { source: "/resources/how-to-hire-a-administrative-virtual-assistant", destination: "/resources/how-to-hire-an-administrative-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-administrative-virtual-assistant/", destination: "/resources/how-to-hire-an-administrative-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-accounting-virtual-assistant-do", destination: "/service/accounting-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-accounting-virtual-assistant-do/", destination: "/service/accounting-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-accounting-virtual-assistant", destination: "/resources/how-to-hire-an-accounting-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-accounting-virtual-assistant/", destination: "/resources/how-to-hire-an-accounting-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-it-virtual-assistant-do", destination: "/service/it-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-it-virtual-assistant-do/", destination: "/service/it-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-it-virtual-assistant", destination: "/resources/how-to-hire-an-it-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-it-virtual-assistant/", destination: "/resources/how-to-hire-an-it-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-email-marketing-virtual-assistant-do", destination: "/service/email-marketing", permanent: true },
      { source: "/resources/what-does-a-email-marketing-virtual-assistant-do/", destination: "/service/email-marketing", permanent: true },
      { source: "/resources/how-to-hire-a-email-marketing-virtual-assistant", destination: "/resources/how-to-hire-an-email-marketing-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-email-marketing-virtual-assistant/", destination: "/resources/how-to-hire-an-email-marketing-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-operations-virtual-assistant-do", destination: "/service/operations", permanent: true },
      { source: "/resources/what-does-a-operations-virtual-assistant-do/", destination: "/service/operations", permanent: true },
      { source: "/resources/how-to-hire-a-operations-virtual-assistant", destination: "/resources/how-to-hire-an-operations-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-operations-virtual-assistant/", destination: "/resources/how-to-hire-an-operations-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-airbnb-virtual-assistant-do", destination: "/service/airbnb-virtual-assistant", permanent: true },
      { source: "/resources/what-does-a-airbnb-virtual-assistant-do/", destination: "/service/airbnb-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-airbnb-virtual-assistant", destination: "/resources/how-to-hire-an-airbnb-virtual-assistant", permanent: true },
      { source: "/resources/how-to-hire-a-airbnb-virtual-assistant/", destination: "/resources/how-to-hire-an-airbnb-virtual-assistant", permanent: true },
      // Consolidate the earlier side-hustle resource into the broader high-volume VA business guide.
      { source: "/resources/virtual-assistant-side-hustle-business-guide", destination: "/resources/how-to-start-a-virtual-assistant-business", permanent: true },
      { source: "/resources/virtual-assistant-side-hustle-business-guide/", destination: "/resources/how-to-start-a-virtual-assistant-business", permanent: true },
      // Recovered from the previous WordPress site's 404 report.
      { source: "/blog-onboard-your-va", destination: "/blog", permanent: true },
      { source: "/blog-onboard-your-va/", destination: "/blog", permanent: true },
      { source: "/blog-tasks-to-delegate-first", destination: "/blog", permanent: true },
      { source: "/blog-tasks-to-delegate-first/", destination: "/blog", permanent: true },
      { source: "/blog/average-hourly-rate-virtual-assistants-philippines", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/average-hourly-rate-virtual-assistants-philippines/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/first-5-tasks-to-delegate", destination: "/blog", permanent: true },
      { source: "/blog/first-5-tasks-to-delegate/", destination: "/blog", permanent: true },
      { source: "/blog/outsourcing-philippines-virtual-assistant", destination: "/outsourcing-philippines-virtual-assistant", permanent: true },
      { source: "/blog/outsourcing-philippines-virtual-assistant/", destination: "/outsourcing-philippines-virtual-assistant", permanent: true },
      { source: "/blog/where-to-find-virtual-assistants-philippines", destination: "/where-to-find-virtual-assistants-philippines", permanent: true },
      { source: "/blog/where-to-find-virtual-assistants-philippines/", destination: "/where-to-find-virtual-assistants-philippines", permanent: true },
      { source: "/blogs", destination: "/blog", permanent: true },
      { source: "/blogs/", destination: "/blog", permanent: true },
      { source: "/career", destination: "/jobs", permanent: true },
      { source: "/career/", destination: "/jobs", permanent: true },
      { source: "/faqs", destination: "/faq", permanent: true },
      { source: "/faqs/", destination: "/faq", permanent: true },
      { source: "/home", destination: "/", permanent: true },
      { source: "/home/", destination: "/", permanent: true },
      { source: "/how-it-works", destination: "/how-vetting-works", permanent: true },
      { source: "/how-it-works/", destination: "/how-vetting-works", permanent: true },
      // GSC still reports impressions for these old root/article URLs. Preserve that authority with one-hop permanent redirects.
      { source: "/how-to-pay-a-virtual-assistant-in-the-philippines-in-depth-2026-guide", destination: "/blog/how-to-pay-a-filipino-virtual-assistant-directly", permanent: true },
      { source: "/how-to-pay-a-virtual-assistant-in-the-philippines-in-depth-2026-guide/", destination: "/blog/how-to-pay-a-filipino-virtual-assistant-directly", permanent: true },
      { source: "/seo-virtual-assistant-philippines-guide", destination: "/service/seo", permanent: true },
      { source: "/seo-virtual-assistant-philippines-guide/", destination: "/service/seo", permanent: true },
      { source: "/how-much-to-pay-a-filipino-virtual-assistant-2026-guide", destination: "/how-much-virtual-assistant-philippines", permanent: true },
      { source: "/how-much-to-pay-a-filipino-virtual-assistant-2026-guide/", destination: "/how-much-virtual-assistant-philippines", permanent: true },
      { source: "/blog/how-much-do-filipino-virtual-assistants-typically-charge-per-hour", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/how-much-do-filipino-virtual-assistants-typically-charge-per-hour/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/how-to-become-bookkeeping-virtual-assistant", destination: "/blog/how-to-become-bookkeeping-virtual-assistant", permanent: true },
      { source: "/how-to-become-bookkeeping-virtual-assistant/", destination: "/blog/how-to-become-bookkeeping-virtual-assistant", permanent: true },
      { source: "/how-to-get-paid-as-a-virtual-assistant-in-the-philippines-by-international-clients", destination: "/blog/get-paid-virtual-assistant-philippines", permanent: true },
      { source: "/how-to-get-paid-as-a-virtual-assistant-in-the-philippines-by-international-clients/", destination: "/blog/get-paid-virtual-assistant-philippines", permanent: true },
      { source: "/how-to-hire-a-virtual-assistant-in-the-philippines-a-complete-guide-for-business-owners", destination: "/blog/how-to-hire-a-virtual-assistant-philippines", permanent: true },
      { source: "/how-to-hire-a-virtual-assistant-in-the-philippines-a-complete-guide-for-business-owners/", destination: "/blog/how-to-hire-a-virtual-assistant-philippines", permanent: true },
      { source: "/join", destination: "/auth/join/client", permanent: true },
      { source: "/join/", destination: "/auth/join/client", permanent: true },
      { source: "/my-account", destination: "/auth/login", permanent: true },
      { source: "/my-account/", destination: "/auth/login", permanent: true },
      { source: "/privacy-policy", destination: "/privacy", permanent: true },
      { source: "/privacy-policy/", destination: "/privacy", permanent: true },
      { source: "/seo", destination: "/service/seo", permanent: true },
      { source: "/seo/", destination: "/service/seo", permanent: true },
      { source: "/service-admin", destination: "/service/admin-inbox", permanent: true },
      { source: "/service-admin/", destination: "/service/admin-inbox", permanent: true },
      { source: "/service-bookkeeping", destination: "/service/bookkeeping", permanent: true },
      { source: "/service-bookkeeping/", destination: "/service/bookkeeping", permanent: true },
      { source: "/service-content-writing", destination: "/service/content-writing", permanent: true },
      { source: "/service-content-writing/", destination: "/service/content-writing", permanent: true },
      { source: "/service-digital-marketing", destination: "/service/digital-marketing-virtual-assistant", permanent: true },
      { source: "/service-digital-marketing/", destination: "/service/digital-marketing-virtual-assistant", permanent: true },
      { source: "/service-ecommerce", destination: "/service/ecommerce", permanent: true },
      { source: "/service-ecommerce/", destination: "/service/ecommerce", permanent: true },
      { source: "/service-lead-generation", destination: "/service/lead-generation", permanent: true },
      { source: "/service-lead-generation/", destination: "/service/lead-generation", permanent: true },
      { source: "/service-real-estate", destination: "/service/real-estate", permanent: true },
      { source: "/service-real-estate/", destination: "/service/real-estate", permanent: true },
      { source: "/service-seo", destination: "/service/seo", permanent: true },
      { source: "/service-seo/", destination: "/service/seo", permanent: true },
      { source: "/service-video-editing", destination: "/service/video-editing", permanent: true },
      { source: "/service-video-editing/", destination: "/service/video-editing", permanent: true },
      { source: "/service/crm-management", destination: "/service/crm", permanent: true },
      { source: "/service/crm-management/", destination: "/service/crm", permanent: true },
      { source: "/service/order-fulfilment", destination: "/service/fulfilment", permanent: true },
      { source: "/service/order-fulfilment/", destination: "/service/fulfilment", permanent: true },
      { source: "/service/research-data-entry", destination: "/service/research-data", permanent: true },
      { source: "/service/research-data-entry/", destination: "/service/research-data", permanent: true },
      { source: "/services/social-media", destination: "/service/social-media", permanent: true },
      // Preserve legacy /services/* URLs that still have backlinks/internal links.
      { source: "/services/healthcare-virtual-assistant", destination: "/service/medical-virtual-assistant", permanent: true },
      { source: "/services/general-virtual-assistant", destination: "/service/general-virtual-assistant", permanent: true },
      { source: "/services/real-estate-virtual-assistant", destination: "/service/real-estate", permanent: true },
      { source: "/services/executive-virtual-assistant", destination: "/service/executive-virtual-assistant", permanent: true },
      { source: "/services/ecommerce-virtual-assistant", destination: "/service/ecommerce", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      // Consolidated law-firm tool guide. Preserve authority and backlinks on the stronger canonical article.
      { source: "/blog/best-legal-practice-management-tools-for-vas", destination: "/blog/best-tools-for-law-firm-virtual-assistant", permanent: true },
      { source: "/blog/best-legal-practice-management-tools-for-vas/", destination: "/blog/best-tools-for-law-firm-virtual-assistant", permanent: true },
      // Legacy article slugs from the crawl. Keep their authority instead of returning 404.
      { source: "/blog/ai-augmented-vas-why-you-should-pay-for-output-not-hours", destination: "/blog/how-a-filipino-va-can-manage-your-ai-workflow", permanent: true },
      { source: "/blog/ai-augmented-vas-why-you-should-pay-for-output-not-hours/", destination: "/blog/how-a-filipino-va-can-manage-your-ai-workflow", permanent: true },
      { source: "/blog/virtual-assistant-agency-philippines-guide", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/blog/virtual-assistant-agency-philippines-guide/", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/blog/can-a-filipino-va-be-hipaa-compliant-security-checklist", destination: "/blog/hipaa-and-remote-virtual-assistants", permanent: true },
      { source: "/blog/can-a-filipino-va-be-hipaa-compliant-security-checklist/", destination: "/blog/hipaa-and-remote-virtual-assistants", permanent: true },
      { source: "/blog/filipino-virtual-assistant-the-complete-hiring-guide", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/blog/filipino-virtual-assistant-the-complete-hiring-guide/", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/blog/filipino-vs-indian-virtual-assistant", destination: "/blog/philippines-vs-india-virtual-assistants", permanent: true },
      { source: "/blog/filipino-vs-indian-virtual-assistant/", destination: "/blog/philippines-vs-india-virtual-assistants", permanent: true },
      { source: "/blog/hire-healthcare-virtual-assistant-philippines", destination: "/service/medical-virtual-assistant", permanent: true },
      { source: "/blog/hire-healthcare-virtual-assistant-philippines/", destination: "/service/medical-virtual-assistant", permanent: true },
      { source: "/blog/hiring-real-estate-virtual-assistant-philippines", destination: "/blog/how-to-hire-a-real-estate", permanent: true },
      { source: "/blog/hiring-real-estate-virtual-assistant-philippines/", destination: "/blog/how-to-hire-a-real-estate", permanent: true },
      { source: "/blog/how-much-to-pay-a-filipino-virtual-assistant-2026-guide", destination: "/how-much-virtual-assistant-philippines", permanent: true },
      { source: "/blog/how-much-to-pay-a-filipino-virtual-assistant-2026-guide/", destination: "/how-much-virtual-assistant-philippines", permanent: true },
      { source: "/blog/how-to-find-virtual-assistant-philippines", destination: "/where-to-find-virtual-assistants-philippines", permanent: true },
      { source: "/blog/how-to-find-virtual-assistant-philippines/", destination: "/where-to-find-virtual-assistants-philippines", permanent: true },
      { source: "/blog/how-to-hire-a-virtual-assistant-philippines", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/blog/how-to-hire-a-virtual-assistant-philippines/", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/blog/how-to-hire-ecommerce-virtual-assistant", destination: "/service/ecommerce", permanent: true },
      { source: "/blog/how-to-hire-ecommerce-virtual-assistant/", destination: "/service/ecommerce", permanent: true },
      { source: "/blog/how-to-pay-a-virtual-assistant-in-the-philippines-in-depth-2026-guide", destination: "/blog/how-to-pay-a-filipino-virtual-assistant-directly", permanent: true },
      { source: "/blog/how-to-pay-a-virtual-assistant-in-the-philippines-in-depth-2026-guide/", destination: "/blog/how-to-pay-a-filipino-virtual-assistant-directly", permanent: true },
      { source: "/blog/medical-virtual-assistant-philippines-guide", destination: "/service/medical-virtual-assistant", permanent: true },
      { source: "/blog/medical-virtual-assistant-philippines-guide/", destination: "/service/medical-virtual-assistant", permanent: true },
      { source: "/rate-project-manager-virtual-assistant", destination: "/blog/hourly-rates-for-filipino-virtual-project-manager", permanent: true },
      { source: "/rate-project-manager-virtual-assistant/", destination: "/blog/hourly-rates-for-filipino-virtual-project-manager", permanent: true },
      { source: "/blog/rate-project-manager-virtual-assistant", destination: "/blog/hourly-rates-for-filipino-virtual-project-manager", permanent: true },
      { source: "/blog/rate-project-manager-virtual-assistant/", destination: "/blog/hourly-rates-for-filipino-virtual-project-manager", permanent: true },
      { source: "/blog/virtual-assistant-hourly-rate-philippines", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/virtual-assistant-hourly-rate-philippines/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/virtual-assistant-outsourcing-guide", destination: "/outsourcing-philippines-virtual-assistant", permanent: true },
      { source: "/blog/virtual-assistant-outsourcing-guide/", destination: "/outsourcing-philippines-virtual-assistant", permanent: true },
      { source: "/blog/virtual-assistant-services-philippines-guide", destination: "/services", permanent: true },
      { source: "/blog/virtual-assistant-services-philippines-guide/", destination: "/services", permanent: true },
      { source: "/blog/average-hourly-rate-for-virtual-assistants-in-the-philippines-in-depth-2026-guide", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/how-much-virtual-assistant-philippines", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/how-to-hire-a-ecommerce", destination: "/service/ecommerce", permanent: true },
      { source: "/blog/how-to-hire-a-ecommerce/", destination: "/service/ecommerce", permanent: true },
      { source: "/blog/hire-ecommerce-virtual-assistant-philippines", destination: "/service/ecommerce", permanent: true },
      { source: "/blog/seo-virtual-assistant-philippines-guide", destination: "/service/seo", permanent: true },
      { source: "/blog/seo-virtual-assistant-philippines-guide/", destination: "/service/seo", permanent: true },
      { source: "/blog/benefits-of-hiring-filipino-virtual-assistants", destination: "/", permanent: true },
      { source: "/sign-in", destination: "/auth/login", permanent: true },
      { source: "/sign-in/", destination: "/auth/login", permanent: true },
      { source: "/virtual-assistant-agency-philippines-guide", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/virtual-assistant-agency-philippines-guide/", destination: "/blog/hire-virtual-assistant-philippines", permanent: true },
      { source: "/virtual-assistant-hourly-rate-philippines", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/virtual-assistant-hourly-rate-philippines/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/virtual-assistant-salary-philippines", destination: "/blog/virtual-assistant-salary-philippines", permanent: true },
      { source: "/virtual-assistant-salary-philippines/", destination: "/blog/virtual-assistant-salary-philippines", permanent: true },
      { source: "/virtual-assistants", destination: "/find-talent", permanent: true },
      { source: "/virtual-assistants/", destination: "/find-talent", permanent: true },
      { source: "/average-hourly-rate-for-virtual-assistants-in-the-philippines-in-depth-2026-guide", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/average-hourly-rate-for-virtual-assistants-in-the-philippines-in-depth-2026-guide/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/why-philippines", destination: "/", permanent: true },
      { source: "/why-philippines/", destination: "/", permanent: true },
      { source: "/hire-a-va/", destination: "/find-talent", permanent: true },
      { source: "/virtual-assistant-jobs/", destination: "/jobs", permanent: true },
      { source: "/client-dashboard/", destination: "/workspace/client", permanent: false },
      { source: "/va-dashboard/", destination: "/workspace/va", permanent: false },
      { source: "/account/", destination: "/auth/login", permanent: false }
    ];
  },
  experimental: {
    serverActions: {
      bodySizeLimit: "8mb"
    }
  }
};

export default nextConfig;
