import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  async redirects() {
    return [
      // Recovered from the previous WordPress site's 404 report.
      { source: "/blog-onboard-your-va", destination: "/blog", permanent: true },
      { source: "/blog-onboard-your-va/", destination: "/blog", permanent: true },
      { source: "/blog-tasks-to-delegate-first", destination: "/blog", permanent: true },
      { source: "/blog-tasks-to-delegate-first/", destination: "/blog", permanent: true },
      { source: "/blog/average-hourly-rate-virtual-assistants-philippines", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/average-hourly-rate-virtual-assistants-philippines/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/blog/first-5-tasks-to-delegate", destination: "/blog", permanent: true },
      { source: "/blog/first-5-tasks-to-delegate/", destination: "/blog", permanent: true },
      { source: "/blog/outsourcing-philippines-virtual-assistant", destination: "/outsourcing-philippines-virtual-assistant", permanent: true },
      { source: "/blog/outsourcing-philippines-virtual-assistant/", destination: "/outsourcing-philippines-virtual-assistant", permanent: true },
      { source: "/blog/where-to-find-virtual-assistants-philippines", destination: "/where-to-find-virtual-assistants-philippines", permanent: true },
      { source: "/blog/where-to-find-virtual-assistants-philippines/", destination: "/where-to-find-virtual-assistants-philippines", permanent: true },
      { source: "/blogs", destination: "/blog", permanent: true },
      { source: "/blogs/", destination: "/blog", permanent: true },
      { source: "/career", destination: "/jobs", permanent: true },
      { source: "/career/", destination: "/jobs", permanent: true },
      { source: "/faqs", destination: "/faq", permanent: true },
      { source: "/faqs/", destination: "/faq", permanent: true },
      { source: "/home", destination: "/", permanent: true },
      { source: "/home/", destination: "/", permanent: true },
      { source: "/how-it-works", destination: "/how-vetting-works", permanent: true },
      { source: "/how-it-works/", destination: "/how-vetting-works", permanent: true },
      { source: "/how-to-become-bookkeeping-virtual-assistant", destination: "/blog/how-to-become-bookkeeping-virtual-assistant", permanent: true },
      { source: "/how-to-become-bookkeeping-virtual-assistant/", destination: "/blog/how-to-become-bookkeeping-virtual-assistant", permanent: true },
      { source: "/how-to-get-paid-as-a-virtual-assistant-in-the-philippines-by-international-clients", destination: "/blog/get-paid-virtual-assistant-philippines", permanent: true },
      { source: "/how-to-get-paid-as-a-virtual-assistant-in-the-philippines-by-international-clients/", destination: "/blog/get-paid-virtual-assistant-philippines", permanent: true },
      { source: "/how-to-hire-a-virtual-assistant-in-the-philippines-a-complete-guide-for-business-owners", destination: "/blog/how-to-hire-a-virtual-assistant-philippines", permanent: true },
      { source: "/how-to-hire-a-virtual-assistant-in-the-philippines-a-complete-guide-for-business-owners/", destination: "/blog/how-to-hire-a-virtual-assistant-philippines", permanent: true },
      { source: "/join", destination: "/auth/join/client", permanent: true },
      { source: "/join/", destination: "/auth/join/client", permanent: true },
      { source: "/my-account", destination: "/auth/login", permanent: true },
      { source: "/my-account/", destination: "/auth/login", permanent: true },
      { source: "/privacy-policy", destination: "/privacy", permanent: true },
      { source: "/privacy-policy/", destination: "/privacy", permanent: true },
      { source: "/seo", destination: "/service/seo", permanent: true },
      { source: "/seo/", destination: "/service/seo", permanent: true },
      { source: "/service-admin", destination: "/services", permanent: true },
      { source: "/service-admin/", destination: "/services", permanent: true },
      { source: "/service-bookkeeping", destination: "/services", permanent: true },
      { source: "/service-bookkeeping/", destination: "/services", permanent: true },
      { source: "/service-content-writing", destination: "/services", permanent: true },
      { source: "/service-content-writing/", destination: "/services", permanent: true },
      { source: "/service-digital-marketing", destination: "/services", permanent: true },
      { source: "/service-digital-marketing/", destination: "/services", permanent: true },
      { source: "/service-ecommerce", destination: "/services", permanent: true },
      { source: "/service-ecommerce/", destination: "/services", permanent: true },
      { source: "/service-lead-generation", destination: "/services", permanent: true },
      { source: "/service-lead-generation/", destination: "/services", permanent: true },
      { source: "/service-real-estate", destination: "/services", permanent: true },
      { source: "/service-real-estate/", destination: "/services", permanent: true },
      { source: "/service-seo", destination: "/service/seo", permanent: true },
      { source: "/service-seo/", destination: "/service/seo", permanent: true },
      { source: "/service-video-editing", destination: "/services", permanent: true },
      { source: "/service-video-editing/", destination: "/services", permanent: true },
      { source: "/service/crm-management", destination: "/service/crm", permanent: true },
      { source: "/service/crm-management/", destination: "/service/crm", permanent: true },
      { source: "/service/order-fulfilment", destination: "/service/fulfilment", permanent: true },
      { source: "/service/order-fulfilment/", destination: "/service/fulfilment", permanent: true },
      { source: "/service/research-data-entry", destination: "/service/research-data", permanent: true },
      { source: "/service/research-data-entry/", destination: "/service/research-data", permanent: true },
      { source: "/services/social-media", destination: "/service/social-media", permanent: true },
      { source: "/sign-in", destination: "/auth/login", permanent: true },
      { source: "/sign-in/", destination: "/auth/login", permanent: true },
      { source: "/virtual-assistant-agency-philippines-guide", destination: "/blog/virtual-assistant-agency-philippines-guide", permanent: true },
      { source: "/virtual-assistant-agency-philippines-guide/", destination: "/blog/virtual-assistant-agency-philippines-guide", permanent: true },
      { source: "/virtual-assistant-hourly-rate-philippines", destination: "/blog/virtual-assistant-hourly-rate-philippines", permanent: true },
      { source: "/virtual-assistant-hourly-rate-philippines/", destination: "/blog/virtual-assistant-hourly-rate-philippines", permanent: true },
      { source: "/virtual-assistant-salary-philippines", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/virtual-assistant-salary-philippines/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/virtual-assistants", destination: "/find-talent", permanent: true },
      { source: "/virtual-assistants/", destination: "/find-talent", permanent: true },
      { source: "/average-hourly-rate-for-virtual-assistants-in-the-philippines-in-depth-2026-guide", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/average-hourly-rate-for-virtual-assistants-in-the-philippines-in-depth-2026-guide/", destination: "/average-hourly-rate-virtual-assistants-philippines", permanent: true },
      { source: "/why-philippines", destination: "/", permanent: true },
      { source: "/why-philippines/", destination: "/", permanent: true },
      { source: "/hire-a-va/", destination: "/find-talent", permanent: true },
      { source: "/virtual-assistant-jobs/", destination: "/jobs", permanent: true },
      { source: "/client-dashboard/", destination: "/workspace/client", permanent: false },
      { source: "/va-dashboard/", destination: "/workspace/va", permanent: false },
      { source: "/account/", destination: "/auth/login", permanent: false }
    ];
  },
  experimental: {
    serverActions: {
      bodySizeLimit: "8mb"
    }
  }
};

export default nextConfig;
