import Link from "next/link";
import { notFound } from "next/navigation";
import { CheckCircle2, Sparkles } from "lucide-react";
import { requireRoleFast } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { acceptCommercialTermsAction, closeJobAction, saveClientRoleReadinessDetailsAction } from "@/app/actions/jobs";
import { dateShort, money } from "@/lib/format";
import { mergeUniqueStrings, uniqueStrings } from "@/lib/collections";
import { candidateAccessLabel } from "@/lib/candidate-access";
import { RoleReadinessForm } from "@/components/role-readiness-form";

export default async function ClientJobDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const {id}=await params;const query=await searchParams;const {userId}=await requireRoleFast("client");const supabase=await createClient();const {data:job}=await supabase.from("jobs").select("*").eq("id",id).eq("client_id",userId).single();if(!job)notFound();
  const admin=createAdminClient();
  const [{data:commercial},{data:access},{data:releasedRows},{data:interviews},{data:offers},{data:workrooms}]=await Promise.all([
    supabase.from("job_commercials").select("*").eq("job_id",id).maybeSingle(),
    admin.from("job_candidate_access").select("access_status").eq("job_id",id).maybeSingle(),
    admin.from("job_shortlist_candidates").select("id,client_decision").eq("job_id",id).eq("shortlist_status","released"),
    admin.from("candidate_interviews").select("id,status,client_decision").eq("job_id",id).neq("status","cancelled"),
    admin.from("placement_offers").select("id,status").eq("job_id",id),
    admin.from("workrooms").select("id,status").eq("job_id",id)
  ]);
  const released=releasedRows||[];const waitingDecisions=released.filter((row:any)=>!row.client_decision).length;const interested=released.filter((row:any)=>row.client_decision==="interested").length;const interviewCount=(interviews||[]).filter((row:any)=>["requested","scheduled","completed"].includes(row.status)).length;const activeOfferCount=(offers||[]).filter((row:any)=>["pending_va","pending_client"].includes(row.status)).length;const hired=(workrooms||[]).some((row:any)=>row.status==="active");
  const roleApproved=job.status==="published"||commercial?.commercial_status==="accepted";
  const progress=hired?{title:"Placement active",copy:"The confirmed VA is now in the workroom for onboarding, tasks, approved time, and ongoing support.",href:"/workspace/client/workroom",label:"Open workroom"}:activeOfferCount?{title:"Final terms are in progress",copy:"Your recruiter prepared the placement terms. The VA accepts first, then you confirm the placement.",href:"/workspace/client/offers",label:"Review offer"}:interviewCount?{title:"Interview stage",copy:"Manage interview times and record a simple Proceed, Hold, or Pass decision so the recruiter can act.",href:"/workspace/client/interviews",label:"Open interviews"}:released.length?{title:`${released.length} recruiter-selected candidate${released.length===1?"":"s"}`,copy:waitingDecisions?`${waitingDecisions} shortlist decision${waitingDecisions===1?"":"s"} waiting on you.`:interested?"Your recruiter has your interest feedback and will coordinate the next step.":"Your recruiter is reviewing your feedback and replacement needs.",href:`/workspace/client/candidates?role=${job.id}`,label:"Open recruiter shortlist"}:roleApproved?{title:"Recruiting in progress",copy:"Your recruiter is screening the vetted pool against the approved brief before presenting anyone to you.",href:"/workspace/client/support",label:"Contact your recruiter"}:{title:"Hiring request under review",copy:"We are confirming the brief and service terms before client-facing recruiting begins.",href:"/workspace/client/support",label:"Contact your recruiter"};

  return <div className="client-role-detail-page">
    {query.saved?<div className="success-banner" role="status"><CheckCircle2 size={17}/> Hiring request saved.</div>:null}
    {query.role_details_saved?<div className="success-banner" role="status"><CheckCircle2 size={17}/> Hiring brief completed. Your recruiter can see the update.</div>:null}
    <div className="page-head client-role-detail-head"><div><Link className="text-link small" href="/workspace/client/jobs">← Hiring requests</Link><div className="row wrap" style={{marginTop:8}}><span className={`badge ${job.status==="published"?"badge-success":job.status==="pending"?"badge-warning":""}`}>{job.status==="published"?"Recruiting":job.status==="pending"?"In review":String(job.status).replaceAll("_"," ")}</span><span className="small muted">Created {dateShort(job.created_at)}</span></div><h1 style={{marginTop:8}}>{job.title}</h1><p>{job.company_name||"Your company"} · {job.hours_per_week?`${job.hours_per_week} hrs/week`:"Flexible hours"} · VA compensation from {money(job.min_hourly_rate)}/hr</p></div><div className="row wrap client-role-detail-actions">{job.status!=="closed"?<Link className="btn" href={`/workspace/client/jobs/${job.id}/edit`}>Edit request</Link>:null}{job.status!=="closed"?<form action={closeJobAction}><input type="hidden" name="job_id" value={job.id}/><button className="btn btn-danger" type="submit">Close request</button></form>:null}</div></div>

    {job.status==="pending"?<div className="alert" style={{marginBottom:18}}>{commercial?.commercial_status==="quoted"?"Your hiring brief has been reviewed. Approve the service terms below so your recruiter can begin the client-facing hiring process.":"Your hiring request is with our team. The recruiter can prepare internally while the brief and commercial terms are confirmed."}</div>:null}
    {job.rejection_note?<div className="alert" style={{marginBottom:18}}><strong>Review note:</strong> {job.rejection_note}</div>:null}
    {job.status!=="closed"?<RoleReadinessForm job={job} returnTo={`/workspace/client/jobs/${job.id}`} action={saveClientRoleReadinessDetailsAction} audience="client"/>:null}

    <section className="candidate-next-action client-role-next-action" style={{marginBottom:18}}><div className="candidate-next-icon"><Sparkles size={21}/></div><div><span className="small">Current stage</span><h2>{progress.title}</h2><p>{progress.copy}</p></div><Link className="btn btn-primary" href={progress.href}>{progress.label}</Link></section>

    <div className="card commercial-card client-role-commercial" style={{marginBottom:18}}><div className="row-between wrap"><div><div className="small muted">Hiring service</div><strong>{job.service_model==="managed_service"?"Managed Virtual Assistant service":"Vetted recruiting placement"}</strong><div className="small muted">VA compensation is separate from the agency service fee.</div></div><div><div className="small muted">Service terms</div><strong>{commercial?commercial.service_model==="managed_service"?`${commercial.managed_markup_percent||0}% managed-service margin`:`USD ${commercial.placement_fee||0} placement fee`:"Confirmed during role review"}</strong>{commercial?<div className="small muted">Status: {String(commercial.commercial_status).replaceAll("_"," ")}</div>:null}</div></div>{commercial?.commercial_status==="quoted"?<form action={acceptCommercialTermsAction} style={{marginTop:14}}><input type="hidden" name="job_id" value={job.id}/><label className="confirmation-check" style={{marginBottom:12}}><input type="checkbox" name="fee_ack" required/><span>I understand this agency service fee is separate from the Virtual Assistant&apos;s compensation.</span></label><button className="btn btn-primary" type="submit">Approve terms and start recruiting</button></form>:null}</div>

    <div className="grid-3 client-role-stats" style={{marginBottom:18}}><div className="card"><div className="small muted">Recruiter shortlist</div><strong style={{fontSize:28}}>{released.length}</strong><div className="small muted">Only vetted, recruiter-selected VAs</div></div><div className="card"><div className="small muted">Interviews</div><strong style={{fontSize:28}}>{interviewCount}</strong><div className="small muted">Coordinated through the hiring workflow</div></div><div className="card"><div className="small muted">Candidate access</div><strong style={{fontSize:18}}>{candidateAccessLabel(access?.access_status)}</strong><div className="small muted">Activated with approved service terms</div></div></div>

    <section className="card client-role-handling" style={{marginBottom:18}}><div className="row-between wrap"><div><h2 style={{margin:0}}>How this role is being handled</h2><p className="small muted">You do not need to manage raw applicants. We qualify, screen, and shortlist before asking you for a decision.</p></div>{released.length?<Link className="btn btn-primary btn-sm" href={`/workspace/client/candidates?role=${job.id}`}>Review shortlist</Link>:null}</div><ol className="candidate-access-steps" style={{marginTop:14}}><li>Recruiter confirms the brief and hard requirements</li><li>Recruiter screens vetted VAs and checks schedule, rate, evidence, and capacity</li><li>You review only the curated shortlist</li><li>We coordinate interview and final terms</li><li>Confirmed placement opens the managed workroom</li></ol></section>

    <section className="card client-role-brief"><div className="dashboard-section-head"><div><h2>Approved role brief</h2><p>The recruiting team uses this information to evaluate fit.</p></div></div><div className="role-match-brief client-role-brief-grid"><div><strong>Timezone</strong><p className="muted">{job.timezone||"Not set"}</p></div><div><strong>Hours</strong><p className="muted">{job.hours_per_week?`${job.hours_per_week} hrs/week`:"Flexible"}</p></div><div><strong>Experience level</strong><p className="muted">{job.experience_level||"Not set"}</p></div><div><strong>Start timing</strong><p className="muted">{job.start_timing||"Not set"}</p></div><div><strong>Categories</strong><p className="muted">{uniqueStrings(job.categories).join(", ")||"Not set"}</p></div><div><strong>Skills & tools</strong><p className="muted">{mergeUniqueStrings(job.required_skills,job.required_tools).join(", ")||"Not set"}</p></div>{job.summary?<div className="span-2"><strong>Summary</strong><p className="muted">{job.summary}</p></div>:null}{job.description?<div className="span-2"><strong>Description</strong><p className="muted" style={{whiteSpace:"pre-wrap"}}>{job.description}</p></div>:null}</div></section>
  </div>;
}
