import { AlertTriangle, CheckCircle2, Mail, ShieldX } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { dateShort } from "@/lib/format";
type EmailRow={id:string;event_type:string|null;recipient:string|null;status:string;error_message:string|null;created_at:string};
export default async function AdminEmailHealthPage(){
 await requireRole("admin"); const admin=createAdminClient(); const since=new Date(Date.now()-86400000).toISOString();
 const [eventsRes,suppressionsRes]=await Promise.all([
  admin.from("outbound_email_events").select("id,event_type,recipient,status,error_message,created_at").gte("created_at",since).order("created_at",{ascending:false}).limit(500),
  admin.from("email_suppressions").select("email,reason,suppressed_at").order("suppressed_at",{ascending:false}).limit(100)
 ]);
 const events=(eventsRes.data||[]) as EmailRow[]; const suppressions=suppressionsRes.data||[];
 const delivered=events.filter(e=>["sent","delivered"].includes(e.status)).length; const failed=events.filter(e=>e.status==="failed").length; const bounced=events.filter(e=>e.status==="bounced").length; const quota=events.filter(e=>/quota|rate limit|daily/i.test(e.error_message||"")).length;
 const byType=new Map<string,{total:number;failed:number}>(); for(const e of events){const key=e.event_type||"unknown";const v=byType.get(key)||{total:0,failed:0};v.total++;if(["failed","bounced","suppressed","complained"].includes(e.status))v.failed++;byType.set(key,v);} const types=[...byType.entries()].sort((a,b)=>b[1].total-a[1].total).slice(0,12);
 return <><div className="page-head"><div><div className="kicker">Email operations</div><h1>Email health</h1><p>See what is consuming mail volume, which messages fail, and which recipients are automatically suppressed.</p></div></div>
 <div className="health-grid"><div className="health-card ok"><CheckCircle2 size={19}/><div><span>Sent / delivered (24h)</span><strong>{delivered}</strong><small>Transactional and automated mail</small></div></div><div className={"health-card "+(failed?"warn":"ok")}><AlertTriangle size={19}/><div><span>Failed (24h)</span><strong>{failed}</strong><small>Provider or recipient failures</small></div></div><div className={"health-card "+(bounced?"warn":"ok")}><Mail size={19}/><div><span>Bounced (24h)</span><strong>{bounced}</strong><small>Hard delivery failures</small></div></div><div className={"health-card "+(quota?"warn":"ok")}><ShieldX size={19}/><div><span>Quota errors (24h)</span><strong>{quota}</strong><small>Capacity failures that can block critical mail</small></div></div><div className="health-card"><ShieldX size={19}/><div><span>Suppressed recipients</span><strong>{suppressions.length}</strong><small>Known bad addresses blocked from future sends</small></div></div></div>
 <div className="grid-2"><section className="card"><h2>Email volume by automation</h2><p className="muted">Last 24 hours. High-volume reminder jobs should stay below critical transactional traffic.</p>{types.length?<div className="compact-list">{types.map(([name,v])=><div className="compact-static" key={name}><span><strong>{name.replaceAll("_"," ")}</strong><small>{v.failed?String(v.failed)+" failed":"No recorded failures"}</small></span><strong>{v.total}</strong></div>)}</div>:<div className="empty">No email events in the last 24 hours.</div>}</section>
 <section className="card"><h2>Suppression list</h2><p className="muted">Bounce, complaint, and provider-suppressed recipients are skipped automatically.</p>{suppressions.length?<div className="compact-list">{suppressions.slice(0,30).map((r:any)=><div className="compact-static" key={r.email}><span><strong>{r.email}</strong><small>{r.reason}</small></span><small>{dateShort(r.suppressed_at)}</small></div>)}</div>:<div className="empty">No suppressed recipients.</div>}</section></div>
 <section className="card" style={{marginTop:18}}><h2>Recent delivery problems</h2>{events.some(e=>["failed","bounced","suppressed","complained"].includes(e.status))?<div className="compact-list">{events.filter(e=>["failed","bounced","suppressed","complained"].includes(e.status)).slice(0,50).map(e=><div className="compact-static" key={e.id}><span><strong>{(e.event_type||"email").replaceAll("_"," ")}</strong><small>{e.status+" · "+(e.error_message||"Provider delivery event")+(e.recipient?" · "+e.recipient:"")}</small></span><small>{dateShort(e.created_at)}</small></div>)}</div>:<div className="empty">No delivery problems in the last 24 hours.</div>}</section></>;
}