import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, UserRoundCheck } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { submitContactAction } from "@/app/actions/leads";
import { canonicalPath } from "@/lib/seo-url";

export const metadata:Metadata={title:"Contact VirtualAssistant.com.ph",description:"Contact VirtualAssistant.com.ph about hiring a Virtual Assistant, account support, partnerships, privacy, or general questions.",keywords:["contact virtualassistant.com.ph","virtual assistant support"],alternates:{canonical:canonicalPath("/contact")}};
export default async function ContactPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const q=await searchParams;return <><SiteHeader/><main id="main-content"><section className="section public-hero-small"><div className="container public-page-head"><h1 className="public-page-title">What can we help with?</h1><p className="public-lede">Pick the option that matches you — it is faster than the form for both. Prefer to talk it through? <a className="text-link" href="https://calendar.app.google/FxedmioyeJhKras87" target="_blank" rel="noopener noreferrer">Book a 15-minute call</a>.</p></div></section><section className="section section-white"><div className="container" style={{maxWidth:760}}><div className="contact-routing">
      <Link className="contact-routing-card" href="/auth/join/va"><span className="contact-routing-icon"><UserRoundCheck size={22}/></span><span><strong>I am a Virtual Assistant looking for work</strong><small>Do not use the form below — we do not accept applications by email. Create your free profile, complete vetting, and apply to roles directly.</small><span className="contact-routing-link">Apply as a Virtual Assistant <ArrowRight size={14}/></span></span></Link>
      <Link className="contact-routing-card" href="/hire"><span className="contact-routing-icon"><BriefcaseBusiness size={22}/></span><span><strong>I want to hire a Virtual Assistant</strong><small>Tell us the role, hours, timezone, and budget. Our recruiting team will review it and help you find the right fit.</small><span className="contact-routing-link">Start a hiring request <ArrowRight size={14}/></span></span></Link>
    </div>
    <div className="contact-form-divider"><span>Something else? Send a message</span></div>
    {q.sent?<div className="success-state"><CheckCircle2 size={36}/><h2>Message received</h2><p>Your message was saved for follow-up.</p><Link className="btn" href="/">Return home</Link></div>:<form action={submitContactAction} className="card stack"><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1}/></label></div>{q.error?<div className="alert" role="alert">{q.error}</div>:null}<div className="form-grid"><div className="field"><label htmlFor="contact-name">Name *</label><input id="contact-name" name="name" required autoComplete="name"/></div><div className="field"><label htmlFor="contact-email">Email *</label><input id="contact-email" name="email" type="email" required autoComplete="email"/></div><div className="field"><label htmlFor="contact-company">Company</label><input id="contact-company" name="company" autoComplete="organization"/></div><div className="field"><label htmlFor="contact-topic">Topic *</label><select id="contact-topic" name="topic" required defaultValue=""><option value="" disabled>Select a topic</option><option>Client account support</option><option>Virtual Assistant account or application</option><option>Partnership</option><option>Privacy or data request</option><option>General enquiry</option></select></div></div><div className="field"><label htmlFor="contact-message">Message *</label><textarea id="contact-message" name="message" required minLength={20} placeholder="Share the relevant account, role, or situation and what you need help with."/></div><button className="btn btn-primary" type="submit">Send message</button></form>}</div></section></main><SiteFooter/></>}
