import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { submitContactAction } from "@/app/actions/leads";

export const metadata:Metadata={title:"Contact VirtualAssistant.com.ph",description:"Send a hiring, account, VA, partnership, or general question to VirtualAssistant.com.ph.",keywords:["contact virtualassistant.com.ph","virtual assistant support"]};
export default async function ContactPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const q=await searchParams;return <><SiteHeader/><main id="main-content"><section className="section public-hero-small"><div className="container public-page-head"><h1 className="public-page-title">What can we help with?</h1><p className="public-lede">For a new hiring request, the role brief is the fastest way to provide the details needed for matching. For everything else, send a message below.</p><Link className="text-link" href="/hire">Starting a hire? Get a managed VA →</Link></div></section><section className="section section-white"><div className="container" style={{maxWidth:760}}>{q.sent?<div className="success-state"><CheckCircle2 size={36}/><h2>Message received</h2><p>Your message was saved for follow-up.</p><Link className="btn" href="/">Return home</Link></div>:<form action={submitContactAction} className="card stack"><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1}/></label></div>{q.error?<div className="alert" role="alert">{q.error}</div>:null}<div className="form-grid"><div className="field"><label htmlFor="contact-name">Name *</label><input id="contact-name" name="name" required autoComplete="name"/></div><div className="field"><label htmlFor="contact-email">Email *</label><input id="contact-email" name="email" type="email" required autoComplete="email"/></div><div className="field"><label htmlFor="contact-company">Company</label><input id="contact-company" name="company" autoComplete="organization"/></div><div className="field"><label htmlFor="contact-topic">Topic *</label><select id="contact-topic" name="topic" required defaultValue=""><option value="" disabled>Select a topic</option><option>Client account support</option><option>VA account or application</option><option>Partnership</option><option>Privacy or data request</option><option>General enquiry</option></select></div></div><div className="field"><label htmlFor="contact-message">Message *</label><textarea id="contact-message" name="message" required minLength={20} placeholder="Share the relevant account, role, or situation and what you need help with."/></div><button className="btn btn-primary" type="submit">Send message</button></form>}</div></section></main><SiteFooter/></>}
