import Link from "next/link";
import { CheckCircle2, Clock3 } from "lucide-react";
import { requireRoleFast } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { respondPlacementOfferAction } from "@/app/actions/recruiter-operations-system";

export default async function VaOffersPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const query=await searchParams;const {userId}=await requireRoleFast("va");const admin=createAdminClient();
  const {data:offers,error}=await admin.from("placement_offers").select("*").eq("va_id",userId).order("created_at",{ascending:false}).limit(100);if(error)throw error;
  const jobIds=[...new Set((offers||[]).map((row:any)=>row.job_id))];const {data:jobs}=jobIds.length?await admin.from("jobs").select("id,title,company_name").in("id",jobIds):{data:[] as any[]};const jobMap=new Map((jobs||[]).map((row:any)=>[row.id,row]));
  return <div className="va-offers-page">
    {query.accepted?<div className="success-banner">Offer accepted. The client now has the final confirmation step.</div>:null}{query.declined?<div className="success-banner">Offer declined. The recruiting team has been notified.</div>:null}
    <div className="page-head va-offers-head"><div><div className="kicker">Placement</div><h1>Offers</h1><p>Review final rate, hours, schedule, and start date before accepting.</p></div><Link className="btn va-offers-overview" href="/workspace/va">Overview</Link></div>
    <div className="stack va-offers-list">{offers?.length?offers.map((offer:any)=>{const job:any=jobMap.get(offer.job_id)||{};return <section className="card va-offer-card" key={offer.id}><div className="row-between wrap va-offer-summary"><div><div className="row wrap"><span className={`badge ${offer.status==="accepted"?"badge-success":""}`}>{String(offer.status).replaceAll("_"," ")}</span></div><h2 style={{margin:"8px 0 4px"}}>{job.title||"Client role"}</h2><p className="small muted">{job.company_name||"Client"}</p></div>{offer.status==="accepted"?<CheckCircle2 size={22}/>:<Clock3 size={22}/>}</div><div className="score-grid va-offer-terms" style={{marginTop:14}}><div><span>Rate</span><strong>USD {Number(offer.hourly_rate).toFixed(2)}/hr</strong></div><div><span>Hours</span><strong>{offer.weekly_hours}/week</strong></div><div><span>Start</span><strong>{offer.start_date}</strong></div><div><span>Timezone</span><strong>{offer.timezone||"As agreed"}</strong></div><div className="span-2"><span>Schedule</span><strong>{offer.schedule}</strong></div></div>{offer.notes?<div className="review-answer va-offer-note" style={{marginTop:14}}><strong>Offer note</strong><p>{offer.notes}</p></div>:null}{offer.status==="pending_va"?<div className="row wrap va-offer-actions" style={{marginTop:16}}><form action={respondPlacementOfferAction}><input type="hidden" name="offer_id" value={offer.id}/><input type="hidden" name="decision" value="accept"/><button className="btn btn-primary" type="submit">Accept final terms</button></form><form action={respondPlacementOfferAction}><input type="hidden" name="offer_id" value={offer.id}/><input type="hidden" name="decision" value="decline"/><button className="btn" type="submit">Decline</button></form></div>:null}{offer.status==="pending_client"?<div className="alert" style={{marginTop:14}}>You accepted. Waiting for client confirmation before onboarding starts.</div>:null}{offer.status==="accepted"?<div className="success-banner" style={{marginTop:14}}>Placement confirmed. <Link className="text-link" href="/workspace/va/workroom">Open your workroom</Link>.</div>:null}</section>}):<div className="empty">No placement offers yet.</div>}</div>
  </div>;
}
