import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { matchAssessment, matchLabel } from "@/lib/matching";
import { money } from "@/lib/format";
import { saveJobAction } from "@/app/actions/applications";
import { jobPublicHref } from "@/lib/public-routing";
import { uniqueStrings } from "@/lib/collections";

export default async function VaJobsPage(){const {user}=await requireRole("va");const supabase=await createClient();const [{data:va},{data:jobs},{data:saved},{data:apps}]=await Promise.all([supabase.from("va_profiles").select("*").eq("user_id",user.id).single(),supabase.from("jobs").select("*").eq("status","published").order("published_at",{ascending:false}).limit(80),supabase.from("saved_jobs").select("job_id").eq("va_id",user.id),supabase.from("applications").select("job_id,status").eq("va_id",user.id)]);const savedSet=new Set((saved||[]).map((x:any)=>x.job_id));const appMap=new Map((apps||[]).map((x:any)=>[x.job_id,x.status]));const ranked=(jobs||[]).map((job:any)=>({job,...matchAssessment(job,va||{})})).sort((a,b)=>b.score-a.score);return <><div className="page-head"><div><h1>Find jobs</h1><p>Roles are ranked using known specialty, skills, tools, availability, and live-overlap data. Missing data lowers confidence instead of earning match points.</p></div><Link className="btn" href="/workspace/va/profile">Improve matching data</Link></div><div className="stack">{ranked.length?ranked.map(({job,score,confidence}:any)=><div className="card job-card" key={job.id}><div className="job-card-top"><div><div className="row wrap"><span className="badge badge-success">Open</span>{appMap.has(job.id)?<span className="badge">Applied: {appMap.get(job.id)}</span>:null}</div><h3 style={{marginTop:8}}><Link href={jobPublicHref(job)}>{job.title}</Link></h3><div className="small muted">{job.company_name||"Confidential client"}</div></div><div className="fit-badge"><strong>{matchLabel(score)}</strong><span>{score}/100</span></div></div><p className="muted" style={{margin:0}}>{job.summary}</p><div className="small muted">Match confidence: {confidence}% of weighted criteria could be assessed from the role and your profile.</div><div className="job-meta"><span>{job.hours_per_week?`${job.hours_per_week} hrs/week`:"Flexible hours"}</span><span>from {money(job.min_hourly_rate)}/hr</span><span>{job.timezone||"Flexible timezone"}</span></div><div className="pill-list">{uniqueStrings(job.categories).map((x,index)=><span className="badge" key={`${String(x)}-${index}`}>{x}</span>)}</div><div className="row wrap"><Link className="btn btn-primary btn-sm" href={jobPublicHref(job)}>{appMap.has(job.id)?"View application job":"View and apply"}</Link><form action={saveJobAction}><input type="hidden" name="job_id" value={job.id}/><button className="btn btn-sm" type="submit">{savedSet.has(job.id)?"Unsave":"Save job"}</button></form></div></div>):<div className="card empty">There are no published jobs right now.</div>}</div></>}
