import Link from "next/link";
import { CheckCircle2, Clock3, Eye, ShieldCheck } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { updateVaProfileAction } from "@/app/actions/profile";
import { confirmVaAvailabilityAction } from "@/app/actions/agency-operations-v2";
import { saveVaWorkSetupAction } from "@/app/actions/work-readiness";
import { updateVaPublicProfileConsentAction } from "@/app/actions/privacy-consent";
import { LiveProfileStrength } from "@/components/live-profile-strength";
import { ResumeAutoFill } from "@/components/resume-autofill";
import { VA_CATEGORIES } from "@/lib/constants";
import { getBusinessSettings } from "@/lib/business-settings";
import { PUBLIC_PROFILE_CONSENT_VERSION } from "@/lib/privacy-consent";

function availabilityAge(value?:string|null){
  if(!value)return{label:"Not yet confirmed",stale:true};
  const days=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000));
  return{label:days===0?"Confirmed today":days===1?"Confirmed 1 day ago":`Confirmed ${days} days ago`,stale:days>=14};
}

export default async function VaProfilePage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  const params = await searchParams;
  const [{ user, profile },settings] = await Promise.all([requireRole("va"),getBusinessSettings()]);
  const supabase = await createClient();
  const { data: va } = await supabase.from("va_profiles").select("*").eq("user_id", user.id).single();
  const consentGranted = Boolean(va?.public_profile_consent);
  const consentDate = va?.public_profile_consent_at ? new Date(va.public_profile_consent_at).toLocaleDateString("en-PH", { year: "numeric", month: "short", day: "numeric" }) : null;
  const freshness=availabilityAge(va?.availability_confirmed_at);
  const canConfirm=va?.availability_status==="available"&&Boolean(va?.weekly_hours)&&Boolean(va?.schedule)&&Boolean(va?.hourly_rate);
  const workSetupComplete=Boolean(va?.work_setup_computer&&va?.work_setup_os&&va?.work_setup_ram_gb&&va?.primary_internet&&va?.backup_internet&&va?.backup_power&&va?.headset_ready&&va?.webcam_ready&&va?.quiet_workspace);

  return <>
    {params.error ? <div className="alert" role="alert">{params.error}</div> : null}
    {params.saved ? <div className="success-banner" role="status">Profile saved successfully.</div> : null}
    {params.availability_confirmed ? <div className="success-banner" role="status">Availability confirmed. Recruiters can rely on your current hours, schedule, and rate for the next matching cycle.</div> : null}
    {params.consent === "granted" ? <div className="success-banner" role="status">Public profile consent saved. Your profile can appear publicly once all eligibility and approval requirements are met.</div> : null}
    {params.consent === "withdrawn" ? <div className="success-banner" role="status">Public profile consent withdrawn. Your profile is no longer eligible to appear in the public directory.</div> : null}
    <div className="page-head"><div><div className="kicker">Profile & readiness</div><h1>Get ready for client matching</h1><p>Keep your professional profile, availability, work setup, and vetting progress in one place.</p></div><Link className="btn" href="/workspace/va/profile/preview" target="_blank"><Eye size={16}/> Preview profile</Link></div>
    <ResumeAutoFill formId="va-profile-form" />
    <div className="profile-editor-layout">
      <div className="stack">
        <form id="va-profile-form" action={updateVaProfileAction} className="stack profile-editor-form" encType="multipart/form-data">
          <input type="hidden" name="directory_visible" value={va?.directory_visible ? "on" : ""}/>
          <section className="card profile-section" id="basics"><div className="profile-section-head"><div><span>01</span><div><h2>Professional basics</h2><p>Make the first screen clear enough for a client to understand what you do in seconds.</p></div></div></div><div className="form-grid"><div className="field"><label>Full legal name <span className="muted">(private)</span></label><input name="full_name" defaultValue={profile.full_name || ""} required/><span className="field-help">Public pages show first name + last initial only.</span></div><div className="field"><label>Professional headline</label><input name="headline" defaultValue={va?.headline || ""} placeholder="Executive Assistant · Operations · Customer Support"/></div><div className="field span-2"><label>Professional summary</label><textarea name="bio" defaultValue={va?.bio || ""} placeholder="What work do you do best? Which clients have you supported? What outcomes can you own?"/><span className="field-help">Aim for 80–220 words focused on outcomes, not a list of tools.</span></div><div className="field span-2"><label>Profile photo <span className="muted">JPG/PNG/WEBP, max 3 MB</span></label>{profile.avatar_url ? <img src={profile.avatar_url} alt="Current profile photo" style={{width:64,height:64,borderRadius:"50%",objectFit:"cover",display:"block",marginBottom:8}}/> : null}<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" required={!profile.avatar_url}/><span className="field-help">{profile.avatar_url ? "Replace your current photo at any time." : "Required before your VA profile can be completed or published."}</span><span className="field-help">Shown next to your name on your public profile and in the talent directory only if you separately opt in below.</span></div></div></section>

          <section className="card profile-section" id="expertise"><div className="profile-section-head"><div><span>02</span><div><h2>Experience & expertise</h2><p>Your specialty, skills, tools, and experience drive both matching and public-directory eligibility.</p></div></div></div><div className="form-grid"><div className="field"><label>Primary specialty</label><select name="primary_category" defaultValue={va?.primary_category || ""}><option value="">Choose a specialty</option>{VA_CATEGORIES.map((x, index) => <option key={`${String(x)}-${index}`}>{x}</option>)}</select><span className="field-help">Choose your strongest specialty, or leave this blank and we will infer a best-fit category from your headline, summary, skills, tools, and industries when you save.</span></div><div className="field"><label>Years of professional experience</label><input type="number" min="0" max="60" name="years_experience" defaultValue={va?.years_experience ?? ""}/><span className="field-help">Public discovery requires at least 2 years.</span></div><div className="field span-2"><label>Additional specialties <span className="muted">(up to 3)</span></label><input name="categories" defaultValue={(va?.categories || []).join(", ")} placeholder="Customer Service, Ecommerce"/></div><div className="field span-2"><label>Core skills</label><input name="skills" defaultValue={(va?.skills || []).join(", ")} placeholder="Calendar management, recruitment coordination, customer support, reporting, research"/><span className="field-help">Add at least 5 specific skills. Separate them with commas.</span></div><div className="field span-2"><label>Tools & software</label><input name="tools" defaultValue={(va?.tools || []).join(", ")} placeholder="Google Workspace, HubSpot, Slack, Canva, ClickUp"/><span className="field-help">Add tools you can use without training.</span></div><div className="field"><label>Industries</label><input name="industries" defaultValue={(va?.industries || []).join(", ")} placeholder="SaaS, dental, real estate"/></div><div className="field"><label>Languages</label><input name="languages" defaultValue={(va?.languages || []).join(", ")} placeholder="English, Filipino"/></div></div></section>

          <section className="card profile-section" id="availability"><div className="profile-section-head"><div><span>03</span><div><h2>Availability & rate</h2><p>Keep this current so recruiters do not present you for schedules or rates that no longer work.</p></div></div><span className={`badge ${freshness.stale?"badge-warning":"badge-success"}`}><Clock3 size={13}/>{freshness.label}</span></div><div className="form-grid"><div className="field"><label>Hours available per week</label><input type="number" min="1" max="80" name="weekly_hours" defaultValue={va?.weekly_hours || ""}/></div><div className="field"><label>Preferred hourly rate, USD</label><input type="number" min={settings.minHourlyRate} step="0.01" name="hourly_rate" defaultValue={va?.hourly_rate || ""}/><span className="field-help">Current agency minimum: USD {settings.minHourlyRate}/hour.</span></div><div className="field"><label>Preferred schedule</label><input name="schedule" defaultValue={va?.schedule || ""} placeholder="Flexible · Evening PH · US overlap"/></div><div className="field"><label>Maximum live client overlap/day</label><input type="number" min="0" max="12" name="overlap_hours" defaultValue={va?.overlap_hours ?? 4}/></div><div className="field"><label>Availability status</label><select name="availability_status" defaultValue={va?.availability_status || "available"}><option value="available">Available now</option><option value="limited">Limited availability</option><option value="unavailable">Not available</option></select></div></div>{freshness.stale?<div className="alert" style={{marginTop:14}}><div><strong>Your availability needs confirmation.</strong><p style={{margin:"4px 0 0"}}>Recruiters will not release you to a new client shortlist after your availability becomes stale. Save any changes first, then confirm below.</p></div></div>:null}</section>

          <section className="card profile-section" id="trust"><div className="profile-section-head"><div><span>04</span><div><h2>Proof & trust</h2><p>Private evidence supports vetting; public links help clients understand your work.</p></div></div></div><div className="form-grid"><div className="field"><label>LinkedIn URL</label><input type="url" name="linkedin_url" defaultValue={va?.linkedin_url || ""} placeholder="https://linkedin.com/in/..."/></div><div className="field"><label>Portfolio URL</label><input type="url" name="portfolio_url" defaultValue={va?.portfolio_url || ""} placeholder="https://..."/></div><div className="field span-2"><label>Private resume <span className="muted">PDF/DOC/DOCX, max 5 MB</span></label><input type="file" name="resume" accept=".pdf,.doc,.docx"/><span className="field-help">Your uploaded resume is never exposed on the public profile.</span></div></div></section>

          <div className="profile-savebar"><span className="small muted">Save whenever you make meaningful changes. Some vetted evidence may require re-approval.</span><button className="btn btn-primary" type="submit">Save profile</button></div>
        </form>

        <section className="card profile-section">
          <div className="row-between wrap"><div><h2 style={{margin:"0 0 4px"}}>Confirm current availability</h2><p className="small muted" style={{margin:0}}>A quick confirmation tells recruiters that the hours, schedule, availability status, and rate saved above are still accurate.</p></div><span className={`badge ${freshness.stale?"badge-warning":"badge-success"}`}>{freshness.label}</span></div>
          <form action={confirmVaAvailabilityAction} style={{marginTop:14}}><button className="btn btn-primary" type="submit" disabled={!canConfirm}>Confirm my current availability</button></form>
          {!canConfirm?<p className="small muted" style={{marginBottom:0}}>Set Available now, weekly hours, a preferred schedule, and your current rate, then save the profile before confirming.</p>:<p className="small muted" style={{marginBottom:0}}>We will remind you periodically so recruiters never have to guess whether you are still available.</p>}
        </section>


        <section className="card profile-section" id="work-readiness">
          <div className="profile-section-head"><div><span>05</span><div><h2>Work readiness</h2><p>Record the private equipment and backup setup recruiters use to confirm you are client-ready.</p></div></div><span className={`badge ${va?.work_setup_verified_at?"badge-success":"badge-warning"}`}>{va?.work_setup_verified_at?<><CheckCircle2 size={13}/> Verified</>:workSetupComplete?"Awaiting verification":"Setup incomplete"}</span></div>
          <form action={saveVaWorkSetupAction} className="stack">
            <div className="form-grid"><div className="field"><label>Computer</label><input name="work_setup_computer" required maxLength={500} defaultValue={va?.work_setup_computer||""} placeholder="Lenovo ThinkPad E14"/></div><div className="field"><label>Operating system</label><input name="work_setup_os" required maxLength={500} defaultValue={va?.work_setup_os||""} placeholder="Windows 11 / macOS"/></div><div className="field"><label>RAM, GB</label><input name="work_setup_ram_gb" type="number" min="4" max="256" required defaultValue={va?.work_setup_ram_gb||""}/></div><div className="field"><label>Primary internet</label><input name="primary_internet" required maxLength={500} defaultValue={va?.primary_internet||""} placeholder="Fiber · provider · typical speed"/></div><div className="field"><label>Backup internet</label><input name="backup_internet" required maxLength={500} defaultValue={va?.backup_internet||""} placeholder="5G hotspot / second ISP"/></div><div className="field"><label>Backup power</label><input name="backup_power" required maxLength={500} defaultValue={va?.backup_power||""} placeholder="UPS / power station"/></div></div>
            <div className="grid-3"><label className="choice"><input type="checkbox" name="headset_ready" defaultChecked={Boolean(va?.headset_ready)}/><span><strong>Call-ready headset</strong><small>Clear microphone and audio.</small></span></label><label className="choice"><input type="checkbox" name="webcam_ready" defaultChecked={Boolean(va?.webcam_ready)}/><span><strong>Webcam ready</strong><small>Available for client meetings.</small></span></label><label className="choice"><input type="checkbox" name="quiet_workspace" defaultChecked={Boolean(va?.quiet_workspace)}/><span><strong>Quiet workspace</strong><small>Suitable for focused remote work.</small></span></label></div>
            {va?.work_setup_verified_at?<div className="alert"><strong>Changing this setup resets verification.</strong> This keeps the recruiter-ready signal accurate.</div>:null}
            <div className="row-between wrap"><span className="small muted">These setup details stay private with the recruiting team.</span><button className="btn" type="submit">Save work setup</button></div>
          </form>
        </section>

        <section className="card profile-section" id="vetting-readiness"><div className="row-between wrap"><div><h2 style={{margin:"0 0 4px"}}>Vetting & recruiter approval</h2><p className="small muted" style={{margin:0}}>Skills testing, video review, recruiter scoring, and final approval are one stage of your readiness journey.</p></div><Link className="btn" href="/workspace/va/vetting">Continue vetting</Link></div></section>
        <section className="card profile-section" id="visibility">
          <div className="profile-section-head"><div><span>06</span><div><h2>Public profile & privacy choice</h2><p>Your account and recruiter profile stay private unless you separately choose public discovery.</p></div></div></div>
          <form action={updateVaPublicProfileConsentAction} className="stack">
            <label className="visibility-toggle"><input type="checkbox" name="public_profile_consent" defaultChecked={consentGranted}/><span><strong>I agree to show my professional VA profile publicly</strong><small>VirtualAssistant.com.ph may display my first name + last initial, profile photo, headline, professional summary, specialties, skills, tools, industries, languages, years of experience, availability, schedule, hourly rate, and public-profile work signals so potential clients can evaluate me for work opportunities.</small></span></label>
            <div className="privacy-note"><ShieldCheck size={17}/><span>Email, phone, private resume, identity documents, test answers, messages, recruiter notes, and account records are not part of the public VA directory.</span></div>
            <p className="small muted">This choice is voluntary. You can withdraw it at any time and your profile will stop being eligible for the public directory. Withdrawing does not delete your account, applications, messages, or hiring history. Read the <Link className="text-link" href="/privacy" target="_blank">Privacy Notice</Link>.</p>
            {consentGranted ? <div className="success-banner">Consent active{consentDate ? ` since ${consentDate}` : ""} · notice version {va?.public_profile_consent_version || PUBLIC_PROFILE_CONSENT_VERSION}</div> : <div className="alert">No public-profile consent is currently recorded. Your profile will remain private even if a recruiter approves it.</div>}
            <div className="row-between wrap"><span className="small muted">Publication still requires approval, eligibility, and the platform visibility switch.</span><button className="btn btn-primary" type="submit">Save public profile preference</button></div>
          </form>
        </section>
      </div>

      <aside className="profile-editor-sidebar"><LiveProfileStrength formId="va-profile-form" initial={va || {}}/><div className="card profile-editor-tip"><strong>Public profile rules</strong><ul><li>Explicit public-profile consent</li><li>2+ years of experience</li><li>Approved or bench vetting stage</li><li>Available status</li><li>Public discovery enabled</li></ul></div></aside>
    </div>
  </>;
}
