import Link from "next/link";
import { Eye, ShieldCheck } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { updateVaProfileAction } from "@/app/actions/profile";
import { LiveProfileStrength } from "@/components/live-profile-strength";
import { ResumeAutoFill } from "@/components/resume-autofill";
import { VA_CATEGORIES } from "@/lib/constants";

export default async function VaProfilePage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  const params = await searchParams;
  const { user, profile } = await requireRole("va");
  const supabase = await createClient();
  const { data: va } = await supabase.from("va_profiles").select("*").eq("user_id", user.id).single();

  return <>
    {params.error ? <div className="alert" role="alert">{params.error}</div> : null}
    {params.saved ? <div className="success-banner" role="status">Profile saved successfully.</div> : null}
    <div className="page-head"><div><h1>Build your VA profile</h1><p>Keep one strong profile for matching, applications, and your public page after approval.</p></div><Link className="btn" href="/workspace/va/profile/preview" target="_blank"><Eye size={16}/> Preview profile</Link></div>
    <ResumeAutoFill formId="va-profile-form" />
    <div className="profile-editor-layout">
      <form id="va-profile-form" action={updateVaProfileAction} className="stack profile-editor-form" encType="multipart/form-data">
        <section className="card profile-section" id="basics"><div className="profile-section-head"><div><span>01</span><div><h2>Professional basics</h2><p>Make the first screen clear enough for a client to understand what you do in seconds.</p></div></div></div><div className="form-grid"><div className="field"><label>Full legal name <span className="muted">(private)</span></label><input name="full_name" defaultValue={profile.full_name || ""} required/><span className="field-help">Public pages show first name + last initial only.</span></div><div className="field"><label>Professional headline</label><input name="headline" defaultValue={va?.headline || ""} placeholder="Executive Assistant · Operations · Customer Support"/></div><div className="field span-2"><label>Professional summary</label><textarea name="bio" defaultValue={va?.bio || ""} placeholder="What work do you do best? Which clients have you supported? What outcomes can you own?"/><span className="field-help">Aim for 80–220 words focused on outcomes, not a list of tools.</span></div><div className="field span-2"><label>Profile photo <span className="muted">JPG/PNG/WEBP, max 3 MB</span></label>{profile.avatar_url ? <img src={profile.avatar_url} alt="Current profile photo" style={{width:64,height:64,borderRadius:"50%",objectFit:"cover",display:"block",marginBottom:8}}/> : null}<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" required={!profile.avatar_url}/><span className="field-help">{profile.avatar_url ? "Replace your current photo at any time." : "Required before your VA profile can be completed or published."}</span><span className="field-help">Shown next to your name on your public profile and in the talent directory.</span></div></div></section>

        <section className="card profile-section" id="expertise"><div className="profile-section-head"><div><span>02</span><div><h2>Experience & expertise</h2><p>Your specialty, skills, tools, and experience drive both matching and public-directory eligibility.</p></div></div></div><div className="form-grid"><div className="field"><label>Primary specialty</label><select name="primary_category" defaultValue={va?.primary_category || ""}><option value="">Choose a specialty</option>{VA_CATEGORIES.map((x, index) => <option key={`${String(x)}-${index}`}>{x}</option>)}</select></div><div className="field"><label>Years of professional experience</label><input type="number" min="0" max="60" name="years_experience" defaultValue={va?.years_experience ?? ""}/><span className="field-help">Public discovery requires at least 2 years.</span></div><div className="field span-2"><label>Additional specialties <span className="muted">(up to 3)</span></label><input name="categories" defaultValue={(va?.categories || []).join(", ")} placeholder="Customer Service, Ecommerce"/></div><div className="field span-2"><label>Core skills</label><input name="skills" defaultValue={(va?.skills || []).join(", ")} placeholder="Calendar management, recruitment coordination, customer support, reporting, research"/><span className="field-help">Add at least 5 specific skills. Separate them with commas.</span></div><div className="field span-2"><label>Tools & software</label><input name="tools" defaultValue={(va?.tools || []).join(", ")} placeholder="Google Workspace, HubSpot, Slack, Canva, ClickUp"/><span className="field-help">Add tools you can use without training.</span></div><div className="field"><label>Industries</label><input name="industries" defaultValue={(va?.industries || []).join(", ")} placeholder="SaaS, dental, real estate"/></div><div className="field"><label>Languages</label><input name="languages" defaultValue={(va?.languages || []).join(", ")} placeholder="English, Filipino"/></div></div></section>

        <section className="card profile-section" id="availability"><div className="profile-section-head"><div><span>03</span><div><h2>Availability & rate</h2><p>Give matching enough information to avoid jobs that do not fit your schedule or expectations.</p></div></div></div><div className="form-grid"><div className="field"><label>Hours available per week</label><input type="number" min="1" max="80" name="weekly_hours" defaultValue={va?.weekly_hours || ""}/></div><div className="field"><label>Preferred hourly rate, USD</label><input type="number" min="5" step="0.01" name="hourly_rate" defaultValue={va?.hourly_rate || ""}/></div><div className="field"><label>Preferred schedule</label><input name="schedule" defaultValue={va?.schedule || ""} placeholder="Flexible · Evening PH · US overlap"/></div><div className="field"><label>Maximum live client overlap/day</label><input type="number" min="0" max="12" name="overlap_hours" defaultValue={va?.overlap_hours ?? 4}/></div><div className="field"><label>Availability status</label><select name="availability_status" defaultValue={va?.availability_status || "available"}><option value="available">Available now</option><option value="limited">Limited availability</option><option value="unavailable">Not available</option></select></div></div></section>

        <section className="card profile-section" id="trust"><div className="profile-section-head"><div><span>04</span><div><h2>Proof & trust</h2><p>Private evidence supports vetting; public links help clients understand your work.</p></div></div></div><div className="form-grid"><div className="field"><label>LinkedIn URL</label><input type="url" name="linkedin_url" defaultValue={va?.linkedin_url || ""} placeholder="https://linkedin.com/in/..."/></div><div className="field"><label>Portfolio URL</label><input type="url" name="portfolio_url" defaultValue={va?.portfolio_url || ""} placeholder="https://..."/></div><div className="field span-2"><label>Private resume <span className="muted">PDF/DOC/DOCX, max 5 MB</span></label><input type="file" name="resume" accept=".pdf,.doc,.docx"/><span className="field-help">Your uploaded resume is never exposed on the public profile.</span></div></div></section>

        <section className="card profile-section" id="visibility"><div className="profile-section-head"><div><span>05</span><div><h2>Public discovery</h2><p>Approved profiles can appear to clients only when every eligibility condition is met.</p></div></div></div><label className="visibility-toggle"><input type="checkbox" name="directory_visible" defaultChecked={Boolean(va?.directory_visible)}/><span><strong>Allow my approved profile to appear publicly</strong><small>We automatically hide profiles that are unavailable, under 2 years of experience, or require re-review after material profile changes.</small></span></label><div className="privacy-note"><ShieldCheck size={17}/><span>Clients see your first name + last initial. Contact details, resume, test answers, and recruiter notes stay private.</span></div></section>

        <div className="profile-savebar"><span className="small muted">Save whenever you make meaningful changes. Some vetted evidence may require re-approval.</span><div className="row wrap"><Link className="btn" href="/workspace/va/vetting">Vetting status</Link><button className="btn btn-primary" type="submit">Save profile</button></div></div>
      </form>

      <aside className="profile-editor-sidebar"><LiveProfileStrength formId="va-profile-form" initial={va || {}}/><div className="card profile-editor-tip"><strong>Public profile rules</strong><ul><li>2+ years of experience</li><li>Approved or bench vetting stage</li><li>Available status</li><li>Public discovery enabled</li></ul></div></aside>
    </div>
  </>;
}
