import Link from "next/link";
import { notFound } from "next/navigation";
import { requireRole } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { reviewJobAction } from "@/app/actions/admin";
import { dateShort, money } from "@/lib/format";
import { StaffJobMatching } from "@/components/staff-job-matching";
import { uniqueStrings } from "@/lib/collections";

export default async function AdminJobReview({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const {id}=await params; const query=await searchParams; await requireRole("admin"); const admin=createAdminClient();
  const {data:j}=await admin.from("jobs").select("*").eq("id",id).single();
  if(!j) notFound();
  const [{data:settings},{data:c},{data:clientProfile},{data:clientAccount}]=await Promise.all([
    admin.from("admin_settings").select("default_placement_fee,default_managed_markup_percent").eq("id",1).single(),
    admin.from("job_commercials").select("*").eq("job_id",id).maybeSingle(),
    j.client_id ? admin.from("client_profiles").select("company_name").eq("user_id",j.client_id).maybeSingle() : Promise.resolve({data:null}),
    j.client_id ? admin.from("profiles").select("full_name").eq("id",j.client_id).maybeSingle() : Promise.resolve({data:null})
  ]);
  const awaiting=j.status==="pending"&&c?.commercial_status==="quoted";
  return <>{query.shortlist_saved?<div className="success-banner" role="status">Internal shortlist saved.</div>:null}{query.shortlist_released?<div className="success-banner" role="status">Selected VAs released to the client shortlist. Candidate identity remains protected until access is paid or comped.</div>:null}{query.shortlist_error?<div className="alert" role="alert">{query.shortlist_error}</div>:null}<div className="page-head"><div><Link className="text-link small" href="/workspace/admin/jobs">← Job review queue</Link><h1 style={{marginTop:8}}>{j.title}</h1><p>{j.company_name||clientProfile?.company_name||clientAccount?.full_name||"Client"} · submitted {dateShort(j.created_at)}</p></div><div className="row wrap"><span className={`badge ${j.status==="published"?"badge-success":j.status==="pending"?"badge-warning":""}`}>{j.status}</span><span className="badge">{j.service_model==="managed_service"?"Managed service":"Curated placement"}</span></div></div>
  <div className="profile-layout"><div className="stack">
    <section className="card"><h3>Role brief</h3><div className="score-grid"><div><span>Hours</span><strong>{j.hours_per_week?`${j.hours_per_week}/week`:"Flexible"}</strong></div><div><span>VA pay floor</span><strong>{money(j.min_hourly_rate)}/hr</strong></div><div><span>VA pay ceiling</span><strong>{j.max_hourly_rate?`${money(j.max_hourly_rate)}/hr`:"Not set"}</strong></div><div><span>Timezone</span><strong>{j.timezone||"Not set"}</strong></div><div><span>Overlap</span><strong>{j.overlap_hours!=null?`${j.overlap_hours} hrs/day`:"Not set"}</strong></div></div><h4>Summary</h4><p>{j.summary||"No summary."}</p><h4>Description</h4><p style={{whiteSpace:"pre-wrap"}}>{j.description||"No description."}</p></section>
    <section className="card"><h3>Responsibilities and requirements</h3><div className="grid-2"><div><strong className="small">Responsibilities</strong><ul>{uniqueStrings(j.responsibilities).length?uniqueStrings(j.responsibilities).map((x,index)=><li key={`${String(x)}-${index}`}>{x}</li>):<li className="muted">None specified</li>}</ul></div><div><strong className="small">Categories</strong><div className="pill-list" style={{marginTop:8}}>{uniqueStrings(j.categories).map((x,index)=><span className="badge" key={`${String(x)}-${index}`}>{x}</span>)}</div><strong className="small" style={{display:"block",marginTop:16}}>Skills</strong><div className="pill-list" style={{marginTop:8}}>{uniqueStrings(j.required_skills).map((x,index)=><span className="badge" key={`${String(x)}-${index}`}>{x}</span>)}</div><strong className="small" style={{display:"block",marginTop:16}}>Tools</strong><div className="pill-list" style={{marginTop:8}}>{uniqueStrings(j.required_tools).map((x,index)=><span className="badge" key={`${String(x)}-${index}`}>{x}</span>)}</div></div></div></section>
    <section className="card"><h3>Schedule and onboarding evidence</h3><dl className="compare-facts"><div><dt>Start timing</dt><dd>{j.start_timing||"Not set"}</dd></div><div><dt>Engagement</dt><dd>{j.engagement_length||"Not set"}</dd></div><div><dt>Schedule notes</dt><dd>{j.schedule_notes||"Not set"}</dd></div><div><dt>Live coverage exception</dt><dd>{j.live_coverage_exception?"Yes":"No"}</dd></div><div><dt>Direct feedback</dt><dd>{j.direct_feedback?"Expected":"Not selected"}</dd></div><div><dt>Onboarding plan</dt><dd>{j.onboarding_plan||"Not set"}</dd></div></dl></section>
  </div><aside className="profile-sidebar"><div className="card stack"><div><h3 style={{margin:0}}>Review and quote</h3><p className="small muted" style={{margin:"5px 0 0"}}>Confirm the role is specific, feasible, and adequately budgeted before sending the service fee to the client.</p></div>{j.status==="pending"&&!awaiting?<><form action={reviewJobAction} className="stack"><input type="hidden" name="job_id" value={j.id}/>{j.service_model==="managed_service"?<div className="field"><label>Managed-service margin %</label><input type="number" min="0.01" max="100" step="0.01" name="managed_markup_percent" defaultValue={settings?.default_managed_markup_percent??0} required/></div>:<div className="field"><label>Placement fee, USD</label><input type="number" min="0.01" step="50" name="placement_fee" defaultValue={settings?.default_placement_fee??0} required/></div>}<button className="btn btn-primary" name="decision" value="approve">Send fee for client acceptance</button></form><form action={reviewJobAction} className="stack"><input type="hidden" name="job_id" value={j.id}/><div className="field"><label>Changes needed</label><textarea name="note" required minLength={15} placeholder="Tell the client exactly what needs to change before approval."/></div><button className="btn" name="decision" value="reject">Return role for edits</button></form></>:awaiting?<div className="alert">The service fee has been sent. This role is waiting for client acceptance before publishing.</div>:<div className="info-banner">This role is {j.status}. Review actions are only available while it is pending.</div>}{c?<div className="review-answer"><strong>Current service fee</strong><p>{c.service_model==="managed_service"?`${c.managed_markup_percent||0}% managed-service margin`:`USD ${c.placement_fee||0} placement fee`}</p><span className="badge">{String(c.commercial_status).replaceAll("_"," ")}</span></div>:null}</div></aside></div><StaffJobMatching job={j} viewerRole="admin" returnTo={`/workspace/admin/jobs/${j.id}`}/></>;
}
