import { CheckCircle2, CreditCard, LockKeyhole, ShieldCheck } from "lucide-react";
import { candidateAccessLabel, candidateAccessUnlocked } from "@/lib/candidate-access";
import { requestCandidateAccessAction } from "@/app/actions/matching";

export function CandidateAccessGate({ jobId, access, applicantCount = 0, releasedCount = 0, returnTo }: { jobId: string; access: any; applicantCount?: number; releasedCount?: number; returnTo: string }) {
  if (candidateAccessUnlocked(access?.access_status)) return <div className="candidate-access-active"><ShieldCheck size={17}/><div><strong>Candidate access active</strong><span>Full permitted candidate profiles, resumes, contact details, comparison, direct messaging, and hiring actions are unlocked for this role.</span></div></div>;
  const status=access?.access_status||"locked";
  const benefits=["VA full name and permitted contact details","Private resume and richer profile evidence","Direct candidate messaging","Comparison and interview / offer / hire controls"];
  return <section className="candidate-access-gate clearer-paywall"><div className="candidate-access-gate-icon"><LockKeyhole size={22}/></div><div className="candidate-access-gate-copy"><span className="badge">{candidateAccessLabel(status)}</span><h3>Unlock VA contact details and hiring tools</h3><p>You can see how many people applied, but not who they are — we protect candidate identity until access is active for this role.</p><ol className="candidate-access-steps"><li>You request access for this role</li><li>We send you the price</li><li>Access turns on and you can contact candidates</li></ol><div className="unlock-benefits">{benefits.map(item=><span key={item}><CheckCircle2 size={14}/>{item}</span>)}</div><div className="row wrap candidate-access-counts"><span><strong>{applicantCount}</strong> applicant{applicantCount===1?"":"s"}</span><span><strong>{releasedCount}</strong> curated match{releasedCount===1?"":"es"}</span></div></div><div className="candidate-access-gate-action">{access?.access_fee!=null?<div className="candidate-access-price"><CreditCard size={16}/><span>Candidate access</span><strong>USD {Number(access.access_fee).toFixed(2)}</strong></div>:null}{status==="invoiced"?<div className="small muted"><strong>Waiting on payment.</strong> Access turns on automatically once your payment is recorded.</div>:status==="quoted"?<div className="small muted"><strong>Your price is ready.</strong> Check your email or messages to confirm, and access turns on straight after.</div>:status==="requested"?<div className="small muted"><strong>Request received.</strong> We will send you the price for this role, usually within 1 business day. Nothing has been charged.</div>:<form action={requestCandidateAccessAction}><input type="hidden" name="job_id" value={jobId}/><input type="hidden" name="return_to" value={returnTo}/><button className="btn btn-primary" type="submit">Request access and pricing</button><p className="small muted candidate-access-note">Nothing is charged now. We reply with the price for this role, and access turns on once it is settled.</p></form>}</div></section>;
}
