import { CreditCard, LockKeyhole, ShieldCheck } from "lucide-react";
import { candidateAccessLabel, candidateAccessUnlocked } from "@/lib/candidate-access";
import { requestCandidateAccessAction } from "@/app/actions/matching";

export function CandidateAccessGate({ jobId, access, applicantCount = 0, releasedCount = 0, returnTo }: { jobId: string; access: any; applicantCount?: number; releasedCount?: number; returnTo: string }) {
  if (candidateAccessUnlocked(access?.access_status)) return <div className="candidate-access-active"><ShieldCheck size={17}/><div><strong>Candidate access active</strong><span>Full permitted candidate profiles, resumes, contact details, comparison, direct messaging, and hiring actions are available for this role.</span></div></div>;
  const status=access?.access_status||"locked";
  const benefits=["Full candidate identity and permitted contact details","Private resume and richer profile evidence","Direct candidate messaging","Interview, offer, and hire controls"];
  return <section className="candidate-access-gate clearer-paywall"><div className="candidate-access-gate-icon"><LockKeyhole size={22}/></div><div className="candidate-access-gate-copy"><span className="badge">{candidateAccessLabel(status)}</span><h3>Like the shortlist? Unlock the full profiles when you are ready.</h3><p>You can review anonymized role-fit evidence first. Identity, private documents, direct contact, and hiring controls stay protected until candidate access is active.</p><ol className="candidate-access-steps"><li>Review the safe shortlist preview below</li><li>Request full candidate access only when the matches look worth pursuing</li><li>We confirm the price before anything is charged</li></ol><div className="unlock-benefits">{benefits.map(item=><span key={item}>{item}</span>)}</div><div className="row wrap candidate-access-counts"><span><strong>{applicantCount}</strong> applicant{applicantCount===1?"":"s"}</span><span><strong>{releasedCount}</strong> curated match{releasedCount===1?"":"es"}</span></div></div><div className="candidate-access-gate-action">{access?.access_fee!=null?<div className="candidate-access-price"><CreditCard size={16}/><span>Candidate access</span><strong>USD {Number(access.access_fee).toFixed(2)}</strong></div>:null}{status==="invoiced"?<div className="small muted"><strong>Access is being finalized.</strong> It turns on once payment is recorded.</div>:status==="quoted"?<div className="small muted"><strong>Your access price is ready.</strong> Review it before deciding whether to continue.</div>:status==="requested"?<div className="small muted"><strong>Your request is with the hiring team.</strong> We will confirm the price before anything is charged.</div>:<form action={requestCandidateAccessAction}><input type="hidden" name="job_id" value={jobId}/><input type="hidden" name="return_to" value={returnTo}/><button className="btn btn-primary" type="submit">Request full candidate access</button><p className="small muted candidate-access-note">No charge today. We confirm the price and next step first.</p></form>}</div></section>;
}
