import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { canonicalPath } from "@/lib/seo-url";

export const metadata: Metadata = {
  title: "Privacy Notice",
  description: "How VirtualAssistant.com.ph handles public VA profiles, private hiring data, matching, consent, retention, and privacy rights.",
  alternates: { canonical: canonicalPath("/privacy") }
};

export default function PrivacyPage() {
  return <><SiteHeader/><main id="main-content">
    <section className="section public-hero-small"><div className="container public-page-head"><h1 className="public-page-title">Privacy Notice</h1><p className="public-lede">This notice explains how VirtualAssistant.com.ph handles account, hiring, public-profile, matching, training, payment, and operational information, including the choices available to Virtual Assistants whose professional profiles may appear in the public directory.</p></div></section>
    <section className="section section-white"><div className="container stack" style={{maxWidth:820}}>
      <div className="card"><h2>Our privacy approach</h2><p className="muted">For platform data where VirtualAssistant.com.ph determines why and how personal information is processed, we apply the principles of transparency, legitimate purpose, proportionality, security, and appropriate retention. For users in the Philippines, this includes the privacy principles and data-subject rights recognized by the Data Privacy Act of 2012 (Republic Act No. 10173), its implementing rules, and applicable issuances of the National Privacy Commission.</p></div>

      <div className="card"><h2>Information we process</h2><p className="muted">Depending on how you use the platform, information may include account and contact details, professional profile information, resumes, applications, role briefs, availability and schedule, training and assessment records, recruiter/client workflow records, interview and placement information, security and audit records, payment and transaction records, and product analytics. We aim to collect only information that is relevant to the hiring, training, marketplace, security, support, and legal purposes described in this notice.</p></div>

      <div className="card"><h2>Public VA profiles require a separate choice</h2><p className="muted">Creating a VA account, completing vetting, or being approved by a recruiter does not by itself authorize public display. A VA must separately opt in to public-profile discovery. The platform records the consent state, the version of the notice/consent used, and the date of the grant or withdrawal. A VA can withdraw this choice from the VA Profile page.</p><p className="muted">Withdrawing public-profile consent makes the profile ineligible for the public VA directory and for public-profile semantic indexing. It does not delete the account, applications, interviews, workrooms, payment records, or other private hiring records that may still need to be retained for legitimate operational, contractual, security, accounting, dispute, or legal purposes.</p></div>

      <div className="card"><h2>What can appear publicly</h2><p className="muted">When a VA has opted in and also satisfies the platform&apos;s approval and eligibility rules, the public directory can show a limited professional profile. This may include first name plus last initial, profile photo, professional headline and summary, specialty, skills, tools, industries, languages, years of experience, general availability and schedule, hourly rate, verified training, and selected professional-profile signals.</p><p className="muted">Public-profile consent is only for the professional information described in the consent control. It is not permission to publish private account or hiring records.</p></div>

      <div className="card"><h2>What stays private</h2><p className="muted">Email addresses, phone numbers, home address, private resumes, identity documents, account records, assessment answers, recruiter/admin notes, private hiring records, client commercial terms, payment information, and other non-public data are not part of the public VA directory. Access is limited by role, purpose, and the relevant hiring relationship.</p></div>

      <div className="card"><h2>Matching, profiling, and AI-assisted search</h2><p className="muted">The platform uses professional profile information such as skills, tools, experience, industries, availability, schedule, rates, vetting state, and job requirements to evaluate or rank possible matches. For privacy-compliance purposes, we treat this matching activity as profiling. Matching scores and search rankings are decision-support tools, not automatic hiring or rejection decisions: recruiters review candidates before client presentation and clients make the final hiring decision.</p><p className="muted">For public-profile search, the platform may create numerical representations (embeddings) from the professional text of VAs who are already eligible for the consented public directory. Private resumes, contact details, assessment answers, recruiter notes, and non-public candidate profiles are excluded from that public-search embedding process. The relevant data-processing system is handled in accordance with applicable National Privacy Commission registration and profiling requirements.</p></div>

      <div className="card"><h2>Why we process information</h2><p className="muted">We process information to create and secure accounts, build VA and client profiles, run vetting and matching, manage role briefs and applications, support recruiter and client workflows, schedule interviews and calls, operate training and credential records, facilitate placements and workrooms, process and reconcile payments, prevent fraud and abuse, maintain audit/security records, provide support, comply with legal obligations, and understand product performance. Where consent is the basis for a specific optional feature, such as public-profile display, that consent can be withdrawn for future processing.</p></div>

      <div className="card"><h2>Service providers and international processing</h2><p className="muted">The platform uses service providers for cloud hosting, database and authentication services, email delivery, analytics, calendar/video-meeting operations, payment processing, security, and AI/embedding processing. Some providers or their infrastructure may process data outside the Philippines. VirtualAssistant.com.ph remains responsible for selecting providers appropriate to the purpose and for applying contractual, access-control, security, and data-minimization safeguards appropriate to the information being processed.</p></div>

      <div className="card"><h2>Retention and deletion</h2><p className="muted">Retention depends on the type of record and why it exists. Active account/profile records are generally kept while the account or hiring relationship remains active. Public-profile data stops being eligible for public display when consent is withdrawn. Applications, interview, placement, payment, accounting, dispute, fraud-prevention, and audit records may be retained after an account becomes inactive where they remain necessary for the transaction, contractual relationship, security investigation, accounting/tax requirement, dispute, or another legal obligation. Data that no longer has a valid purpose should be deleted, anonymized, or securely disposed of under the platform&apos;s retention schedule.</p></div>

      <div className="card"><h2>Your privacy rights</h2><p className="muted">Depending on applicable law and the circumstances, you may have rights to be informed, access personal data, request correction, object to certain processing, withdraw consent, request deletion or blocking where appropriate, and raise a privacy concern. Public-profile consent can be changed directly from the VA Profile page. For other privacy requests, use the <Link className="text-link" href="/contact">contact channel</Link> and provide enough information for us to verify the account and request safely. You may also raise a concern with the National Privacy Commission where applicable.</p></div>

      <div className="card"><h2>Security and incident handling</h2><p className="muted">Private files use controlled access, account data is protected through role-based application and database controls, and sensitive operations are performed through authenticated server-side workflows. Security controls include least-privilege access, audit records, signed/verified webhook handling, and restricted storage links for private files. Security incidents and personal data breaches are assessed and handled under the platform&apos;s incident-response process, including applicable National Privacy Commission reporting requirements.</p></div>

      <div className="card"><h2>Public-profile controls</h2><p className="muted">If you are a VA, open your <Link className="text-link" href="/workspace/va/profile#visibility">VA Profile privacy settings</Link> to grant or withdraw public-profile consent. A profile can be approved for private recruiter matching without being publicly listed.</p></div>
    </div></section>
  </main><SiteFooter/></>;
}
