import Link from "next/link";
import { CalendarClock, HeartPulse } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { deleteTimeEntryAction, logTimeAction, updateTaskStatusAction, updateTimeEntryAction } from "@/app/actions/workroom";
import { toggleOwnedChecklistAction } from "@/app/actions/workroom-checklist";
import { submitPlacementPulseAction } from "@/app/actions/agency-operations-v2";
import { money } from "@/lib/format";
import { PlacementReviewPanel } from "@/components/placement-review-panel";
import type { PlacementReview } from "@/lib/reviews";
import type { AvatarProfileRow, PlacementCheckinRow, TimeEntryRow, WorkroomChecklistRow, WorkroomRow, WorkroomTaskRow } from "@/lib/workspace-rows";

type VaWorkroom = WorkroomRow & {
  jobs: { title: string | null; company_name: string | null; hours_per_week: number | null; min_hourly_rate: number | null; timezone: string | null; overlap_hours: number | null; onboarding_plan: string | null; engagement_length: string | null } | null;
};

function timeStatus(status:string){return status==="approved"?"Approved":status==="changes_requested"?"Changes requested":"Pending review";}
function healthLabel(status:string){return status==="healthy"?"Healthy":status==="watch"?"Watch":status==="at_risk"?"At Risk":"Building";}
function healthBadge(status:string){return status==="healthy"?"badge-success":status==="at_risk"?"badge-danger":"badge-warning";}
function checkpointLabel(value:string){return value.startsWith("day")?value.replace("day","Day "):value.startsWith("month")?value.replace("month","Month "):value;}
function dateLabel(value?:string|null){if(!value)return"Not scheduled";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));}

export default async function VaWorkroomPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const params=await searchParams;
  const {user}=await requireRole("va");
  const supabase=await createClient();
  const admin=createAdminClient();
  const {data:roomData}=await supabase.from("workrooms").select("*,jobs(title,company_name,hours_per_week,min_hourly_rate,timezone,overlap_hours,onboarding_plan,engagement_length)").eq("va_id",user.id).order("created_at",{ascending:false});
  const rooms=(roomData||[]) as VaWorkroom[];
  const ids=rooms.map((r)=>r.id);const applicationIds=rooms.map((r)=>r.application_id);
  let tasks:WorkroomTaskRow[]=[];let checks:WorkroomChecklistRow[]=[];let time:TimeEntryRow[]=[];let conversations:{id:string;application_id:string|null}[]=[];let reviews:PlacementReview[]=[];let checkins:PlacementCheckinRow[]=[];let csms:AvatarProfileRow[]=[];
  if(ids.length){
    const csmIds=[...new Set(rooms.map((r)=>r.client_success_owner_id).filter(Boolean))];
    const results=await Promise.all([
      supabase.from("workroom_tasks").select("*").in("workroom_id",ids).order("created_at"),
      supabase.from("workroom_checklist").select("*").in("workroom_id",ids).order("sort_order"),
      supabase.from("time_entries").select("*").in("workroom_id",ids).order("work_date",{ascending:false}),
      supabase.from("conversations").select("id,application_id").in("application_id",applicationIds),
      supabase.from("reviews").select("*").in("workroom_id",ids),
      admin.from("placement_checkins").select("*").in("workroom_id",ids).order("due_at"),
      csmIds.length?admin.from("profiles").select("id,full_name").in("id",csmIds):Promise.resolve({data:[]})
    ]);
    tasks=results[0].data||[];checks=results[1].data||[];time=results[2].data||[];conversations=results[3].data||[];reviews=results[4].data||[];checkins=results[5].data||[];csms=results[6].data||[];
  }
  const {data:publicProfile}=await supabase.from("public_va_directory").select("user_id").eq("user_id",user.id).maybeSingle();
  const vaProfileIsPublic=Boolean(publicProfile);const conversationMap=new Map(conversations.map((c)=>[c.application_id,c.id]));const csmMap=new Map(csms.map((c)=>[c.id,c.full_name]));
  const requestedCheckin=String(params.checkin||"");

  return <>
    {params.pulse_saved?<div className="success-banner" role="status">Thanks. Your placement check-in was saved. Client Success will step in if anything needs attention.</div>:null}
    <div className="page-head"><div><div className="kicker">My Placement</div><h1>Your placement workspace</h1><p>Everything for an active placement lives here: onboarding, tasks, time, conversations, support, and Client Success check-ins.</p></div></div>
    {rooms.length?<div className="stack">{rooms.map((r)=>{
      const roomTasks=tasks.filter((t)=>t.workroom_id===r.id);const allChecks=checks.filter((c)=>c.workroom_id===r.id);const vaChecks=allChecks.filter((c)=>c.owner_role==="va");const clientChecks=allChecks.filter((c)=>c.owner_role==="client");const roomTime=time.filter((t)=>t.workroom_id===r.id);const total=roomTime.reduce((sum,t)=>sum+Number(t.hours||0),0);const approvedHours=roomTime.filter((t)=>t.status==="approved").reduce((sum,t)=>sum+Number(t.hours||0),0);const thread=conversationMap.get(r.application_id);const roomCheckins=checkins.filter((c)=>c.workroom_id===r.id);const requested=roomCheckins.find((c)=>c.id===requestedCheckin&&!c.va_signal);const next=requested||roomCheckins.find((c)=>!c.va_signal&&c.status!=="skipped");return <div className="card stack" key={r.id}>
      <div className="row-between wrap"><div><div className="row wrap"><span className={`badge ${healthBadge(r.health_status||"")}`}><HeartPulse size={13}/>{healthLabel(r.health_status||"")}{r.health_score!=null?` · ${r.health_score}`:""}</span><span className="badge">{String(r.placement_stage||"active").replaceAll("_"," ")}</span></div><h2 style={{margin:"8px 0 3px"}}>{r.jobs?.title}</h2><span className="muted">{r.jobs?.company_name||"Client"}</span></div><Link className="btn btn-primary" href={thread?`/workspace/va/messages?thread=${thread}`:"/workspace/va/messages"}>Open this conversation</Link></div>
      <section className="card hire-terms-card"><h3 style={{marginTop:0}}>Confirmed placement terms</h3><div className="grid-4"><div><span className="small muted">Agreed rate</span><strong style={{display:"block"}}>{money(r.agreed_hourly_rate||r.jobs?.min_hourly_rate)}/hr</strong></div><div><span className="small muted">Start date</span><strong style={{display:"block"}}>{r.start_date||"Not recorded"}</strong></div><div><span className="small muted">Agreed schedule</span><strong style={{display:"block"}}>{r.agreed_schedule||"Not recorded"}</strong></div><div><span className="small muted">Client Success</span><strong style={{display:"block"}}>{csmMap.get(r.client_success_owner_id||"")||"Being assigned"}</strong></div></div></section>

      {next?<form action={submitPlacementPulseAction} className="card stack"><input type="hidden" name="checkin_id" value={next.id}/><div className="row-between wrap"><div><strong>{checkpointLabel(next.checkpoint)} placement check-in</strong><p className="small muted" style={{margin:"4px 0 0"}}>How is this placement going for you?</p></div><span className="small muted"><CalendarClock size={13}/> {dateLabel(next.due_at)}</span></div><div className="row wrap"><button className="btn btn-sm btn-primary" type="submit" name="signal" value="green">Great</button><button className="btn btn-sm" type="submit" name="signal" value="yellow">Need support</button><button className="btn btn-sm btn-danger" type="submit" name="signal" value="red">Serious concern</button></div><div className="field"><label>Optional note</label><textarea name="note" maxLength={2000} placeholder="Share context if there is something Client Success should know."/></div></form>:null}

      <div className="grid-3"><div className="card"><div className="small muted">Expected hours</div><strong>{r.jobs?.hours_per_week?`${r.jobs.hours_per_week}/week`:"Flexible"}</strong></div><div className="card"><div className="small muted">Approved time</div><strong>{approvedHours.toFixed(2)} hrs</strong></div><div className="card"><div className="small muted">Total submitted</div><strong>{total.toFixed(2)} hrs</strong></div></div>
      <div className="grid-2"><section className="card"><h3>Your onboarding actions</h3><p className="small muted">Complete only the setup items assigned to you. Client-owned access and setup items stay with the client.</p><div className="checklist">{vaChecks.length?vaChecks.map((c)=><form action={toggleOwnedChecklistAction} className="check-item" key={c.id}><div className={`check-icon ${c.completed_at?"done":""}`}>{c.completed_at?"✓":""}</div><div><strong className="small">{c.title}</strong></div><input type="hidden" name="checklist_id" value={c.id}/><input type="hidden" name="done" value={c.completed_at?"1":"0"}/><button className="btn btn-sm" type="submit">{c.completed_at?"Reopen":"Complete"}</button></form>):<div className="small muted">No VA onboarding actions are waiting.</div>}</div>{clientChecks.length?<div className="info-banner" style={{marginTop:12}}><strong>Client setup: {clientChecks.filter((c)=>c.completed_at).length}/{clientChecks.length} complete</strong><p style={{margin:"5px 0 0"}}>You can see client progress, but you cannot complete client-owned items.</p></div>:null}{r.jobs?.onboarding_plan?<p className="small muted"><strong>Client plan:</strong> {r.jobs.onboarding_plan}</p>:null}</section>
        <section className="card"><h3>Log time</h3><p className="small muted">Submit completed work for client review. Approved time becomes eligible for invoicing.</p><form action={logTimeAction} className="stack"><input type="hidden" name="workroom_id" value={r.id}/><div className="form-grid"><div className="field"><label>Date</label><input type="date" name="work_date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Hours</label><input type="number" name="hours" min="0.25" max="24" step="0.25" required/></div><div className="field span-2"><label>Work note</label><textarea name="note" placeholder="What did you work on?"/></div></div><button className="btn btn-primary" type="submit">Submit time for review</button></form></section></div>
      <section className="card"><div className="row-between wrap"><h3 style={{margin:0}}>Assigned tasks</h3><span className="small muted">{roomTasks.filter((t)=>t.status==="done").length} of {roomTasks.length} done</span></div>{roomTasks.length?<div className="table-wrap responsive-table" style={{marginTop:12}}><table><thead><tr><th>Task</th><th>Due</th><th>Status</th></tr></thead><tbody>{roomTasks.map((t)=><tr key={t.id}><td data-label="Task"><strong>{t.title}</strong><div className="small muted">{t.description}</div></td><td data-label="Due">{t.due_date||"No date"}</td><td data-label="Status"><form action={updateTaskStatusAction} className="row"><input type="hidden" name="task_id" value={t.id}/><label className="sr-only" htmlFor={`va-task-${t.id}`}>Task status</label><select id={`va-task-${t.id}`} name="status" defaultValue={t.status} className="compact-select"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="review">Ready for review</option><option value="done">Done</option></select><button className="btn btn-sm" type="submit">Save</button></form></td></tr>)}</tbody></table></div>:<div className="empty">The client has not assigned tasks yet.</div>}</section>
      {roomTime.length?<section className="card"><h3>Your time entries</h3><p className="small muted">You can correct or delete an entry until the client approves it. A correction returns the entry to pending review.</p><div className="stack">{roomTime.slice(0,20).map((t)=><div className="review-answer" key={t.id}><div className="row-between wrap"><div><span className={`badge ${t.status==="approved"?"badge-success":t.status==="changes_requested"?"badge-warning":""}`}>{timeStatus(t.status)}</span>{t.client_note?<p className="small" style={{margin:"7px 0 0"}}><strong>Client note:</strong> {t.client_note}</p>:null}</div><strong>{Number(t.hours).toFixed(2)} hrs · {t.work_date}</strong></div>{t.status==="approved"?<p className="small muted">{t.note||"No work note."}</p>:<form action={updateTimeEntryAction} className="stack" style={{marginTop:12}}><input type="hidden" name="time_entry_id" value={t.id}/><div className="form-grid"><div className="field"><label>Date</label><input type="date" name="work_date" defaultValue={t.work_date} required/></div><div className="field"><label>Hours</label><input type="number" name="hours" defaultValue={Number(t.hours)} min="0.25" max="24" step="0.25" required/></div><div className="field span-2"><label>Work note</label><textarea name="note" defaultValue={t.note||""}/></div></div><div className="row wrap"><button className="btn btn-sm" type="submit">Save correction</button></div></form>}{t.status!=="approved"?<form action={deleteTimeEntryAction} style={{marginTop:8}}><input type="hidden" name="time_entry_id" value={t.id}/><button className="btn btn-sm btn-danger" type="submit">Delete entry</button></form>:null}</div>)}</div></section>:null}
      <PlacementReviewPanel workroomId={r.id} viewerRole="va" counterpartyLabel={r.jobs?.company_name||"this client"} ownReview={reviews.find((review)=>review.workroom_id===r.id&&review.reviewer_id===user.id)||null} receivedReview={reviews.find((review)=>review.workroom_id===r.id&&review.reviewer_id===r.client_id)||null} vaProfileIsPublic={vaProfileIsPublic}/>
    </div>})}</div>:<div className="card empty">Your workroom will appear after you accept the recruiter-prepared terms and the client confirms the placement.</div>}
  </>;
}
