-- Seed the first free training course as a reviewed-before-publish draft.
-- Course and lessons are intentionally not visible to learners until an admin
-- records review metadata and explicitly marks lessons/course publishable.

insert into public.training_courses (
  id, slug, title, summary, category, country_focus, estimated_minutes,
  status, content_version, created_at, updated_at
) values (
  '10000000-0000-4000-8000-000000000001',
  'virtual-assistant-foundations',
  'Virtual Assistant Foundations',
  'A practical beginner-friendly course for Filipino Virtual Assistants covering professional remote work, client communication, email and calendar operations, files and spreadsheets, task management, research, responsible AI use, and independent execution.',
  'foundation',
  null,
  375,
  'draft',
  1,
  now(),
  now()
) on conflict (slug) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('11000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', 'Starting Strong', 'Understand what VA work actually is, what clients expect, and the professional boundaries that protect both sides.', 1)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('11000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001', 'Client Communication', 'Communicate clearly, ask better questions, give useful updates, and handle mistakes without creating more work.', 2)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('11000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000001', 'Email and Calendar Operations', 'Build dependable habits for inboxes, scheduling, meetings, and follow-through.', 3)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('11000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000001', 'Files, Documents, and Spreadsheets', 'Organize information so clients can find, trust, and reuse your work.', 4)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('11000000-0000-4000-8000-000000000005', '10000000-0000-4000-8000-000000000001', 'Tasks, Time, and Handoffs', 'Prioritize work, manage deadlines, and keep work moving across time zones.', 5)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('11000000-0000-4000-8000-000000000006', '10000000-0000-4000-8000-000000000001', 'Research and AI', 'Research carefully, verify sources, and use AI as an assistant rather than a substitute for judgment.', 6)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('11000000-0000-4000-8000-000000000007', '10000000-0000-4000-8000-000000000001', 'Briefs, SOPs, and Independent Work', 'Turn instructions into reliable execution, know when to escalate, and put the whole workflow together.', 7)
on conflict (course_id, position) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000001', '11000000-0000-4000-8000-000000000001', 'what-a-virtual-assistant-actually-does', 'What a Virtual Assistant Actually Does',
  'Understand the difference between completing tasks and reliably owning work for a remote client.', '[{"type":"heading","text":"What you should understand by the end"},{"type":"list","items":["What clients usually mean when they hire a Virtual Assistant","The difference between a task, a responsibility, and an outcome","Why reliability and judgment matter as much as software knowledge","How to clarify what you own and what still belongs to the client"]},{"type":"heading","text":"A VA is not just someone who follows instructions"},{"type":"paragraph","text":"A Virtual Assistant supports a business remotely. The work can include administration, customer support, research, marketing support, bookkeeping support, e-commerce operations, scheduling, CRM updates, and many other recurring processes. The important part is not the job title. It is the responsibility you are trusted to handle."},{"type":"paragraph","text":"A beginner often thinks success means finishing whatever task appears in chat. A strong VA thinks one step further: What is the client trying to achieve? What information is missing? What could go wrong? What evidence should I leave so the client can see what happened? This does not mean making decisions you were never authorized to make. It means becoming dependable inside the boundaries of your role."},{"type":"heading","text":"Task, responsibility, and outcome"},{"type":"list","items":["Task: Send the meeting reminder.","Responsibility: Keep the client''s meetings correctly scheduled and confirmed.","Outcome: The right people attend at the right time with the information they need."]},{"type":"callout","title":"A useful rule","text":"Do not expand your authority just because you want to be helpful. Own the process you were given, document your work, and escalate decisions that belong to the client."},{"type":"scenario","title":"The vague request","text":"Your client messages: ''Can you handle tomorrow''s meeting with the supplier?'' Before doing anything, identify what ''handle'' could include, what you already know, and the minimum questions you need to ask. A good response might confirm the time zone, attendees, meeting link, agenda, whether a reminder is required, and whether you are expected to take notes."},{"type":"heading","text":"Key takeaways"},{"type":"list","items":["VA work is remote business support, not one fixed job description.","Reliable ownership means understanding the desired outcome, not only the immediate task.","Clarify authority before making decisions for a client.","Good work leaves a clear record of what was done, what changed, and what still needs attention."]}]'::jsonb, 25, 1,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000002', '11000000-0000-4000-8000-000000000001', 'professional-standards-boundaries-and-confidentiality', 'Professional Standards, Boundaries, and Confidentiality',
  'Build professional habits around access, privacy, promises, availability, and client trust.', '[{"type":"heading","text":"Professionalism is mostly predictable behavior"},{"type":"paragraph","text":"Clients do not need a VA who sounds corporate all day. They need someone who is dependable. That means showing up when expected, communicating when something changes, protecting access, avoiding careless promises, and treating private business information as private."},{"type":"heading","text":"Five standards to protect"},{"type":"list","items":["Access: only use accounts, folders, systems, and permissions you were authorized to use.","Confidentiality: do not share client data, screenshots, customer information, internal pricing, or private conversations outside the work context.","Accuracy: do not mark something complete when you have not checked it.","Availability: be clear about your working hours and do not create an expectation of 24/7 response unless that is the agreed role.","Authority: do not approve refunds, payments, contracts, pricing changes, medical advice, legal advice, or other high-impact decisions unless your role explicitly allows it."]},{"type":"heading","text":"Passwords and access"},{"type":"steps","items":["Use the client''s preferred password manager or access-sharing method when available.","Keep work accounts separate from personal accounts where practical.","Turn on multi-factor authentication when the client requires it and follow their recovery process.","Never paste passwords, API keys, recovery codes, or sensitive customer data into random tools or AI systems.","If access seems broader than necessary, ask before using it."]},{"type":"callout","title":"Confidential means confidential","text":"Removing a client''s name from a screenshot does not automatically make the material safe to share. Unique workflows, pricing, customer details, or internal problems may still identify the business."},{"type":"scenario","title":"Portfolio temptation","text":"You improved a client''s messy spreadsheet and want to show the before-and-after in your portfolio. The client never gave permission. Do not publish it. Create a fictional sample that demonstrates the same skill without exposing the client''s data or internal process."},{"type":"heading","text":"When to say no or ask first"},{"type":"list","items":["You are asked to use a customer''s private information for a purpose that was not explained.","A task looks like regulated legal, financial, tax, medical, or compliance advice rather than administration.","The client asks you to misrepresent who you are or fabricate information.","You are being asked to share credentials with someone whose identity or role is unclear.","You do not understand the consequence of an action that cannot easily be reversed."]}]'::jsonb, 30, 2,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000003', '11000000-0000-4000-8000-000000000002', 'clear-written-client-communication', 'Clear Written Client Communication',
  'Write messages that are easy to scan, specific about action, and useful across email, Slack, and project tools.', '[{"type":"heading","text":"Good communication reduces work"},{"type":"paragraph","text":"A useful client message should reduce uncertainty. The client should not have to ask what happened, what you need, or what they are supposed to do next. Clear writing is especially important in remote work because your message often replaces the quick conversation that would happen in an office."},{"type":"heading","text":"Use a simple structure"},{"type":"steps","items":["Lead with the point: what changed, what you completed, or what you need.","Add only the context needed to understand the issue.","State the next action and who owns it.","Include a deadline or timing when it matters.","Link the document, task, ticket, or source instead of making the client hunt for it."]},{"type":"heading","text":"Weak versus useful"},{"type":"paragraph","text":"Weak: ''Hi, just checking on this. Let me know.'' Useful: ''The supplier has not confirmed Friday''s delivery. I followed up at 10:15 AM Manila time and added the reply thread to the task. If they do not answer by 2 PM, should I call the number on the account or move delivery to Monday?'' The second message tells the client what happened and presents a clear decision point."},{"type":"list","items":["Use short paragraphs when the message contains several points.","Use bullets for decisions, status, or multiple questions.","Avoid fake urgency. Use ''urgent'' only when delay has a real consequence.","Do not hide a problem inside a long friendly introduction.","Match the client''s preferred tone without copying slang you are uncomfortable using."]},{"type":"callout","title":"No double greetings","text":"If you are replying in an active thread, you usually do not need to restart every message with another ''Hi [Name]''. Continue naturally unless the context has changed."},{"type":"scenario","title":"Three questions at once","text":"You need the client''s approval on a draft, confirmation of a meeting time, and access to a folder. Write one message that makes all three requests easy to answer. Use numbered questions and place the most time-sensitive item first."},{"type":"heading","text":"Before you send"},{"type":"list","items":["Can the reader understand the point in the first two lines?","Did I clearly separate facts from assumptions?","If I asked a question, is it specific enough to answer quickly?","Did I include the relevant link or reference?","Would this message still make sense if someone reads it tomorrow?"]}]'::jsonb, 30, 1,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000004', '11000000-0000-4000-8000-000000000002', 'updates-questions-mistakes-and-escalation', 'Updates, Questions, Mistakes, and Escalation',
  'Learn when to update a client, how to ask focused questions, and what to do when something goes wrong.', '[{"type":"heading","text":"Do not make the client chase you"},{"type":"paragraph","text":"One of the fastest ways to lose trust is to disappear when work is delayed or unclear. A short, useful update is better than silence. You do not need to report every tiny action. Report changes that affect timing, quality, cost, customers, access, or decisions."},{"type":"heading","text":"Ask questions after doing reasonable homework"},{"type":"steps","items":["Read the full brief, thread, SOP, and linked documents first.","Check whether the answer already exists in the task history or knowledge base.","State what you found and where you are stuck.","Ask the smallest question that unlocks the work.","If there are safe options, present them clearly instead of asking an open-ended question."]},{"type":"heading","text":"How to report a mistake"},{"type":"steps","items":["State what happened without hiding it.","Explain the immediate impact that you can confirm.","Take any safe reversible action you are authorized to take.","Tell the client what still needs a decision or approval.","Document how you will prevent the same mistake next time."]},{"type":"callout","title":"Do not invent certainty","text":"If you do not know the impact yet, say that. ''I am checking whether the message reached the full list'' is better than guessing that everything is fine."},{"type":"scenario","title":"Wrong calendar invite","text":"You invited a customer to 10:00 AM instead of 11:00 AM. The meeting is tomorrow. Draft the update you would send to the client and list the safe corrective steps you can take immediately."},{"type":"heading","text":"Escalate when"},{"type":"list","items":["A decision changes price, contract terms, payroll, refunds, or other material commitments.","There is a privacy, security, or access concern.","A customer is threatening legal action, chargeback, public escalation, or serious complaint.","Instructions conflict and you cannot resolve the conflict from existing documentation.","You are about to take an irreversible action and are not sure you have authority."]}]'::jsonb, 25, 2,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000005', '11000000-0000-4000-8000-000000000003', 'inbox-management', 'Inbox Management Without Losing Context',
  'Organize inboxes, distinguish urgent from merely new, and prepare replies without overstepping.', '[{"type":"heading","text":"The goal is not inbox zero"},{"type":"paragraph","text":"A clean inbox can be helpful, but the real goal is that important messages receive the right action at the right time. An inbox can contain only ten emails and still be badly managed if the urgent one is buried or nobody knows who owns the follow-up."},{"type":"heading","text":"A practical triage system"},{"type":"steps","items":["Identify messages that require immediate attention because of deadlines, customers, money, access, or operational impact.","Separate messages that need the client''s decision from messages you can handle under existing instructions.","Convert actionable messages into tasks or follow-ups when the client''s workflow requires it.","File newsletters, receipts, notifications, and reference material into the agreed labels or folders.","Record anything that must be revisited rather than relying on memory."]},{"type":"heading","text":"Drafting replies"},{"type":"list","items":["Use the existing thread so context stays together.","Do not promise dates, prices, refunds, or outcomes you cannot authorize.","Quote or summarize the exact request before answering a complex question.","If you draft on behalf of the client, preserve their voice and flag anything you are unsure about.","Check recipients, attachments, links, dates, and time zones before sending."]},{"type":"callout","title":"Urgent is about consequence","text":"A message is not urgent simply because it arrived recently. Urgency comes from what happens if nobody acts in time."},{"type":"scenario","title":"Monday morning inbox","text":"You open the inbox and see: a customer asking to cancel tomorrow''s appointment, a newsletter, an overdue supplier invoice notice, a meeting transcript, a request for a copy of an old receipt, and a password-reset alert the client did not request. Put them in the order you would investigate them and explain why."},{"type":"heading","text":"Useful inbox outputs"},{"type":"list","items":["A short daily list of decisions the client needs to make.","Clear labels or folders with a documented purpose.","Tasks or reminders for follow-ups that cannot be completed immediately.","Drafts that are ready for review rather than half-finished messages.","A visible record of anything unusual, sensitive, or time-critical."]}]'::jsonb, 30, 1,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000006', '11000000-0000-4000-8000-000000000003', 'calendar-and-meeting-coordination', 'Calendar and Meeting Coordination',
  'Schedule accurately across time zones, prevent avoidable conflicts, and make meetings easier to attend.', '[{"type":"heading","text":"Calendar work is risk management"},{"type":"paragraph","text":"A calendar entry looks simple, but errors can waste several people''s time. A reliable VA checks the date, time zone, duration, attendees, meeting location or link, required preparation, and whether the invitation reflects what was actually agreed."},{"type":"heading","text":"Before scheduling"},{"type":"list","items":["Confirm the client''s working hours and protected time.","Know which calendar is the source of truth.","Check the time zone for every external attendee when it is not obvious.","Confirm whether buffers are required before or after meetings.","Know which meetings the VA may schedule directly and which require approval."]},{"type":"heading","text":"Scheduling workflow"},{"type":"steps","items":["Identify the purpose and required attendees.","Find candidate times using the correct time zones.","Check conflicts, travel time, buffers, and existing holds.","Confirm the chosen time when required.","Create the event with a clear title, attendee list, location or meeting link, notes, and relevant documents.","Send or schedule reminders according to the client''s process.","Update the task or CRM so the meeting status is visible outside the calendar when needed."]},{"type":"callout","title":"Never guess a time zone","text":"If someone says ''3 PM'' and participants are in different regions, confirm the zone before booking. Daylight-saving changes make familiar offsets unreliable."},{"type":"scenario","title":"Sydney and Manila","text":"Your client is in Sydney, a candidate is in Manila, and the client asks you to book ''10 AM Thursday''. Explain what you must confirm before sending the invitation and what information should appear in the event."},{"type":"heading","text":"After the meeting"},{"type":"list","items":["Store notes or transcripts only where authorized.","Create follow-up tasks with owners and due dates.","Send agreed materials or summaries.","Update CRM or project status if the meeting changed the next step.","Do not leave action items trapped inside meeting notes."]}]'::jsonb, 30, 2,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000007', '11000000-0000-4000-8000-000000000004', 'drive-docs-and-file-organization', 'Google Drive, Docs, and File Organization',
  'Create a file system that is easy to search, permission safely, and hand over to another person.', '[{"type":"heading","text":"Organization should survive you"},{"type":"paragraph","text":"A file system is good when another person can find the correct document without asking you where you saved it. Avoid personal naming systems that make sense only in your head."},{"type":"heading","text":"A simple file structure"},{"type":"list","items":["Use folders based on stable business functions or projects, not temporary moods like ''important''.","Use consistent file names that include the subject and useful date or version information when relevant.","Avoid making many copies called FINAL, FINAL2, and FINAL-REAL.","Use links to the source document instead of downloading and re-uploading unnecessary duplicates.","Keep archive material separate from active work."]},{"type":"heading","text":"Permissions matter"},{"type":"steps","items":["Check who currently has access before changing sharing.","Use the least access required: viewer, commenter, or editor.","Do not turn a private folder public just to make sharing easier.","When someone leaves a project, follow the client''s process for removing access.","If ownership needs to move, confirm the destination account before transferring it."]},{"type":"callout","title":"Do not fix confusion by duplicating files","text":"If several versions already exist, identify the source of truth and consolidate carefully. Creating another copy usually makes the problem worse."},{"type":"scenario","title":"The messy client folder","text":"You inherit a Drive containing ''Client List.xlsx'', ''Client List NEW.xlsx'', ''Client List FINAL.xlsx'', and ''Client List use this one.xlsx''. Describe how you would determine the source of truth before renaming, moving, or deleting anything."},{"type":"heading","text":"Good document habits"},{"type":"list","items":["Use headings and clear section names in long documents.","Leave comments when a decision is needed instead of silently changing uncertain content.","Use version history when appropriate rather than creating endless copies.","Link supporting sources directly in research documents.","Before handoff, remove temporary notes that could confuse the next person."]}]'::jsonb, 30, 1,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000008', '11000000-0000-4000-8000-000000000004', 'spreadsheets-for-va-admin-work', 'Spreadsheets for Everyday VA Admin Work',
  'Use spreadsheets safely for lists, tracking, cleanup, simple formulas, and handoffs.', '[{"type":"heading","text":"A spreadsheet is a small database until it is not"},{"type":"paragraph","text":"Many businesses use Sheets or Excel for leads, content calendars, invoices, inventories, contacts, applications, or schedules. Your job is often to keep the data consistent enough that people can sort, filter, review, and trust it."},{"type":"heading","text":"Protect the structure"},{"type":"list","items":["One row should usually represent one item, person, transaction, or record.","Each column should have one clear meaning.","Do not mix dates, notes, and numbers in the same column unless the sheet was designed that way.","Do not merge cells inside working data tables because sorting and filtering become unreliable.","Avoid changing formulas, validation rules, protected ranges, or hidden tabs unless you understand their purpose."]},{"type":"heading","text":"Useful beginner skills"},{"type":"list","items":["Sort and filter without permanently scrambling related columns.","Freeze headers so column names remain visible.","Use simple SUM, COUNT, COUNTA, IF, and basic date functions when the workflow calls for them.","Use data validation for controlled choices such as status.","Remove obvious duplicates only after deciding which field or combination of fields defines a duplicate.","Keep raw imported data separate from cleaned or reporting views when possible."]},{"type":"callout","title":"Backup before destructive cleanup","text":"If you are about to delete many rows, split columns, replace values in bulk, or remove duplicates, make sure the client has version history or a recoverable copy."},{"type":"scenario","title":"Lead list cleanup","text":"A lead sheet has duplicate companies, inconsistent phone formats, blank owner fields, and status values such as ''Followup'', ''follow up'', and ''FU''. Explain the cleanup order you would use and which assumptions you would confirm before changing data."},{"type":"heading","text":"Handoff checklist"},{"type":"list","items":["Headers are understandable.","Filters are not accidentally hiding records.","Dates and currency use consistent formats.","Formulas still calculate after your edits.","Any unresolved data issues are documented.","The client knows what changed and where the source data came from."]}]'::jsonb, 30, 2,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000009', '11000000-0000-4000-8000-000000000005', 'task-management-and-prioritization', 'Task Management and Prioritization',
  'Turn requests into visible work, choose what needs attention first, and close tasks with evidence.', '[{"type":"heading","text":"A task list is not a priority system"},{"type":"paragraph","text":"Remote work can produce many simultaneous requests. The newest message is not automatically the most important. Prioritization means understanding deadline, business impact, dependency, customer effect, and the cost of delay."},{"type":"heading","text":"A simple priority check"},{"type":"list","items":["Deadline: when does this actually become late?","Impact: what happens if it is delayed or wrong?","Dependency: is another person blocked until you finish?","Reversibility: can a mistake be easily undone?","Effort: can a short task remove a larger blocker?","Authority: are you allowed to complete it or does it need approval?"]},{"type":"heading","text":"Turn vague work into a task"},{"type":"steps","items":["Write the desired outcome, not only the verb.","Add the due date and time zone when timing matters.","Attach or link the source material.","Record the owner and any approver.","Break large work into checkpoints if it cannot realistically be finished in one sitting.","Define what evidence means the task is complete."]},{"type":"callout","title":"Done should be verifiable","text":"''Updated CRM'' is weak if nobody can tell what changed. A stronger completion note says which records were updated, what source was used, and what exceptions still need review."},{"type":"scenario","title":"Competing priorities","text":"At 1 PM you have four tasks: send tomorrow''s meeting confirmation, update 60 CRM records by end of day, fix a typo on a public page, and prepare an invoice the client promised a customer by 2 PM. Put them in a reasonable order and explain what information could change your decision."},{"type":"heading","text":"Daily operating habit"},{"type":"list","items":["Start by checking deadlines, blocked work, and client messages that changed priorities.","Group similar low-risk tasks where batching saves time.","Leave room for unexpected urgent work.","Before finishing the day, update task statuses and write tomorrow''s first actions.","Do not keep critical work only in your personal memory or private notes."]}]'::jsonb, 30, 1,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000010', '11000000-0000-4000-8000-000000000005', 'time-zones-deadlines-and-handoffs', 'Time Zones, Deadlines, and Handoffs',
  'Avoid missed deadlines when clients, customers, and teammates work in different countries and schedules.', '[{"type":"heading","text":"Remote work runs on explicit time"},{"type":"paragraph","text":"Words such as today, tomorrow morning, or end of day can mean different things when people are in different countries. Good remote operators attach important deadlines to a specific date, time, and time zone."},{"type":"heading","text":"Time-zone habits"},{"type":"list","items":["Store the client''s main business time zone in your working notes.","For external meetings, confirm the attendee''s zone instead of assuming it from a phone number or company address.","Be careful around daylight-saving transitions.","When repeating a deadline, include the local zone if there is any chance of ambiguity.","Use calendar tools for conversion, but still review the result before sending."]},{"type":"heading","text":"A good handoff"},{"type":"steps","items":["State what is complete.","State what is still open.","Name the next owner.","Include the exact deadline or next checkpoint.","Link the task, thread, document, or ticket.","Call out anything risky, unusual, or waiting on approval."]},{"type":"callout","title":"Do not hand off a mystery","text":"''Please continue this tomorrow'' forces the next person to reconstruct your work. A handoff should let them resume in minutes."},{"type":"scenario","title":"End-of-shift handoff","text":"You are ending your shift in Manila while your Australian client is still working. A customer is waiting for a quote, the quote draft is complete, but the client must approve the final price. Write the handoff note."},{"type":"heading","text":"When you may miss a deadline"},{"type":"list","items":["Raise the risk before the deadline, not after.","Explain what is blocking progress.","Say what portion is already complete.","Offer the safest realistic next step.","Do not promise a new deadline unless you can actually meet it."]}]'::jsonb, 25, 2,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000011', '11000000-0000-4000-8000-000000000006', 'research-and-source-verification', 'Research and Source Verification',
  'Find useful information, distinguish strong sources from weak ones, and present research a client can trust.', '[{"type":"heading","text":"Research is not copying search results"},{"type":"paragraph","text":"A client usually needs an answer they can act on. Your job is to locate relevant information, check whether it is current and credible, identify uncertainty, and present the result in a form that supports a decision."},{"type":"heading","text":"Start with the question"},{"type":"steps","items":["Rewrite the request as a specific research question.","Identify what would count as a useful answer: price, policy, contact, comparison, requirement, evidence, or recommendation.","Decide whether freshness matters. Software features, prices, regulations, opening hours, and policies often change.","Search for primary or authoritative sources first when possible.","Cross-check important claims when the consequence of error is meaningful.","Record the source and date so someone else can verify your work."]},{"type":"heading","text":"Source strength"},{"type":"list","items":["Primary source: official company documentation, government pages, original datasets, policies, contracts, or direct statements.","Strong secondary source: reputable publications or expert resources that clearly cite evidence.","Community source: forums, social posts, or reviews that are useful for experiences and patterns but may not be factually reliable.","Search snippet or AI answer: a lead to investigate, not proof by itself."]},{"type":"callout","title":"Freshness matters","text":"A perfectly accurate 2023 answer can still be wrong for a 2026 software price, tax threshold, product feature, or regulation."},{"type":"scenario","title":"Find three suppliers","text":"A client asks for three Australian suppliers of a specific office product with delivery to Sydney. Design a small research table showing what fields you would capture, which claims need verification, and how you would distinguish price from shipping cost and delivery estimate."},{"type":"heading","text":"Presenting research"},{"type":"list","items":["Lead with the answer or shortlist.","Show the criteria you used.","Link sources directly.","Separate verified facts from your interpretation.","Call out missing or conflicting information instead of hiding it.","If you recommend an option, explain the factual reason rather than pretending uncertainty does not exist."]}]'::jsonb, 30, 1,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000012', '11000000-0000-4000-8000-000000000006', 'responsible-ai-for-va-work', 'Responsible AI for Virtual Assistant Work',
  'Use AI to speed up drafting and analysis while protecting client data and verifying anything that matters.', '[{"type":"heading","text":"AI can accelerate work, but it does not own the outcome"},{"type":"paragraph","text":"AI tools are useful for drafting, summarizing, brainstorming, classifying, transforming text, and helping you think through a process. They can also confidently invent facts, miss context, expose sensitive data if used carelessly, and produce generic work that does not match the client''s needs."},{"type":"heading","text":"Good uses"},{"type":"list","items":["Drafting a first version of a routine email from approved facts.","Turning meeting notes into a proposed task list for human review.","Brainstorming search terms for research.","Reformatting non-sensitive information into a table or checklist.","Explaining a spreadsheet formula or helping diagnose a non-sensitive error.","Creating a first-pass outline that you then verify and rewrite."]},{"type":"heading","text":"High-risk uses"},{"type":"list","items":["Uploading confidential client documents without permission.","Using AI output as the only source for legal, tax, medical, financial, compliance, pricing, or policy claims.","Sending an AI-written message without checking names, dates, promises, links, and tone.","Letting AI make a decision the client expects a person to approve.","Inventing citations, customer details, credentials, testimonials, or work history."]},{"type":"steps","items":["Remove or avoid sensitive data unless the client has approved the tool and workflow.","Give the model enough non-sensitive context to produce a useful draft.","Treat the output as untrusted until reviewed.","Verify factual claims against appropriate sources.","Rewrite generic or inaccurate sections.","Before sending, ask: Would I be comfortable taking responsibility for this if the client knew AI helped produce it?"]},{"type":"callout","title":"AI is not a source","text":"If an AI tool says a software feature exists, a government rule applies, or a price is current, verify it from the relevant source before presenting it as fact."},{"type":"scenario","title":"AI-written customer reply","text":"A customer asks whether they can receive a refund outside the normal policy. You have the policy document but no authority to approve exceptions. Explain how AI could help draft the response and which parts must still be verified or escalated before anything is sent."},{"type":"heading","text":"The standard"},{"type":"list","items":["Use AI to reduce repetitive effort, not to avoid thinking.","Protect client information.","Verify important facts.","Do not hide uncertainty.","You remain responsible for the work you submit."]}]'::jsonb, 30, 2,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '12000000-0000-4000-8000-000000000013', '11000000-0000-4000-8000-000000000007', 'reading-briefs-sops-and-working-independently', 'Reading Briefs, SOPs, and Working Independently',
  'Turn instructions into a reliable workflow, spot missing information, and know when independence becomes guessing.', '[{"type":"heading","text":"Independent does not mean unsupervised guessing"},{"type":"paragraph","text":"Clients value VAs who can move work forward without constant prompting. That independence comes from understanding instructions, checking context, following agreed rules, documenting decisions, and escalating the exceptions that fall outside those rules."},{"type":"heading","text":"How to read a brief"},{"type":"steps","items":["Identify the outcome: what should be true when the work is finished?","Identify the inputs: what files, access, data, or approvals are required?","Identify the process: is there an SOP, checklist, example, or previous task to follow?","Identify constraints: deadline, tone, budget, market, software, permissions, or quality standard.","Identify the handoff: where should the result go and who needs to know?","Identify uncertainty: what could materially change the result if you assume incorrectly?"]},{"type":"heading","text":"How to use an SOP"},{"type":"list","items":["Follow the current approved version, not an old screenshot or memory.","If reality differs from the SOP, document the exception instead of silently creating a new process.","Suggest improvements separately from the live task so experimentation does not disrupt operations.","When you discover a repeated missing step, propose an SOP update with an example.","Do not treat an SOP as permission to ignore obvious safety, privacy, or authorization concerns."]},{"type":"callout","title":"Escalate exceptions, not routine work","text":"The goal is not to ask the client to approve every small action. The goal is to understand the normal operating rules well enough that only real exceptions need attention."},{"type":"scenario","title":"Composite client brief","text":"A fictional Australian service business asks you to monitor new enquiries, create jobs in its system, schedule appointments, and send confirmations. The brief does not explain what to do when a customer requests same-day service after the schedule is full. List the normal work you can proceed with, the missing decision rule, and the exact question you would ask the client."},{"type":"heading","text":"Before you call a task complete"},{"type":"list","items":["The requested outcome is actually achieved.","Important details have been checked.","The result is saved in the agreed place.","The next person can understand what happened.","Exceptions and unresolved decisions are visible.","You did not exceed your authority to make the work look finished."]}]'::jsonb, 30, 1,
  false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_assessments (
  id, course_id, module_id, title, instructions, assessment_type, pass_score,
  position, is_published, created_at, updated_at
) values (
  '13000000-0000-4000-8000-000000000001',
  '10000000-0000-4000-8000-000000000001',
  '11000000-0000-4000-8000-000000000007',
  'Final VA Work Simulation',
  'Complete a composite client simulation covering inbox triage, calendar coordination, task prioritization, research, a client status update, and escalation decisions. This assessment should be reviewed for clarity before publication and should never use a real client brief unchanged.',
  'practical',
  null,
  1,
  false,
  now(),
  now()
) on conflict (id) do nothing;
