-- Write the existing Payroll Administration for Virtual Assistants course.
-- Keep the course draft-only until a human reviewer approves the full curriculum.

update public.training_courses
set
  summary = 'Practical payroll-administration training for Virtual Assistants covering timesheets, employee changes, payroll inputs, privacy, pre-payroll checks, approvals, exception tracking, employee queries, reporting, secure handoffs, and recurring controls without providing tax, legal, or statutory advice.',
  estimated_minutes = 300,
  status = 'draft',
  published_at = null,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '20000000-0000-4000-8000-000000000014';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Payroll administration is a controlled data and approval workflow"},{"type":"paragraph","text":"A Payroll Administration Virtual Assistant can collect approved inputs, maintain trackers, prepare pay-run files, identify missing information, document exceptions, distribute approved outputs, and support employee queries. The VA should not decide tax treatment, statutory rates, employment-law questions, disputed pay, or other professional payroll judgments unless the client has an approved procedure and qualified owner for that decision."},{"type":"heading","text":"Typical payroll cycle"},{"type":"steps","items":["Confirm the payroll calendar and cut-off.","Collect approved time, leave, starter, leaver, allowance, deduction, and reimbursement inputs.","Validate completeness and obvious anomalies.","Record unresolved exceptions.","Prepare the approved import or input file.","Route the pay run for review.","Capture approval before payment or release.","Distribute approved payslips or reports through the approved system.","Log corrections and post-payroll actions."]},{"type":"heading","text":"Roles must be explicit"},{"type":"list","items":["Data preparer","Payroll reviewer","Approver","Payment authorizer","Finance contact","HR contact","Payroll specialist or accountant","System administrator"]},{"type":"callout","title":"Country rules are not interchangeable","text":"Tax withholding, social contributions, leave, termination, payroll reporting, payslip requirements, and filing obligations differ by jurisdiction. Use the client’s approved process and qualified advice for country-specific treatment."},{"type":"scenario","title":"Client asks you to choose a tax code","text":"A new employee has submitted incomplete tax information and the client asks you to select the correct tax treatment. Explain what you can prepare, what must remain unresolved, and who should make the final decision."},{"type":"heading","text":"Key takeaway"},{"type":"paragraph","text":"Payroll support is valuable when the VA protects process integrity. Clean inputs, visible exceptions, clear approvals, and secure handoffs matter more than trying to act as the payroll professional."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000011';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Payroll data is highly sensitive"},{"type":"paragraph","text":"Payroll records can contain names, addresses, bank details, salary, tax identifiers, government numbers, leave information, deductions, benefits, and identity documents. Handle only the information needed for the assigned task and keep it inside approved systems."},{"type":"heading","text":"Minimum-necessary access"},{"type":"list","items":["Use role-based access instead of shared administrator accounts.","Do not download full payroll exports when a smaller report is sufficient.","Keep bank and identity data out of chat tools unless the client explicitly approves that channel.","Do not store payroll files in personal cloud drives or local folders outside policy.","Do not reuse passwords or share credentials.","Lock or sign out when leaving the workstation."]},{"type":"heading","text":"Secure file handling"},{"type":"steps","items":["Confirm the approved storage location.","Use a clear file name and payroll period.","Avoid unnecessary copies.","Limit sharing to required reviewers.","Remove temporary files according to policy.","Confirm the final version before sending.","Record who received the file when the client requires an audit trail."]},{"type":"callout","title":"Never verify a bank change by replying to the same suspicious message","text":"Bank-detail changes are a common fraud risk. Follow the client’s independent verification process before any protected payment information is changed."},{"type":"scenario","title":"Bank details arrive by email","text":"An employee emails new bank details minutes before payroll cut-off. Describe the secure workflow, including verification, approval, timing, and what happens if the change cannot be verified before the cut-off."},{"type":"heading","text":"Privacy incident response"},{"type":"paragraph","text":"If payroll information is sent to the wrong person, exposed publicly, or accessed by an unauthorized user, preserve the facts, stop further disclosure where possible, and escalate immediately under the client’s privacy or security incident process. Do not quietly delete evidence and assume the issue is resolved."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000012';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Timesheet preparation is about approved time, not personal judgment"},{"type":"paragraph","text":"The VA can collect timesheets, compare them with schedules, flag missing entries, check totals, and prepare approved hours for payroll. Disputed hours, overtime eligibility, penalty rates, breaks, or time classifications should be routed to the authorized manager or payroll specialist."},{"type":"heading","text":"Pre-cut-off timesheet checks"},{"type":"list","items":["Employee is active in the payroll period.","Timesheet period matches the payroll period.","Required manager approval is present.","Start and finish times are complete where required.","Total hours reconcile to the submitted detail.","Leave and worked hours do not overlap unexpectedly.","Duplicate rows are removed.","Unusual overtime or large changes are flagged.","Missing timesheets are tracked."]},{"type":"heading","text":"Cut-off workflow"},{"type":"steps","items":["Send reminders before cut-off.","Maintain a missing-input tracker.","Escalate outstanding approvals before the deadline.","Freeze the submitted batch at the agreed cut-off.","Log late changes separately.","Do not silently edit approved hours.","Route late or disputed items using the client’s exception process."]},{"type":"callout","title":"A discrepancy is not permission to correct the employee record","text":"If the schedule shows eight hours but the approved timesheet shows ten, document the mismatch and route it. The VA should not decide which record is legally or contractually correct."},{"type":"scenario","title":"Manager approval is missing","text":"Three employees submitted timesheets, but one manager has not approved them by cut-off. Build the exception entry, escalation message, and possible next steps without deciding whether the hours should be paid."},{"type":"heading","text":"Audit-friendly notes"},{"type":"paragraph","text":"When an input changes, record the original value, requested change, requester, approver, date, and final accepted value when the client process supports it. Good records make later payroll questions far easier to resolve."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000021';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Employee changes need effective dates and evidence"},{"type":"paragraph","text":"New starters, leavers, leave, pay changes, role changes, bank updates, and status changes can all affect payroll. The VA’s job is to confirm that each change has the required information and approval before it enters the pay-run preparation file."},{"type":"heading","text":"New starter checklist"},{"type":"list","items":["Full legal name and approved employee identifier","Start date","Approved pay details","Employment or worker classification recorded by the authorized team","Bank details received through the approved process","Required tax or statutory forms received","Leave or benefit setup information if applicable","Approver and source documents"]},{"type":"heading","text":"Leaver checklist"},{"type":"list","items":["Final working date","Approved termination or separation instruction","Outstanding approved hours","Approved leave treatment","Approved deductions or reimbursements","Final-pay owner","Access-removal or HR handoff where part of the client process"]},{"type":"heading","text":"Leave input checks"},{"type":"steps","items":["Confirm the leave period.","Confirm approval.","Check whether the leave overlaps time entries.","Use the approved leave category.","Do not calculate legal entitlement from memory.","Escalate negative balances or unusual treatment."]},{"type":"callout","title":"Effective date matters","text":"A pay-rate change approved today may apply from a future date or be backdated. Never assume the effective date. Record it explicitly and flag retroactive changes for review."},{"type":"scenario","title":"Backdated pay change","text":"A manager submits a pay-rate increase after payroll cut-off and says it should have applied two weeks earlier. List the information and approvals required before the change can be included in the next payroll cycle."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000022';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Pay components should be categorized from approved source material"},{"type":"paragraph","text":"Payroll can include base earnings, variable earnings, allowances, bonuses, commissions, reimbursements, deductions, and other adjustments. The same label can have different treatment depending on the client, jurisdiction, employment arrangement, and system configuration."},{"type":"heading","text":"Common input categories"},{"type":"list","items":["Base salary or regular hourly pay","Approved overtime or additional hours","Bonus or commission inputs","Allowances","Expense reimbursements","Approved deductions","Salary adjustments","Back pay","One-off corrections"]},{"type":"heading","text":"Input preparation workflow"},{"type":"steps","items":["Confirm the source document or approved request.","Confirm employee and payroll period.","Confirm amount, units, or rate source.","Confirm effective date.","Confirm approval.","Map the item to the client-approved payroll code.","Flag any item whose treatment is unclear."]},{"type":"callout","title":"Do not turn an expense into payroll treatment by guessing","text":"If the client has not defined whether an item is reimbursed, taxable, non-taxable, deductible, or handled outside payroll, route the question to the appropriate payroll, finance, HR, or tax owner."},{"type":"scenario","title":"Ambiguous allowance","text":"A manager asks you to add a “travel allowance” for one employee, but the request does not state the period, amount basis, payroll code, or treatment. Draft the clarification request and identify what must be approved."},{"type":"heading","text":"Duplicate and unusual inputs"},{"type":"paragraph","text":"Compare one-off items with prior payrolls where appropriate. Duplicate bonuses, repeated reimbursements, large deductions, or unusually high variable pay should be flagged before the pay run rather than discovered after payment."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000031';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Statutory items require awareness without pretending to provide advice"},{"type":"paragraph","text":"Payroll systems may calculate tax withholding, social insurance, retirement or pension contributions, health contributions, levies, garnishments, or other statutory items. The exact rules depend on jurisdiction and can change. A VA can support the approved process but should not invent rates or give tax, legal, or payroll advice."},{"type":"heading","text":"Safe VA responsibilities"},{"type":"list","items":["Check that required employee forms are on file.","Confirm approved system setup fields are complete.","Run client-approved validation reports.","Flag missing identifiers or unusual system warnings.","Prepare reports for the payroll specialist or accountant.","Track filing or handoff deadlines without signing professional declarations unless authorized."]},{"type":"heading","text":"Escalate when"},{"type":"list","items":["A statutory rate or threshold appears wrong.","The employee disputes withholding or contribution treatment.","A government notice arrives.","A garnishment or court-directed deduction is received.","The client asks which tax rule applies.","A filing correction may be required.","A country-specific entitlement is unclear."]},{"type":"callout","title":"Approved software settings are not a substitute for professional judgment","text":"Even when a payroll system calculates automatically, unusual results still need review by the authorized payroll or finance owner when the output conflicts with expectations or employee records."},{"type":"scenario","title":"Employee says tax is too high","text":"An employee asks you to explain why their tax withholding increased and to lower it next payroll. Write the response and escalation path without giving tax advice or changing the system setting yourself."},{"type":"heading","text":"Reference discipline"},{"type":"paragraph","text":"When country-specific instructions are documented, use the client’s current approved source, note the effective date, and avoid relying on old screenshots or remembered rates."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000032';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Pre-payroll checks catch expensive mistakes before release"},{"type":"paragraph","text":"The best payroll QA happens before payment. Exception reports should focus attention on missing approvals, unusual changes, duplicates, inactive employees, new bank details, large variances, and anything that does not match the approved input trail."},{"type":"heading","text":"Useful checks"},{"type":"list","items":["Missing timesheets","Missing manager approvals","Zero or unusually low pay","Large pay increases or decreases","Unexpected overtime","Duplicate bonuses or reimbursements","New bank-account changes","Terminated employees still receiving regular pay","New starters missing required setup","Negative net pay or other system warnings","Unexpected deductions","Late adjustments"]},{"type":"heading","text":"Variance review"},{"type":"steps","items":["Compare current and prior payroll totals when appropriate.","Identify material changes.","Trace each change back to an approved input.","Record unexplained variances.","Route exceptions to the correct owner.","Do not clear an exception simply because the total looks plausible."]},{"type":"callout","title":"Exception cleared means explained, not ignored","text":"Every material exception should have a reason, source, or approval. “Looks okay” is not an audit trail."},{"type":"scenario","title":"Payroll total jumps 18 percent","text":"The current pay run is 18 percent higher than the previous period. Build a review sequence covering headcount changes, bonuses, overtime, corrections, new starters, terminations, and one-off payments before escalating any unexplained balance."},{"type":"heading","text":"Exception log fields"},{"type":"list","items":["Employee or item","Issue","Amount or variance","Source","Owner","Status","Resolution","Approval","Date resolved"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000041';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Approval separates preparation from authorization"},{"type":"paragraph","text":"A VA may prepare the payroll file and supporting reports, but payment authorization and final release should follow the client’s approval matrix. Separation of duties reduces fraud and accidental payment risk."},{"type":"heading","text":"Before approval"},{"type":"steps","items":["Complete input checks.","Resolve or document exceptions.","Generate the approved review reports.","Confirm payroll period and pay date.","Confirm the reviewer sees the final version.","Record approval in the accepted channel."]},{"type":"heading","text":"Payment controls"},{"type":"list","items":["Do not change bank details outside the verified process.","Do not approve your own prepared payment file unless the client has explicitly designed that control and you are authorized.","Do not bypass a second approver because the deadline is close.","Do not send payment files to unverified recipients.","Do not reuse an old approval for a changed payroll file."]},{"type":"callout","title":"A changed payroll file needs renewed approval","text":"If any employee, amount, bank record, deduction, or payroll total changes after approval, the approved version no longer matches the file. Follow the client’s reapproval process."},{"type":"heading","text":"Payslip administration"},{"type":"paragraph","text":"Distribute payslips only through approved secure channels. Check that each employee can access only their own document. Do not email a batch of payslips as open attachments unless that is explicitly permitted by the client’s secure process."},{"type":"scenario","title":"Last-minute change after approval","text":"A manager asks you to add a large bonus after the payroll reviewer already approved the batch. Explain the correct sequence from change request through revised report, approval, and payment release."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000042';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Payroll queries need evidence, privacy, and ownership"},{"type":"paragraph","text":"Employees may ask about missing hours, unexpected deductions, leave, bank changes, tax, benefits, bonuses, or payslip differences. The VA should acknowledge the issue, collect enough detail to investigate, protect privacy, and route decisions that exceed the VA’s authority."},{"type":"heading","text":"Query workflow"},{"type":"steps","items":["Verify the employee using the client-approved method.","Identify the payroll period and specific issue.","Review approved records and system output.","State what the records show.","Avoid guessing why a statutory or policy treatment occurred.","Escalate the decision owner when needed.","Track the correction or response to closure."]},{"type":"heading","text":"Correction control"},{"type":"list","items":["Original value","Corrected value","Reason","Source evidence","Approver","Effective payroll period","Whether off-cycle payment is authorized","Whether downstream reporting must also be corrected"]},{"type":"callout","title":"Do not promise an off-cycle payment","text":"If an employee is underpaid, acknowledge the issue and escalate urgently, but do not promise payment timing or method unless the authorized payroll owner has confirmed it."},{"type":"scenario","title":"Employee says four hours are missing","text":"The payslip shows four fewer hours than the employee expected. Their timesheet was approved as submitted. Write the investigation path, employee response, and escalation note without altering the payroll record yourself."},{"type":"heading","text":"Sensitive disputes"},{"type":"paragraph","text":"Threats of legal action, discrimination claims, termination disputes, garnishments, or serious payroll complaints should be escalated quickly to the client’s HR, payroll, legal, or management owner according to policy."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000051';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Post-payroll reporting creates a clean handoff to finance and payroll specialists"},{"type":"paragraph","text":"After payroll is approved, the VA may prepare payroll summaries, variance notes, cost-center reports, leave reports, payment confirmations, and exception logs. The output should tie back to the approved payroll period and final pay run."},{"type":"heading","text":"Useful handoff pack"},{"type":"list","items":["Final payroll summary","Payment total or approved payment reference","Department or cost-center breakdown if used","One-off payment summary","Exception and correction log","New starter and leaver list","Outstanding employee queries","Reports required by finance or the payroll specialist","Next-cycle follow-up items"]},{"type":"heading","text":"Reconciliation support"},{"type":"steps","items":["Confirm the report period.","Confirm the report comes from the final approved pay run.","Compare payroll totals with the authorized payment total where the process requires it.","Identify unexplained differences.","Record timing differences separately.","Route accounting treatment questions to finance."]},{"type":"callout","title":"Reconciliation support is not accounting sign-off","text":"A VA can compare reports and identify differences. Final ledger treatment, statutory reporting, and financial sign-off belong to the authorized finance or payroll owner."},{"type":"scenario","title":"Payroll report and bank total differ","text":"The payroll summary is higher than the payment total by the amount of one employee’s pay. Build the investigation steps and explain when the issue becomes a payroll, payment, or finance escalation."},{"type":"heading","text":"Close the cycle"},{"type":"paragraph","text":"Archive the approved reports, record unresolved items, update the next payroll checklist, and make sure temporary working files are removed or retained according to the client’s policy."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000052';

update public.training_lessons
set
  content = '[{"type":"heading","text":"A payroll calendar prevents deadline surprises"},{"type":"paragraph","text":"Payroll is recurring, but each cycle has dependencies. A clear calendar shows when inputs are due, when managers must approve, when payroll is reviewed, when payment is authorized, when employees are paid, and when follow-up or statutory handoffs occur."},{"type":"heading","text":"Calendar fields"},{"type":"list","items":["Payroll period","Timesheet cut-off","Leave and change cut-off","Manager approval deadline","Payroll preparation date","Review date","Final approval date","Payment authorization date","Pay date","Reporting or statutory handoff date","Owner for each step"]},{"type":"heading","text":"Recurring control checklist"},{"type":"steps","items":["Open the cycle and copy only current approved templates.","Confirm active employee list.","Send input reminders.","Track exceptions daily near cut-off.","Freeze the input batch at the agreed point.","Run pre-payroll checks.","Capture approvals.","Close post-payroll queries and reports.","Carry unresolved items to the next cycle."]},{"type":"callout","title":"Recurring does not mean automatic approval","text":"Every cycle still needs its own input validation and approval. Last month’s clean payroll does not prove this month’s payroll is correct."},{"type":"scenario","title":"Holiday shortens the payroll week","text":"A public holiday means the bank processing deadline is earlier than usual. Update the payroll calendar, reminder plan, approval timing, and risk notes without changing statutory rules or payment terms yourself."},{"type":"heading","text":"Continuity planning"},{"type":"paragraph","text":"Document backup owners, approved emergency contacts, and where the latest payroll checklist is stored. Avoid a process that depends on one person remembering every deadline."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000061';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Final composite payroll-administration simulation"},{"type":"paragraph","text":"This simulation tests payroll operations judgment, privacy, exception handling, approvals, and secure handoff. The fictional company is built from common payroll workflows and does not assume one country’s tax or employment rules."},{"type":"scenario","title":"Harbor & Field Services","text":"Harbor & Field Services has 42 employees paid every two weeks. One manager has not approved three timesheets. A new starter is missing a required tax form. One employee submitted new bank details by email. Another employee has a backdated pay increase awaiting approval. The payroll variance report shows an 11 percent increase, mainly from overtime and a one-off bonus. After draft payroll, one employee reports four missing hours. The client’s payroll specialist owns statutory treatment and final payroll approval."},{"type":"heading","text":"Part 1: Input control"},{"type":"steps","items":["Create the missing-input and exception list.","Separate items that can proceed from items that must pause.","Define the verification step for the bank change.","Document the backdated pay-change information still required.","Escalate the missing tax form appropriately."]},{"type":"heading","text":"Part 2: Pre-payroll QA"},{"type":"list","items":["Explain the 11 percent variance using approved inputs where possible.","Check the overtime and one-off bonus against source approvals.","Identify unresolved items.","Prepare the reviewer handoff.","State what you are not authorized to decide."]},{"type":"heading","text":"Part 3: Approval and payment"},{"type":"steps","items":["Describe the approval sequence.","Explain what would require reapproval.","Protect the payment file and payslips.","Record the final approved version."]},{"type":"heading","text":"Part 4: Employee query and correction"},{"type":"list","items":["Investigate the four missing hours.","Draft the employee response.","Create the correction record.","Route any off-cycle decision to the authorized owner."]},{"type":"heading","text":"Part 5: Closeout"},{"type":"steps","items":["Prepare the finance and payroll-specialist handoff pack.","List unresolved items for the next cycle.","Update the payroll calendar.","Archive or remove working files according to policy."]},{"type":"callout","title":"Assessment standard","text":"A strong answer protects employee data, preserves separation of duties, documents exceptions, refuses to invent statutory treatment, and leaves a complete evidence trail for the authorized payroll owner."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000014-0000-4000-8000-000000000062';

update public.training_assessments
set
  instructions = 'Complete the Harbor & Field Services composite payroll-administration simulation. Prepare the payroll input and exception controls, handle missing approvals and sensitive data safely, investigate variances and a missing-hours query, define the approval and correction workflow, and produce a finance/payroll-specialist handoff. Do not provide tax, legal, employment-law, or statutory advice, and do not authorize payments outside the approved role.',
  is_published = false,
  updated_at = now()
where id = '23000000-0000-4000-8000-000000000014';
