-- Upgrade VirtualAssistant.com.ph v3.0.x to v3.1.0.
-- Run once in Supabase SQL editor or through Supabase migrations.

alter table public.jobs add column if not exists service_model text not null default 'curated_placement';
do $$ begin
  alter table public.jobs add constraint jobs_service_model_check check (service_model in ('curated_placement','managed_service'));
exception when duplicate_object then null; end $$;

alter table public.admin_settings add column if not exists default_placement_fee numeric(10,2) not null default 0;
alter table public.admin_settings add column if not exists default_managed_markup_percent numeric(5,2) not null default 0;

create table if not exists public.focus_verticals (
  id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null unique, description text,
  active boolean not null default true, bench_target integer not null default 5 check (bench_target between 1 and 25),
  sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into public.focus_verticals (slug,name,description,bench_target,sort_order) values
 ('healthcare-dental','Healthcare & Dental','Front desk, scheduling, insurance support, billing coordination, and patient communication.',5,1),
 ('home-local-services','Home & Local Services','Moving, security, trades, dispatch, reception, customer support, and appointment coordination.',5,2),
 ('professional-growth','Professional Services & Growth','Executive support, lead generation, sales operations, marketing support, and client service.',5,3)
on conflict (slug) do nothing;

create table if not exists public.skills_tests (
  id uuid primary key default gen_random_uuid(), category text not null unique, title text not null, instructions text,
  duration_minutes integer not null default 20 check (duration_minutes between 5 and 90), passing_score integer not null default 70 check (passing_score between 1 and 100),
  questions jsonb not null default '[]'::jsonb, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.va_test_attempts (
  id uuid primary key default gen_random_uuid(), test_id uuid not null references public.skills_tests(id) on delete restrict,
  va_id uuid not null references public.profiles(id) on delete cascade, answers jsonb not null default '{}'::jsonb,
  auto_score integer check (auto_score is null or auto_score between 0 and 100), reviewer_score integer check (reviewer_score is null or reviewer_score between 0 and 100),
  final_score integer check (final_score is null or final_score between 0 and 100), reviewer_id uuid references public.profiles(id) on delete set null,
  review_notes text, submitted_at timestamptz not null default now(), reviewed_at timestamptz, unique(test_id, va_id)
);
create table if not exists public.va_vetting (
  va_id uuid primary key references public.profiles(id) on delete cascade,
  stage text not null default 'profile' check (stage in ('profile','test','video','recruiter_review','finalist','approved','bench','rejected')),
  recruiter_id uuid references public.profiles(id) on delete set null, video_url text, video_submitted_at timestamptz,
  recruiter_notes text, admin_notes text, approved_at timestamptz, rejected_at timestamptz, updated_at timestamptz not null default now()
);
insert into public.va_vetting (va_id)
select id from public.profiles where role='va'
on conflict (va_id) do nothing;

alter table public.va_vetting add column if not exists recruiter_interview_at timestamptz;

create table if not exists public.vetting_scorecards (
  id uuid primary key default gen_random_uuid(), va_id uuid not null references public.profiles(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id) on delete restrict,
  role_skills smallint not null check (role_skills between 1 and 5), communication smallint not null check (communication between 1 and 5),
  judgment smallint not null check (judgment between 1 and 5), reliability smallint not null check (reliability between 1 and 5),
  client_readiness smallint not null check (client_readiness between 1 and 5), total_score integer not null check (total_score between 20 and 100),
  recommendation text not null check (recommendation in ('reject','hold','finalist')), notes text, created_at timestamptz not null default now()
);
create table if not exists public.bench_memberships (
  id uuid primary key default gen_random_uuid(), va_id uuid not null references public.profiles(id) on delete cascade,
  category text not null, status text not null default 'active' check (status in ('active','paused')),
  priority integer not null default 3 check (priority between 1 and 5), notes text, created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(va_id,category)
);
create table if not exists public.job_commercials (
  job_id uuid primary key references public.jobs(id) on delete cascade,
  service_model text not null default 'curated_placement' check (service_model in ('curated_placement','managed_service')),
  placement_fee numeric(10,2), managed_markup_percent numeric(5,2),
  commercial_status text not null default 'not_quoted' check (commercial_status in ('not_quoted','quoted','accepted','invoiced','paid')),
  notes text, updated_at timestamptz not null default now()
);

alter table public.focus_verticals enable row level security;
drop policy if exists "profiles own update" on public.profiles;

alter table public.skills_tests enable row level security;
alter table public.va_test_attempts enable row level security;
alter table public.va_vetting enable row level security;
alter table public.vetting_scorecards enable row level security;
alter table public.bench_memberships enable row level security;
alter table public.job_commercials enable row level security;

drop policy if exists "va vetting own read" on public.va_vetting;
create policy "va vetting own read" on public.va_vetting for select using (auth.uid() = va_id);
drop policy if exists "va test own read" on public.va_test_attempts;
create policy "va test own read" on public.va_test_attempts for select using (auth.uid() = va_id);
drop policy if exists "focus verticals public read" on public.focus_verticals;
create policy "focus verticals public read" on public.focus_verticals for select using (active = true);
drop policy if exists "client commercials read" on public.job_commercials;
create policy "client commercials read" on public.job_commercials for select using (exists (select 1 from public.jobs j where j.id=job_id and j.client_id=auth.uid()));

create or replace view public.public_va_directory as
select v.user_id,v.slug,p.full_name,p.avatar_url,v.headline,v.bio,v.primary_category,v.categories,v.skills,v.tools,v.industries,v.languages,
       v.years_experience,v.weekly_hours,v.schedule,v.overlap_hours,v.portfolio_url,v.linkedin_url,v.availability_status
from public.va_profiles v
join public.profiles p on p.id=v.user_id
join public.va_vetting vv on vv.va_id=v.user_id
where v.directory_visible=true and v.availability_status='available' and vv.stage in ('approved','bench');
revoke all on public.public_va_directory from anon;
grant select on public.public_va_directory to anon, authenticated;

-- Keep future VA signups synchronized with the vetting workflow.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  requested_role public.user_role;
begin
  requested_role := case
    when new.raw_user_meta_data->>'role' = 'client' then 'client'::public.user_role
    else 'va'::public.user_role
  end;
  insert into public.profiles (id, role, full_name)
  values (new.id, requested_role, nullif(new.raw_user_meta_data->>'full_name', ''));
  if requested_role = 'client' then
    insert into public.client_profiles (user_id) values (new.id);
  elsif requested_role = 'va' then
    insert into public.va_profiles (user_id, slug) values (new.id, concat('va-', substr(new.id::text, 1, 8)));
    insert into public.va_vetting (va_id) values (new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists focus_verticals_touch on public.focus_verticals;
create trigger focus_verticals_touch before update on public.focus_verticals for each row execute procedure public.touch_updated_at();
drop trigger if exists skills_tests_touch on public.skills_tests;
create trigger skills_tests_touch before update on public.skills_tests for each row execute procedure public.touch_updated_at();
drop trigger if exists va_vetting_touch on public.va_vetting;
create trigger va_vetting_touch before update on public.va_vetting for each row execute procedure public.touch_updated_at();
drop trigger if exists bench_memberships_touch on public.bench_memberships;
create trigger bench_memberships_touch before update on public.bench_memberships for each row execute procedure public.touch_updated_at();
drop trigger if exists job_commercials_touch on public.job_commercials;
create trigger job_commercials_touch before update on public.job_commercials for each row execute procedure public.touch_updated_at();

-- Starter category skills tests. Customize questions in the recruiter/admin workflow as your standards mature.
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Administrative Support','Administrative Support practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "A client has two overlapping meetings. What should you do first?", "options": ["Cancel both meetings", "Check priority, constraints, and rescheduling options", "Move one without telling anyone", "Wait until the client notices"], "correct": "Check priority, constraints, and rescheduling options"}, {"id": "q2", "type": "choice", "prompt": "Which practice is best for shared task tracking?", "options": ["Keep tasks in private notes", "Use one agreed system with owners and due dates", "Send daily screenshots only", "Rely on memory"], "correct": "Use one agreed system with owners and due dates"}, {"id": "q3", "type": "choice", "prompt": "A confidential file is sent to the wrong recipient. What is the best immediate action?", "options": ["Ignore it", "Notify the client and follow the security escalation process", "Delete your own copy only", "Post about it in the team chat"], "correct": "Notify the client and follow the security escalation process"}, {"id": "q4", "type": "choice", "prompt": "Which calendar detail is most important when scheduling across regions?", "options": ["Font color", "Time zone", "Meeting title length", "Browser choice"], "correct": "Time zone"}, {"id": "q5", "type": "text", "prompt": "Write a short plan for organizing an executive''s inbox with 200 unread messages."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Bookkeeping & Finance','Bookkeeping & Finance practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "What is the safest response when a transaction has no supporting receipt?", "options": ["Guess the category", "Flag it for clarification and keep an audit trail", "Delete it", "Create a receipt yourself"], "correct": "Flag it for clarification and keep an audit trail"}, {"id": "q2", "type": "choice", "prompt": "Bank reconciliation is primarily used to do what?", "options": ["Write marketing copy", "Compare accounting records with bank activity", "Schedule meetings", "Estimate website traffic"], "correct": "Compare accounting records with bank activity"}, {"id": "q3", "type": "choice", "prompt": "Which item should never be changed without authorization?", "options": ["A spreadsheet column width", "A posted financial transaction affecting prior reports", "A task label", "A calendar color"], "correct": "A posted financial transaction affecting prior reports"}, {"id": "q4", "type": "choice", "prompt": "A client asks you to pay an unfamiliar vendor from an emailed bank account change. What should you do?", "options": ["Pay immediately", "Verify the change through an approved independent channel", "Reply asking if it is real and then pay", "Ignore all vendor emails forever"], "correct": "Verify the change through an approved independent channel"}, {"id": "q5", "type": "text", "prompt": "Describe how you would prepare a weekly accounts receivable follow-up report."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Customer Service','Customer Service practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "An angry customer reports the same issue for the third time. What is the best first response?", "options": ["Tell them to calm down", "Acknowledge the history, confirm the issue, and take ownership of the next step", "Close the ticket", "Send a generic FAQ"], "correct": "Acknowledge the history, confirm the issue, and take ownership of the next step"}, {"id": "q2", "type": "choice", "prompt": "What should a useful support note include?", "options": ["Only the customer''s name", "Issue, actions taken, outcome, and next step", "A personal opinion about the customer", "No details"], "correct": "Issue, actions taken, outcome, and next step"}, {"id": "q3", "type": "choice", "prompt": "When should a support issue be escalated?", "options": ["Whenever the queue is busy", "When it meets an agreed risk, authority, or complexity threshold", "Never", "Only after the customer asks ten times"], "correct": "When it meets an agreed risk, authority, or complexity threshold"}, {"id": "q4", "type": "choice", "prompt": "Which metric best reflects whether issues are being resolved rather than only answered?", "options": ["Resolution rate", "Number of emojis used", "Browser tabs open", "Email signature length"], "correct": "Resolution rate"}, {"id": "q5", "type": "text", "prompt": "Write a concise response to a customer whose appointment was missed because of a scheduling error."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Dental & Healthcare','Dental & Healthcare practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "A patient asks for clinical advice that is outside your role. What should you do?", "options": ["Give your best guess", "Route the question to the licensed clinical team using the approved process", "Search social media", "Ignore the patient"], "correct": "Route the question to the licensed clinical team using the approved process"}, {"id": "q2", "type": "choice", "prompt": "What is most important when handling patient information?", "options": ["Convenience", "Privacy and the client''s approved compliance process", "Speed at any cost", "Using personal messaging apps"], "correct": "Privacy and the client''s approved compliance process"}, {"id": "q3", "type": "choice", "prompt": "A patient wants to reschedule. What should you confirm before finalizing?", "options": ["Only their first name", "Identity, appointment details, availability, and office rules", "Their social media profile", "Nothing"], "correct": "Identity, appointment details, availability, and office rules"}, {"id": "q4", "type": "choice", "prompt": "A claim status is unclear. What is the best next step?", "options": ["Promise it will be paid", "Document the status and follow the payer or office verification workflow", "Delete the claim", "Charge the patient immediately without checking"], "correct": "Document the status and follow the payer or office verification workflow"}, {"id": "q5", "type": "text", "prompt": "Describe how you would handle a busy morning with ringing phones, check-in messages, and insurance follow-ups."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Ecommerce','Ecommerce practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "An order is marked delivered but the customer says it is missing. What should you do first?", "options": ["Accuse the customer", "Follow the store''s missing-delivery verification workflow", "Refund every order automatically", "Ignore the message"], "correct": "Follow the store''s missing-delivery verification workflow"}, {"id": "q2", "type": "choice", "prompt": "What is the safest way to update product inventory?", "options": ["Use the approved source of truth and document changes", "Guess quantities", "Copy a competitor", "Disable all products"], "correct": "Use the approved source of truth and document changes"}, {"id": "q3", "type": "choice", "prompt": "A product page has many views but few purchases. Which information is useful to review?", "options": ["Conversion rate, price, offer, reviews, and page clarity", "The VA''s wallpaper", "Only the number of staff", "Nothing"], "correct": "Conversion rate, price, offer, reviews, and page clarity"}, {"id": "q4", "type": "choice", "prompt": "What should happen before issuing a refund?", "options": ["Check the store''s refund policy and order history", "Always refund immediately", "Ask another customer", "Delete the order"], "correct": "Check the store''s refund policy and order history"}, {"id": "q5", "type": "text", "prompt": "Write a short process for handling a customer request to exchange the wrong product size."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Executive Assistance','Executive Assistance practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "A CEO receives an urgent request from a major client during a blocked focus period. What should you do?", "options": ["Interrupt without context", "Assess urgency against agreed rules and surface a concise recommendation", "Ignore all urgent requests", "Forward every email"], "correct": "Assess urgency against agreed rules and surface a concise recommendation"}, {"id": "q2", "type": "choice", "prompt": "What makes an executive briefing useful?", "options": ["It is as long as possible", "It highlights decisions, risks, context, and next actions", "It includes every email verbatim", "It avoids deadlines"], "correct": "It highlights decisions, risks, context, and next actions"}, {"id": "q3", "type": "choice", "prompt": "When managing an executive inbox, what is the best default?", "options": ["Delete everything older than one day", "Use agreed triage rules and preserve accountability", "Reply as the executive without permission", "Move all messages to spam"], "correct": "Use agreed triage rules and preserve accountability"}, {"id": "q4", "type": "choice", "prompt": "What should meeting preparation include?", "options": ["Objective, attendees, context, materials, and decisions needed", "Only a Zoom link", "A random agenda", "No preparation"], "correct": "Objective, attendees, context, materials, and decisions needed"}, {"id": "q5", "type": "text", "prompt": "Draft a five-bullet daily executive briefing structure."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Lead Generation & Sales','Lead Generation & Sales practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "What makes a prospect list qualified?", "options": ["It is very large", "It matches agreed ICP criteria and has verifiable contact data", "It contains any email found online", "It includes only personal friends"], "correct": "It matches agreed ICP criteria and has verifiable contact data"}, {"id": "q2", "type": "choice", "prompt": "What should happen after a discovery call is booked?", "options": ["Nothing", "Update the CRM with source, context, owner, and next step", "Delete the lead", "Send the same message ten times"], "correct": "Update the CRM with source, context, owner, and next step"}, {"id": "q3", "type": "choice", "prompt": "A prospect asks to stop receiving outreach. What should you do?", "options": ["Keep sending", "Record the opt-out and follow the client''s compliance process", "Change the subject line and continue", "Use another account"], "correct": "Record the opt-out and follow the client''s compliance process"}, {"id": "q4", "type": "choice", "prompt": "Which metric is more useful than raw lead volume?", "options": ["Qualified meetings or opportunities created", "Number of spreadsheet rows", "Number of browser tabs", "Length of email signature"], "correct": "Qualified meetings or opportunities created"}, {"id": "q5", "type": "text", "prompt": "Write a short plan for building and validating a list of 100 qualified prospects for a B2B service company."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Marketing & Social Media','Marketing & Social Media practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "What should a content calendar include?", "options": ["Only captions", "Channel, publish date, asset, copy, owner, status, and goal", "Only hashtags", "Only design files"], "correct": "Channel, publish date, asset, copy, owner, status, and goal"}, {"id": "q2", "type": "choice", "prompt": "A post performs poorly. What is the best next step?", "options": ["Delete the account", "Review the hook, format, audience, timing, and comparable posts", "Post the same thing every hour", "Blame the audience"], "correct": "Review the hook, format, audience, timing, and comparable posts"}, {"id": "q3", "type": "choice", "prompt": "Which metric is most useful depends primarily on what?", "options": ["The business goal", "The VA''s favorite platform", "The logo color", "The time of day only"], "correct": "The business goal"}, {"id": "q4", "type": "choice", "prompt": "How should comments that need client judgment be handled?", "options": ["Invent a policy", "Escalate using an agreed response matrix", "Delete all comments", "Ignore them"], "correct": "Escalate using an agreed response matrix"}, {"id": "q5", "type": "text", "prompt": "Create a simple weekly reporting outline for a client using Instagram, Facebook, and LinkedIn."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Phone & Reception','Phone & Reception practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "A caller asks for information you are not authorized to share. What should you do?", "options": ["Share it to be helpful", "Explain the limit and route the request appropriately", "Guess", "Hang up immediately"], "correct": "Explain the limit and route the request appropriately"}, {"id": "q2", "type": "choice", "prompt": "What should a useful call note include?", "options": ["Caller, reason, key details, action, and follow-up", "Only the phone number", "A personal judgment", "Nothing"], "correct": "Caller, reason, key details, action, and follow-up"}, {"id": "q3", "type": "choice", "prompt": "For outbound service calls, what should guide the script?", "options": ["Approved offer, audience, disclosure, and objection handling", "Anything that gets a sale", "A competitor''s script copied word for word", "No script or process"], "correct": "Approved offer, audience, disclosure, and objection handling"}, {"id": "q4", "type": "choice", "prompt": "If a caller is upset, what is the best approach?", "options": ["Match their tone", "Stay calm, acknowledge the concern, clarify the need, and follow escalation rules", "Put them on hold indefinitely", "Argue"], "correct": "Stay calm, acknowledge the concern, clarify the need, and follow escalation rules"}, {"id": "q5", "type": "text", "prompt": "Write a short outbound call opening for offering a business service without sounding pushy."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Real Estate','Real Estate practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "A new inquiry asks about a listing. What should be recorded in the CRM?", "options": ["Contact details, source, property interest, timeline, and next action", "Only the first name", "Nothing until they buy", "Personal opinions"], "correct": "Contact details, source, property interest, timeline, and next action"}, {"id": "q2", "type": "choice", "prompt": "What should a VA avoid when working with regulated real estate activities?", "options": ["Following the client''s approved process", "Performing licensed activities they are not authorized to perform", "Documenting lead status", "Scheduling appointments"], "correct": "Performing licensed activities they are not authorized to perform"}, {"id": "q3", "type": "choice", "prompt": "A lead misses an appointment. What is the best next step?", "options": ["Mark them dead forever", "Follow the agreed no-show follow-up sequence and update the CRM", "Call every five minutes", "Delete the record"], "correct": "Follow the agreed no-show follow-up sequence and update the CRM"}, {"id": "q4", "type": "choice", "prompt": "Which report helps an agent understand pipeline health?", "options": ["Leads by stage, source, conversion, and aging", "Favorite property colors", "Number of browser tabs", "Email font size"], "correct": "Leads by stage, source, conversion, and aging"}, {"id": "q5", "type": "text", "prompt": "Outline a follow-up workflow for a new buyer lead from first inquiry to booked call."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('SEO','SEO practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "What is the best first step before changing a page for SEO?", "options": ["Add the keyword everywhere", "Understand search intent, current performance, and the page''s purpose", "Delete the page", "Buy random backlinks"], "correct": "Understand search intent, current performance, and the page''s purpose"}, {"id": "q2", "type": "choice", "prompt": "Which practice is risky?", "options": ["Earning relevant editorial links", "Buying large volumes of low-quality links solely to manipulate rankings", "Improving internal links", "Fixing crawl issues"], "correct": "Buying large volumes of low-quality links solely to manipulate rankings"}, {"id": "q3", "type": "choice", "prompt": "What does Google Search Console help you review?", "options": ["Search performance and indexing signals", "Payroll taxes", "Video editing", "Phone calls only"], "correct": "Search performance and indexing signals"}, {"id": "q4", "type": "choice", "prompt": "A page ranks but gets few clicks. Which item should you review?", "options": ["Title, snippet, intent match, and SERP competition", "Only the footer color", "The office chair", "Nothing"], "correct": "Title, snippet, intent match, and SERP competition"}, {"id": "q5", "type": "text", "prompt": "Give a concise SEO audit plan for a local service page that is not ranking well."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Video Editing & Creative','Video Editing & Creative practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "For a short-form video, what usually matters most in the opening seconds?", "options": ["A clear hook", "A long logo animation", "Silence", "A full credit roll"], "correct": "A clear hook"}, {"id": "q2", "type": "choice", "prompt": "What is the safest way to use music in client content?", "options": ["Use any trending song", "Use music the client has rights or appropriate licensing to use", "Download random audio", "Ignore licensing"], "correct": "Use music the client has rights or appropriate licensing to use"}, {"id": "q3", "type": "choice", "prompt": "A client asks for captions. What improves usability?", "options": ["Readable timing, contrast, line length, and accuracy", "Tiny text", "Captions covering faces", "Random spelling"], "correct": "Readable timing, contrast, line length, and accuracy"}, {"id": "q4", "type": "choice", "prompt": "What is a good review workflow?", "options": ["Version files clearly and collect timestamped feedback", "Overwrite the only master file", "Send unnamed exports", "Ignore revision notes"], "correct": "Version files clearly and collect timestamped feedback"}, {"id": "q5", "type": "text", "prompt": "Describe your workflow for turning a 10-minute talking-head recording into three strong reels or shorts."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
insert into public.skills_tests (category,title,instructions,duration_minutes,passing_score,questions) values ('Web & WordPress','Web & WordPress practical screening','Complete the test without outside help. The final written scenario is reviewed by a recruiter alongside your profile and video introduction.',20,70,'[{"id": "q1", "type": "choice", "prompt": "Before updating plugins on a production WordPress site, what is the safest first step?", "options": ["Update everything blindly", "Confirm backups and a rollback path", "Delete the database", "Disable SSL"], "correct": "Confirm backups and a rollback path"}, {"id": "q2", "type": "choice", "prompt": "What should happen before editing theme files directly?", "options": ["Use a child theme, version control, or another safe deployment method", "Edit production with no backup", "Share admin passwords publicly", "Turn off all security"], "correct": "Use a child theme, version control, or another safe deployment method"}, {"id": "q3", "type": "choice", "prompt": "A form stops sending email. What should you check?", "options": ["Form configuration, delivery logs, SMTP, and recent changes", "Only the logo", "Social media followers", "Nothing"], "correct": "Form configuration, delivery logs, SMTP, and recent changes"}, {"id": "q4", "type": "choice", "prompt": "What improves page performance?", "options": ["Optimized assets, caching, efficient code, and appropriate hosting", "Uploading huge uncompressed images", "Adding unnecessary plugins", "Autoplaying many videos"], "correct": "Optimized assets, caching, efficient code, and appropriate hosting"}, {"id": "q5", "type": "text", "prompt": "Outline how you would safely troubleshoot a WordPress page that became slow after a recent update."}]'::jsonb) on conflict (category) do update set title=excluded.title, instructions=excluded.instructions, questions=excluded.questions, active=true;
