-- Australian VA Fundamentals draft.
-- This course teaches administrative awareness and workflows only.
-- It is not tax, legal, privacy, BAS, accounting, or other professional advice.

insert into public.training_courses (
  id, slug, title, summary, category, country_focus, estimated_minutes,
  status, content_version, created_at, updated_at
) values (
  '20000000-0000-4000-8000-000000000001',
  'australian-va-fundamentals',
  'Australian VA Fundamentals',
  'A practical course for Filipino Virtual Assistants working with Australian clients. Covers communication, time zones, business admin terminology, privacy awareness, customer operations, supplier follow-up, and cross-border handoffs without giving regulated professional advice.',
  'foundation',
  'Australia',
  290,
  'draft',
  1,
  now(),
  now()
) on conflict (slug) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('21000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000001', 'Working With Australian Clients', 'Understand client expectations, communication norms, and how to adapt without relying on stereotypes.', 1)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('21000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000001', 'Time, Deadlines, and Working Rhythms', 'Handle Australian time zones, daylight-saving changes, deadlines, and handoffs accurately.', 2)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('21000000-0000-4000-8000-000000000003', '20000000-0000-4000-8000-000000000001', 'Australian Business Admin Basics', 'Recognise common business identifiers, documents, and tax-related terms without stepping into regulated advice.', 3)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('21000000-0000-4000-8000-000000000004', '20000000-0000-4000-8000-000000000001', 'Privacy and Data Handling', 'Work carefully with Australian customer and business information and know when privacy questions must be escalated.', 4)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('21000000-0000-4000-8000-000000000005', '20000000-0000-4000-8000-000000000001', 'Customer and Operations Support', 'Support customers, suppliers, appointments, and recurring operations with clear escalation rules.', 5)
on conflict (course_id, position) do nothing;

insert into public.training_modules (id, course_id, title, summary, position)
values ('21000000-0000-4000-8000-000000000006', '20000000-0000-4000-8000-000000000001', 'Australian Client Handoffs and Simulation', 'Combine the course into practical workflows, handoffs, and a realistic client simulation.', 6)
on conflict (course_id, position) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000001', '21000000-0000-4000-8000-000000000001', 'working-with-australian-business-clients', 'Working With Australian Business Clients', 'Learn how to adapt to an Australian client’s actual working style without assuming every client communicates or operates the same way.',
  '[{"type":"heading","text":"Start with the client, not the stereotype"},{"type":"paragraph","text":"Australian clients are not one personality type. Some are direct, some are highly detailed, some prefer calls, some prefer written updates, and some expect you to work independently inside a clear process. Your job is to learn the operating style of the specific client rather than imitate a cultural stereotype."},{"type":"heading","text":"What to learn in your first week"},{"type":"list","items":["Preferred communication channel for routine work and urgent issues","Normal response-time expectation","Working hours and time zone","How the client wants tasks documented","Which decisions you can make without approval","What requires escalation immediately","How formal or informal customer-facing communication should be","Which systems are the source of truth"]},{"type":"heading","text":"Use examples to calibrate"},{"type":"paragraph","text":"If a client says ''keep me updated'', ask what a useful update looks like. Does the client want a daily summary, task comments, exceptions only, or a message whenever something is blocked? One good example is often more useful than ten vague rules."},{"type":"callout","title":"Do not copy tone blindly","text":"A client may use short or informal messages internally but still expect more formal communication with customers, suppliers, patients, candidates, or executives. Match the context, not just the client’s chat style."},{"type":"scenario","title":"New Australian client","text":"A Melbourne-based client says, ''Just keep an eye on the inbox and calendar for me.'' List the questions you would ask before treating that as permission to reply, reschedule meetings, accept invitations, or archive messages."},{"type":"heading","text":"Key takeaways"},{"type":"list","items":["Learn the client’s operating rules early.","Do not assume informality means low standards.","Confirm decision boundaries.","Use examples to understand what good work looks like for that client."]}]'::jsonb, 25, 1, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000002', '21000000-0000-4000-8000-000000000001', 'australian-client-communication', 'Australian Client Communication and Written Tone', 'Write clear, concise updates for Australian clients while preserving context, professionalism, and the client’s preferred tone.',
  '[{"type":"heading","text":"Clear beats overly formal"},{"type":"paragraph","text":"Professional communication does not need to sound stiff. Most routine remote-work updates are easier to use when they are concise, specific, and action-oriented. The correct tone still depends on the client, audience, and situation."},{"type":"heading","text":"Useful update structure"},{"type":"steps","items":["State the outcome or problem first.","Add only the context needed to understand it.","Say what you already did.","State what you need from the client, if anything.","Include the deadline or consequence when timing matters."]},{"type":"heading","text":"Language details"},{"type":"list","items":["Use the spelling and terminology the client prefers in customer-facing material.","Do not change existing brand copy from Australian English to another style unless asked.","Keep dates unambiguous in operational communication when an overseas reader could interpret them differently.","Use clear time-zone labels for meetings with international participants.","Avoid filler such as repeated greetings, long apologies, and vague phrases that hide the actual issue."]},{"type":"callout","title":"Specific beats polite-but-vague","text":"''The supplier still has not confirmed delivery. I followed up at 10:20 AM Sydney time. If there is no reply by 2 PM, should I call them?'' is more useful than ''Just following up, please advise.''"},{"type":"scenario","title":"Client update","text":"A supplier has delayed an order by two days. Draft a short update for the client that separates the confirmed fact, your action, the business impact, and the decision you need from them."},{"type":"heading","text":"Before sending"},{"type":"list","items":["Is the point obvious in the first two lines?","Did I separate fact from assumption?","Did I include the relevant task or document link?","Did I make the next action clear?","Would the message still make sense to someone reading it later?"]}]'::jsonb, 25, 2, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000003', '21000000-0000-4000-8000-000000000002', 'australian-time-zones-and-daylight-saving', 'Australian Time Zones and Daylight-Saving Changes', 'Avoid missed meetings and deadlines when Australian states, territories, and overseas team members are on different clocks.',
  '[{"type":"heading","text":"Never manage Australian schedules from memory alone"},{"type":"paragraph","text":"Australia spans multiple time zones, and daylight-saving changes can alter the difference between the Philippines and some Australian locations during the year. A reliable VA uses the location’s actual time zone and checks the converted time before sending an invitation or deadline."},{"type":"heading","text":"Scheduling workflow"},{"type":"steps","items":["Identify the city or exact business time zone, not just ''Australia''.","Check the target date because seasonal clock changes may affect the offset.","Convert the proposed time using a reliable calendar or time-zone tool.","Write the local time and zone clearly in the invitation or confirmation.","Check the event again after saving, especially if the meeting was moved across dates."]},{"type":"heading","text":"Operational habits"},{"type":"list","items":["Store the client’s primary business time zone in your onboarding notes.","Use location-based calendar time zones rather than manually adding hours.","Confirm the attendee’s location when it is unclear.","Include dates, not only words such as tomorrow or Friday, in important cross-border deadlines.","Be cautious with recurring meetings around seasonal time changes."]},{"type":"callout","title":"Do not assume Sydney time equals every Australian location","text":"Use the actual city or time zone for the business or attendee. The safest workflow is always date-aware conversion."},{"type":"scenario","title":"Recurring weekly call","text":"A weekly client call is scheduled for 9:00 AM Sydney time. Explain what you would check before telling the Manila-based team that the call will always occur at the same Philippine time throughout the year."},{"type":"heading","text":"The standard"},{"type":"list","items":["Use exact locations and dates.","Let calendar software convert, then verify.","Make the local time visible to the reader.","Treat recurring meetings as something to re-check around seasonal clock changes."]}]'::jsonb, 30, 1, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000004', '21000000-0000-4000-8000-000000000002', 'deadlines-holidays-and-australian-handoffs', 'Deadlines, Business Days, and Australian Handoffs', 'Make deadlines explicit, account for client availability, and hand work over without creating cross-time-zone confusion.',
  '[{"type":"heading","text":"A deadline should be specific enough to act on"},{"type":"paragraph","text":"In cross-border work, ''end of day'' can be ambiguous. Use an exact date, local business time, and time zone when delay has a consequence. If a deadline depends on an Australian business day, confirm the client’s actual working calendar rather than assuming every state or industry observes the same schedule."},{"type":"heading","text":"Before committing to a deadline"},{"type":"list","items":["Which time zone controls the deadline?","Does the client need time to review before the external deadline?","Is another person or supplier required before you can finish?","Is the client likely to be offline when you need approval?","Does the task fall near a local public holiday or office closure that the client has flagged?"]},{"type":"heading","text":"Good handoff format"},{"type":"steps","items":["Done: what has been completed.","Waiting: what cannot move yet.","Owner: who acts next.","Deadline: exact date and time zone.","Evidence: link the task, thread, document, or record.","Risk: anything that could affect the outcome if nobody acts."]},{"type":"scenario","title":"Friday handoff","text":"Your Manila shift ends while the Australian client is still online. A customer needs a quote Monday morning, but the price requires client approval. Write a handoff that prevents the client from assuming the quote has already been sent."},{"type":"callout","title":"Do not manufacture urgency","text":"A local holiday, time-zone difference, or client absence may change the realistic deadline. Surface the constraint early instead of promising a time you cannot control."}]'::jsonb, 25, 2, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000005', '21000000-0000-4000-8000-000000000003', 'abn-acn-gst-and-bas-awareness', 'ABN, ACN, GST, and BAS: What a VA Should Recognise', 'Recognise common Australian business and tax terms so you can process documents correctly without giving tax or accounting advice.',
  '[{"type":"heading","text":"Administrative awareness, not tax advice"},{"type":"paragraph","text":"Australian clients may refer to business identifiers and tax documents in everyday admin work. You should recognise the terms, know where they may appear, and know when a question must go back to the client, bookkeeper, accountant, or registered adviser."},{"type":"heading","text":"Common terms you may see"},{"type":"list","items":["ABN: an Australian Business Number used to identify a business or organisation in dealings with government and the community.","ACN: an Australian Company Number associated with registered companies.","GST: goods and services tax. A client may discuss whether amounts are GST-inclusive, whether a supplier is GST-registered, or how invoices are coded.","BAS: business activity statement. Businesses may use it to report and pay certain tax obligations such as GST and PAYG items, depending on their circumstances."]},{"type":"heading","text":"What a VA can safely do"},{"type":"list","items":["Copy an ABN from an approved source into the correct business record.","Check whether the invoice includes the information the client’s SOP requires.","File receipts and invoices into the correct period or folder.","Prepare a list of missing documents for the bookkeeper.","Follow a documented coding workflow where the client or bookkeeper has already defined the rule.","Flag unclear tax treatment instead of inventing a category."]},{"type":"heading","text":"What should be escalated"},{"type":"list","items":["Whether a business should register for GST.","Whether a transaction is taxable, GST-free, input taxed, deductible, or claimable.","How a BAS should be completed or corrected.","Whether a person is entitled to an ABN.","Questions that require tax, BAS, accounting, or legal advice rather than administration."]},{"type":"callout","title":"Source of truth","text":"For tax-related rules, rely on the client’s approved adviser and current official guidance. Do not turn an old spreadsheet rule or AI answer into tax advice."},{"type":"scenario","title":"Unclear invoice coding","text":"A supplier invoice has an ABN and a total amount, but the GST treatment does not match the client’s usual pattern. Describe what you can check administratively and what you should escalate rather than decide yourself."}]'::jsonb, 30, 1, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000006', '21000000-0000-4000-8000-000000000003', 'invoices-records-and-bookkeeper-handoffs', 'Invoices, Records, and Bookkeeper Handoffs', 'Prepare financial admin cleanly for a client or bookkeeper without crossing into tax or accounting decisions.',
  '[{"type":"heading","text":"Good bookkeeping support starts with clean evidence"},{"type":"paragraph","text":"Many VA roles include collecting invoices, attaching receipts, matching documents to transactions, following up missing paperwork, or preparing a clean queue for a bookkeeper. The value is accuracy and completeness, not pretending to be the tax adviser."},{"type":"heading","text":"Document workflow"},{"type":"steps","items":["Confirm the correct entity or business before filing the document.","Check supplier or customer name, invoice number, date, amount, and available tax details.","Save the source document in the approved system.","Link or attach it to the relevant transaction or record when the workflow requires it.","Flag duplicates, missing documents, unusual amounts, or unclear coding.","Leave unresolved tax treatment for the authorised person to decide."]},{"type":"heading","text":"Useful exception list"},{"type":"list","items":["Missing receipt or invoice","Duplicate invoice number","Amount does not match the payment","Supplier details differ from previous records","GST or tax treatment looks inconsistent with the documented rule","Credit note or refund is not reflected in the record","Transaction belongs to an unclear business entity"]},{"type":"callout","title":"Do not silently fix a financial discrepancy","text":"If the source document and system disagree, preserve the evidence and flag the difference. A clean audit trail is more valuable than making the numbers look tidy."},{"type":"scenario","title":"Month-end document chase","text":"The bookkeeper asks for five missing receipts, two supplier invoices, and clarification on one duplicate-looking transaction. Build the checklist you would use to collect the evidence and hand it back clearly."}]'::jsonb, 25, 2, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000007', '21000000-0000-4000-8000-000000000004', 'australian-privacy-principles-for-va-admin', 'Australian Privacy Principles: Practical Awareness for VAs', 'Understand why Australian clients may have strict rules for collecting, accessing, storing, and sharing personal information.',
  '[{"type":"heading","text":"Privacy is an operating requirement, not only a policy page"},{"type":"paragraph","text":"Australian businesses may be subject to the Privacy Act and Australian Privacy Principles depending on their circumstances. The rules cover areas such as collection, use, disclosure, data quality, access, correction, and security of personal information. A VA does not need to interpret the law, but should follow the client’s approved privacy and security processes."},{"type":"heading","text":"Practical habits"},{"type":"list","items":["Collect only the information the workflow actually requires.","Use the approved system rather than keeping customer data in personal notes or accounts.","Do not reuse customer information for a new purpose without authorisation.","Check recipients before sharing customer records or attachments.","Do not upload customer or employee data to AI or third-party tools unless the client has approved that workflow.","Report suspected privacy or security incidents immediately through the client’s process."]},{"type":"heading","text":"Cross-border work needs extra care"},{"type":"paragraph","text":"A Filipino VA may access Australian customer information from outside Australia. That does not automatically mean the work is prohibited, but it makes the client’s approved systems, access controls, privacy instructions, and vendor choices especially important. Do not independently decide what cross-border disclosure is legally permitted."},{"type":"callout","title":"Personal information can still be sensitive even if it looks routine","text":"Names, contact details, financial information, health information, identifiers, customer histories, and internal employee records may require controlled handling. Follow the client’s classification and access rules."},{"type":"scenario","title":"Export request","text":"A client asks you to export a customer list into a spreadsheet and upload it to a new marketing tool you have never used before. List the checks you should make before transferring the data."},{"type":"heading","text":"Escalate when"},{"type":"list","items":["A customer asks to access or correct their personal information and you do not have an approved response workflow.","You think information was sent to the wrong person.","A new tool or integration will receive personal information.","Someone asks you to collect more information than the normal process requires.","You are unsure whether you are authorised to disclose or reuse personal data."]}]'::jsonb, 30, 1, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000008', '21000000-0000-4000-8000-000000000004', 'security-access-and-client-data', 'Security, Access, and Client Data', 'Apply practical security habits when working remotely with Australian client accounts, documents, customers, and team systems.',
  '[{"type":"heading","text":"Remote access increases responsibility"},{"type":"paragraph","text":"A remote VA may have access to inboxes, CRMs, calendars, customer files, accounting tools, cloud storage, and other systems. Convenience should not override access control. Use only the accounts and permissions you were given for the work."},{"type":"heading","text":"Daily security habits"},{"type":"list","items":["Use unique passwords and the client’s approved password-sharing method.","Use multi-factor authentication where required.","Keep work accounts separate from personal accounts where practical.","Lock your device when unattended.","Do not share client files through personal messaging apps unless that is the approved workflow.","Avoid downloading customer data when the work can be completed inside the authorised system.","Remove local copies when the client’s process says they are no longer needed."]},{"type":"heading","text":"When something looks wrong"},{"type":"steps","items":["Stop before taking additional risky action.","Preserve evidence such as the message, time, account, or error details.","Tell the correct client contact using the incident process.","Do not investigate beyond your authority.","Do not hide an accidental disclosure or access mistake."]},{"type":"callout","title":"Security mistakes get worse when hidden","text":"Early reporting gives the client a better chance to contain the problem. The goal is accurate, fast escalation, not avoiding embarrassment."},{"type":"scenario","title":"Unexpected login prompt","text":"While working in the client’s CRM, you receive repeated authentication prompts and then a message asking you to approve a login you did not initiate. Explain what you should do and what you should not do."}]'::jsonb, 25, 2, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000009', '21000000-0000-4000-8000-000000000005', 'customer-service-and-escalation', 'Customer Service and Escalation for Australian Clients', 'Handle routine customer communication confidently while keeping refunds, complaints, risk, and exceptions inside the client’s authority rules.',
  '[{"type":"heading","text":"The goal is resolution inside the rules"},{"type":"paragraph","text":"Customer support is not about saying yes to everything. A strong VA knows the standard process, communicates clearly, records the interaction, and escalates exceptions before making commitments the business has not authorised."},{"type":"heading","text":"Before replying"},{"type":"list","items":["Read the full customer history, not only the latest message.","Check the relevant policy or SOP.","Confirm what you are authorised to offer.","Separate the customer’s emotion from the factual issue that needs solving.","Identify whether timing changes the severity of the issue."]},{"type":"heading","text":"Escalation triggers may include"},{"type":"list","items":["Refunds or credits outside the normal policy","Threats of legal action, regulator complaints, chargebacks, or serious public escalation","Safety concerns","Privacy or security complaints","Disputes about contract terms or pricing","Requests for professional advice that your role cannot provide","Repeated service failures or high-value accounts that the client wants handled personally"]},{"type":"callout","title":"Do not invent policy to calm someone down","text":"If you cannot promise a refund, replacement, deadline, or exception, say what you can do next instead of making a commitment you may have to reverse later."},{"type":"scenario","title":"Angry customer","text":"A customer says they were promised same-day service but no technician arrived. The CRM shows a booking for tomorrow, not today. Draft the first response and list what you would verify before blaming the customer or the team."}]'::jsonb, 25, 1, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000010', '21000000-0000-4000-8000-000000000005', 'suppliers-appointments-and-operational-follow-up', 'Suppliers, Appointments, and Operational Follow-up', 'Keep routine Australian business operations moving through accurate scheduling, confirmations, follow-ups, and visible records.',
  '[{"type":"heading","text":"Operational admin is about preventing dropped work"},{"type":"paragraph","text":"A large part of VA work is making sure the next step actually happens. This may involve suppliers, customers, contractors, appointments, quotes, deliveries, internal approvals, or recurring tasks."},{"type":"heading","text":"Follow-up workflow"},{"type":"steps","items":["Record what was requested and when.","Set the expected response or completion time.","Follow up through the agreed channel.","Log the result in the system of record.","Escalate if the delay affects a customer, deadline, cost, or dependent task.","Close the loop with the relevant person rather than leaving the status buried in a message thread."]},{"type":"heading","text":"Appointment checks"},{"type":"list","items":["Correct date, time, and time zone","Customer or attendee contact details","Location or meeting link","Assigned staff member or provider","Required preparation or access notes","Confirmation status","Cancellation or reschedule instructions","Follow-up required after the appointment"]},{"type":"scenario","title":"Supplier delay","text":"A supplier promised delivery Wednesday but now says Friday. A customer installation is booked Thursday. Explain what you should update, who should be notified, and which decision belongs to the client rather than the VA."},{"type":"callout","title":"A status update is not a completed workflow","text":"If the delay creates a new task, customer notification, reschedule, or approval, record and assign that next step explicitly."}]'::jsonb, 25, 2, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_lessons (
  id, module_id, slug, title, summary, content, estimated_minutes, position,
  is_published, content_version, created_at, updated_at
) values (
  '22000000-0000-4000-8000-000000000011', '21000000-0000-4000-8000-000000000006', 'australian-va-handoffs-and-work-simulation', 'Australian VA Handoffs and Work Simulation', 'Combine communication, time zones, business terminology, privacy, and operational judgment in one realistic Australian client workflow.',
  '[{"type":"heading","text":"The final skill is connecting the pieces"},{"type":"paragraph","text":"Real VA work rarely arrives as one clean task. A single customer issue can touch the inbox, calendar, CRM, supplier communication, privacy, a deadline, and a client decision. The goal is to keep the workflow moving without losing context or exceeding your authority."},{"type":"heading","text":"Composite client scenario"},{"type":"scenario","title":"Harbour Field Services","text":"Harbour Field Services is a fictional Australian service business. A customer emails at 8:10 AM Sydney time saying their equipment has failed and they need urgent help. The CRM shows the customer’s mobile number, site address, previous service history, and an unpaid invoice. A technician has a 1:00 PM job near the customer but the schedule is otherwise full. A supplier message says a replacement part may arrive tomorrow. The client is in a meeting for the next 45 minutes."},{"type":"heading","text":"Your job"},{"type":"steps","items":["Identify what information is confirmed and what is still missing.","Decide which actions can safely proceed under a normal admin workflow.","List the decisions that require client approval.","Draft the first customer acknowledgement without promising an arrival time you cannot guarantee.","Prepare the internal note for the technician or scheduler.","Record the follow-up deadline and time zone.","Identify any customer information that should remain inside approved systems.","Write the client handoff so they can make the pending decision quickly when they return."]},{"type":"heading","text":"Quality check"},{"type":"list","items":["Did you separate facts, assumptions, and decisions?","Did you use the correct local time context?","Did you avoid giving tax, legal, technical, or regulated advice?","Did you protect personal information?","Did you avoid promising service, pricing, refunds, or parts before approval?","Did you leave a clear record for the next person?"]},{"type":"callout","title":"This is the standard for the rest of the training library","text":"A good VA should be able to explain not only what action they would take, but why the action is safe, what evidence they would leave, and when they would escalate."}]'::jsonb, 25, 1, false, 1, now(), now()
) on conflict (module_id, slug) do nothing;

insert into public.training_assessments (
  id, course_id, module_id, title, instructions, assessment_type, pass_score,
  position, is_published, created_at, updated_at
) values (
  '23000000-0000-4000-8000-000000000001',
  '20000000-0000-4000-8000-000000000001',
  '21000000-0000-4000-8000-000000000006',
  'Australian Client Operations Simulation',
  'Complete a composite Australian client workflow covering time zones, customer communication, supplier follow-up, privacy-safe handling of customer information, business-admin terminology, escalation decisions, and a written client handoff. This is an administrative judgment assessment, not a tax, legal, privacy, or accounting qualification.',
  'practical',
  null,
  1,
  false,
  now(),
  now()
) on conflict (id) do nothing;
