-- Write the existing Operations Virtual Assistant course.
-- Course remains draft-only until reviewer metadata and explicit publication are recorded.

update public.training_courses
set
  summary = 'A practical operations course for Virtual Assistants covering process ownership, SOPs, recurring workflows, vendor coordination, handoffs, data reconciliation, KPI reporting, process improvement, automation awareness, and incident coordination.',
  estimated_minutes = 300,
  status = 'draft',
  published_at = null,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '20000000-0000-4000-8000-000000000012';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Operations work turns repeated activity into a dependable system"},{"type":"paragraph","text":"An Operations Virtual Assistant helps a business keep recurring work moving. The role is broader than completing isolated tasks. You need to understand what starts a process, what information it needs, who owns each step, what a correct result looks like, and what should happen when the normal flow breaks."},{"type":"heading","text":"Five parts of a process"},{"type":"list","items":["Trigger: what starts the work, such as a new order, signed client, scheduled meeting, or monthly deadline.","Input: the information, access, document, payment, approval, or request needed before work can proceed.","Steps: the actions performed in the normal sequence.","Output: the result the business needs, such as a completed onboarding, approved invoice, dispatched order, or reconciled report.","Owner and control: who is responsible and what check prevents an incorrect or incomplete result."]},{"type":"heading","text":"Do not confuse a list of actions with a process"},{"type":"paragraph","text":"A checklist that says ''email client, update CRM, create folder'' may describe activity, but it does not tell you when the workflow begins, which client data is required, what happens when information is missing, who approves exceptions, or how the business knows the workflow is complete."},{"type":"callout","title":"A useful operations question","text":"If the person who usually does this task disappeared for a week, could another trained person continue from the process, records, and ownership rules that exist today?"},{"type":"scenario","title":"New client onboarding","text":"A fictional consulting company signs a new client. Sales marks the deal won, but operations needs a signed agreement, billing contact, project owner, kickoff date, shared folder, and internal handoff. Map the trigger, inputs, core steps, output, owner, and one control that would prevent an incomplete onboarding."},{"type":"heading","text":"What good operations work leaves behind"},{"type":"list","items":["A visible status","A clear owner","The source documents or data","A next action when incomplete","A record of exceptions","A definition of done","Enough context for another person to continue"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000011';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Normal work and exception work are different"},{"type":"paragraph","text":"A process is efficient when routine cases can move without constant approval and unusual cases are clearly recognised. An Operations VA should know the normal rule, the thresholds that create an exception, and the escalation path for cases outside authority."},{"type":"heading","text":"Operational risks to watch"},{"type":"list","items":["Deadline risk: a task will miss a client, supplier, payroll, delivery, or reporting deadline.","Data risk: information is missing, duplicated, inconsistent, or entered into the wrong record.","Financial risk: a payment, invoice, refund, purchase, or pricing decision is unclear.","Access risk: the wrong person may have access or required access is missing.","Customer risk: an unresolved issue could affect service delivery or trust.","Dependency risk: another team cannot proceed until your step is complete.","Compliance or safety risk: the work touches rules or consequences outside normal admin authority."]},{"type":"heading","text":"Escalate with a decision-ready summary"},{"type":"steps","items":["State the exception in one sentence.","Show the verified facts.","Explain the operational impact.","State what you have already done.","Identify the decision or approval needed.","Include the deadline or next checkpoint.","Link the source record."]},{"type":"callout","title":"Do not escalate raw chaos","text":"Forwarding a long thread with ''what should I do?'' makes the manager reconstruct the issue. Summarise the exception so they can make the decision quickly."},{"type":"scenario","title":"Supplier capacity issue","text":"Your supplier can deliver only 60 of 100 units needed for a client order due Friday. The client expects the full quantity and partial delivery has not been discussed. Write the exception summary, identify the business decisions that require approval, and list the safe admin work you can complete immediately."},{"type":"heading","text":"Track exceptions, not only tasks"},{"type":"paragraph","text":"If the same exception happens repeatedly, it may be a process-design problem rather than a one-off mistake. Operations should make recurring failure visible so the business can improve the process instead of solving the same problem manually forever."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000012';

update public.training_lessons
set
  content = '[{"type":"heading","text":"An SOP should help someone perform the work correctly"},{"type":"paragraph","text":"A standard operating procedure is useful when it reduces ambiguity. It should explain the purpose, trigger, owner, inputs, steps, exceptions, and completion checks for a repeatable workflow. A long document is not automatically a good SOP."},{"type":"heading","text":"Core SOP structure"},{"type":"list","items":["Purpose: why the process exists","Trigger: when the procedure begins","Owner: who is accountable","Inputs and access: what must be available","Procedure: ordered steps","Decision rules: what changes the path","Exceptions and escalation: what not to decide alone","Quality checks: what must be true before completion","Output and handoff: where the result goes","Review information: version, owner, and last reviewed date"]},{"type":"heading","text":"Write for the person doing the task"},{"type":"paragraph","text":"Avoid vague instructions such as ''process the request normally'' or ''update the system as needed''. Explain what record to update, which field matters, what source to use, and how the person knows the step succeeded."},{"type":"callout","title":"Screenshots expire","text":"Screenshots can help, but interfaces change. Pair screenshots with written field names and decision rules so the SOP does not become unusable after a small software redesign."},{"type":"scenario","title":"Turn tribal knowledge into an SOP","text":"A team member says: ''Every Monday I check unpaid invoices, message clients, then tell the owner if anything looks bad.'' Turn this into an SOP outline. Identify which parts are too vague to document without asking more questions."},{"type":"heading","text":"Maintenance rules"},{"type":"list","items":["Review an SOP after major process, software, policy, or ownership changes.","Record version changes when the update affects how work is performed.","Do not silently rewrite approval thresholds or business rules.","Archive outdated instructions rather than leaving several competing versions active.","When an exception becomes common, decide whether it belongs in the SOP."]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000021';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Use the right tool for the right repeatable behaviour"},{"type":"paragraph","text":"SOPs explain how a process works. Checklists help prevent skipped steps. Templates reduce repeated drafting. Recurring tasks make sure time-based work reappears. Good operations systems combine them without creating duplicate reminders everywhere."},{"type":"heading","text":"When to use each"},{"type":"list","items":["Checklist: the sequence is stable and missing a step creates risk.","Template: the structure repeats but details change, such as a weekly report or client handoff.","Recurring task: the work must happen on a reliable schedule.","SOP: the workflow has decisions, context, roles, or exception rules that need explanation.","Automation: a stable rule can safely move data or trigger work without manual judgment."]},{"type":"heading","text":"Design a recurring task well"},{"type":"steps","items":["Name the outcome, not just the activity.","Set the correct frequency and time zone.","Assign one accountable owner.","Attach the SOP or source of truth.","Include the required inputs.","Define what completion evidence should be left.","Add a fallback for missed or blocked runs when needed."]},{"type":"callout","title":"Avoid reminder duplication","text":"If the same weekly process appears in the CRM, project tool, calendar, Slack reminder, and a private spreadsheet, nobody knows which copy is authoritative."},{"type":"scenario","title":"Monthly reporting system","text":"A client wants monthly operational reporting by the third business day. Design the recurring task, checklist, report template, required inputs, owner, review step, and late-data escalation."},{"type":"heading","text":"A good template speeds work without hiding judgment"},{"type":"paragraph","text":"Templates should make the expected structure obvious while leaving room for exceptions. A weekly update template can require outcomes, blockers, risks, metrics, and next actions without forcing every week to look identical."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000022';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Coordination is evidence plus follow-through"},{"type":"paragraph","text":"Vendor, supplier, and contractor administration often includes requesting quotes, confirming scope, collecting documents, tracking delivery, following up invoices, recording contacts, and escalating service problems. The VA coordinates the process but should not invent commercial authority."},{"type":"heading","text":"Build a usable vendor record"},{"type":"list","items":["Legal or trading name","Primary contacts","Approved services or scope","Commercial terms the client has authorised you to reference","Order or contract references","Delivery or service expectations","Required documents","Current open issues","Last contact and next follow-up","Internal owner"]},{"type":"heading","text":"Quote and purchase coordination"},{"type":"steps","items":["Confirm the requirement and specification.","Request comparable information from approved vendors.","Record price, inclusions, exclusions, delivery, validity, and payment terms.","Flag meaningful differences rather than comparing only the headline price.","Send the comparison to the authorised decision-maker.","Place or confirm the order only within your approval authority.","Track the commitment until receipt or completion."]},{"type":"callout","title":"Do not negotiate authority you do not have","text":"You can collect options and communicate approved positions. Do not accept contract changes, pricing commitments, minimum volumes, payment terms, or penalties unless the client has authorised you to do so."},{"type":"scenario","title":"Three supplier quotes","text":"Three vendors quote the same job. The cheapest excludes delivery, one has a four-week lead time, and the most expensive can complete next week. Build the comparison table fields and explain what decision belongs to the client."},{"type":"heading","text":"Close the loop"},{"type":"list","items":["Confirm delivery or completion","Record discrepancies","Collect final documents","Match invoice to authorised work where that is part of the process","Escalate unresolved quality or payment issues","Update vendor performance notes when the client uses them"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000031';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Dependencies are where operations work gets stuck"},{"type":"paragraph","text":"Many workflows cross teams. Sales may need finance approval. Operations may wait on a supplier. Marketing may need legal review. A task can look active for days while nothing is actually moving because the dependency is hidden."},{"type":"heading","text":"Track more than the task owner"},{"type":"list","items":["Current owner","Next owner","Dependency","Required input","Due date","Status","Last meaningful update","Next follow-up","Escalation point","Source record or link"]},{"type":"heading","text":"Handoff quality"},{"type":"steps","items":["State the desired outcome.","Summarise completed work.","List unresolved items.","Provide the required evidence and links.","Name the next owner.","State the deadline or service impact.","Confirm the handoff was received when the process requires acknowledgement."]},{"type":"callout","title":"Assignment is not acceptance","text":"Moving a card to another person does not guarantee they saw it, understood it, or can act. For high-impact work, the handoff may need explicit acknowledgement."},{"type":"scenario","title":"Client launch dependency chain","text":"A launch needs contract signature, first payment, account setup, creative assets, and a kickoff meeting. Payment is late and creative is incomplete. Map the dependency chain, identify what can proceed safely, and write the handoff that prevents teams from assuming the launch is ready."},{"type":"heading","text":"How to report blocked work"},{"type":"paragraph","text":"A good blocked-work report names the dependency, owner, expected date, business impact, and next follow-up. ''Waiting on client'' is usually not enough."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000032';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Operational decisions depend on trustworthy records"},{"type":"paragraph","text":"Operations VAs often maintain trackers, CRMs, order systems, task boards, spreadsheets, and reporting inputs. Data quality means the record is complete enough, consistent enough, and current enough for the next person or report to rely on it."},{"type":"heading","text":"Common data-quality problems"},{"type":"list","items":["Duplicate records","Missing required fields","Inconsistent statuses","Dates stored in mixed formats","Amounts copied from the wrong source","Closed items still marked open","One system updated while another remains stale","Free-text notes used where structured fields should carry the value"]},{"type":"heading","text":"Reconciliation means comparing sources"},{"type":"steps","items":["Define the two or more sources being compared.","Choose the matching key such as ID, invoice number, email, order number, or date.","Compare expected records and values.","Separate exact matches, missing items, duplicates, and mismatches.","Investigate from the authoritative source.","Correct only what your role allows.","Record unresolved exceptions for review."]},{"type":"callout","title":"Do not make numbers agree by deleting evidence","text":"If two systems disagree, preserve the discrepancy until you know which source is authoritative. A clean-looking report can be dangerously wrong."},{"type":"scenario","title":"Order reconciliation","text":"The order system shows 248 orders this week while the fulfilment tracker shows 241. Design the reconciliation steps. Include how you would identify cancellations, duplicates, late imports, and records that need investigation."},{"type":"heading","text":"Before bulk cleanup"},{"type":"list","items":["Confirm backup or version history","Define duplicate logic","Confirm source of truth","Test the change on a small sample","Document transformation rules","Recheck totals after the change"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000041';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Reporting should help someone decide what to do"},{"type":"paragraph","text":"A KPI report is not useful because it contains many numbers. It is useful when it shows whether the operation is on track, where performance changed, what caused the change if known, and which exceptions need action."},{"type":"heading","text":"Every KPI needs a definition"},{"type":"list","items":["Name: what is being measured","Formula: how it is calculated","Population: which records are included or excluded","Period: daily, weekly, monthly, rolling period, or cohort","Source: where the data comes from","Target or threshold: if one exists","Owner: who acts when the metric is off track"]},{"type":"heading","text":"A useful operations report"},{"type":"steps","items":["Lead with the most important changes.","Show actual versus target or previous period where relevant.","Explain material exceptions, not every small fluctuation.","Separate confirmed causes from hypotheses.","List decisions or actions required.","Link the underlying detail for people who need it."]},{"type":"callout","title":"Do not invent explanations for movement","text":"If response time worsened and you do not know why, report the change and investigate. Do not write a confident reason just because it sounds plausible."},{"type":"scenario","title":"Weekly operations report","text":"On-time completion fell from 94% to 82%, open backlog rose from 35 to 71, and one vendor caused 18 delayed tasks. Draft the executive summary and the exception section without burying the main operational problem."},{"type":"heading","text":"Exception summary format"},{"type":"list","items":["What changed","Magnitude","Affected workflow","Verified cause, if known","Current owner","Action underway","Decision needed","Next checkpoint"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000042';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Bottlenecks are where work waits"},{"type":"paragraph","text":"A bottleneck is a step whose capacity or delay limits the flow of the whole process. Repeated failure points are places where errors, rework, missing information, or exceptions keep occurring. Operations improvement starts by observing the real workflow instead of blaming individuals too early."},{"type":"heading","text":"Signals of a bottleneck"},{"type":"list","items":["Work piles up before one step","The same approver is always late","Many tasks are reopened for missing information","One team constantly asks another team for status","Customers repeatedly chase the same stage","The process depends on one person’s memory","Manual copy-paste creates recurring errors"]},{"type":"heading","text":"Find the cause before proposing the fix"},{"type":"steps","items":["Define the failure in measurable terms.","Map the current process.","Look for where delay or rework begins.","Review a sample of real cases.","Separate one-off mistakes from repeated patterns.","Identify whether the cause is capacity, unclear ownership, missing input, bad tooling, weak policy, or poor process design.","Test the smallest safe change that addresses the actual cause."]},{"type":"callout","title":"Do not automate a broken process first","text":"Automation can make a bad process fail faster and at larger scale. Stabilise the rule and exception path before automating it."},{"type":"scenario","title":"Slow client onboarding","text":"Average onboarding takes nine days. Data shows contracts are signed in one day, payment averages two days, but account setup waits an average of five days because requests arrive through email with missing fields. Identify the likely bottleneck and propose two small changes to test before buying new software."},{"type":"heading","text":"Measure after the change"},{"type":"paragraph","text":"A process improvement is only an improvement if the result gets better without creating a new hidden problem. Recheck cycle time, errors, backlog, customer impact, and team effort after the change."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000051';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Automation is a controlled transfer of work to a rule"},{"type":"paragraph","text":"An Operations VA does not need to be a developer to spot automation opportunities. You do need to understand the trigger, conditions, action, data, failure mode, and manual fallback before automating a business process."},{"type":"heading","text":"Good automation candidates"},{"type":"list","items":["Stable repetitive steps","Clear structured inputs","Low-ambiguity rules","High volume manual copying","Time-based reminders","Status changes with predictable downstream actions","Notifications triggered by known conditions"]},{"type":"heading","text":"Poor automation candidates"},{"type":"list","items":["Processes whose business rules are still changing","High-impact decisions requiring human judgment","Messy source data with frequent exceptions","Steps involving sensitive data in tools the client has not approved","Actions that are difficult to reverse","Workflows with no monitoring or failure owner"]},{"type":"heading","text":"Safe change sequence"},{"type":"steps","items":["Document the current workflow.","Define the exact rule being automated.","List exceptions and stop conditions.","Test with sample or low-risk records.","Set an owner for failures.","Keep a manual fallback.","Monitor results after release.","Document the new workflow and version change."]},{"type":"callout","title":"Automation should fail visibly","text":"A silent automation failure is often worse than a manual task because people assume the work happened. Make failures observable and owned."},{"type":"scenario","title":"Lead handoff automation","text":"The client wants every website enquiry automatically assigned to sales. Some forms are spam, some are support requests, and some are existing clients. Explain what needs to be classified before automatic assignment and what should happen when the rule is uncertain."},{"type":"heading","text":"Change-management habit"},{"type":"paragraph","text":"Tell the people affected what changed, when it changed, what they should do differently, and how to report a problem. A technically correct automation can still fail if the team does not understand the new process."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000052';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Incidents need coordination before they need perfect explanations"},{"type":"paragraph","text":"An operational incident is an unexpected event that materially disrupts normal service, delivery, access, data, or a critical workflow. An Operations VA may help coordinate information and follow-up, but should not take technical, legal, security, financial, or public-communications authority they were not given."},{"type":"heading","text":"First-response priorities"},{"type":"steps","items":["Confirm the incident and affected process.","Record the start time and known impact.","Notify the correct owner or incident lead.","Stop any routine automation or action the approved incident plan says to pause.","Collect verified updates from responsible teams.","Maintain one incident record or timeline.","Track decisions, owners, and next checkpoints.","Prepare internal or customer updates only within the approved communication process."]},{"type":"heading","text":"Incident log fields"},{"type":"list","items":["Time","Verified event","Source","Impact","Action taken","Owner","Decision","Next checkpoint","Resolution evidence"]},{"type":"callout","title":"Do not speculate during an incident","text":"If the cause is unknown, record it as unknown. Guessing the cause can send teams in the wrong direction and create inaccurate customer communication."},{"type":"scenario","title":"Critical system unavailable","text":"At 10:15 AM the client’s booking system becomes unavailable. Staff cannot see appointments and customers are calling. The vendor status page shows an active outage but no restoration time. Build the incident coordination checklist and draft the internal update without inventing an ETA."},{"type":"heading","text":"Business continuity handoff"},{"type":"paragraph","text":"If the incident continues across shifts, hand over the timeline, current impact, temporary workaround, outstanding decisions, next vendor checkpoint, customer communication status, and exact owner for each open action."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000061';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Final composite operations simulation"},{"type":"paragraph","text":"This simulation combines process mapping, SOP judgment, recurring work, vendor coordination, data reconciliation, KPI reporting, bottleneck analysis, and incident handoff. The company is fictional and built from common operating patterns rather than any single real client."},{"type":"scenario","title":"Summit Service Group","text":"Summit Service Group manages recurring field-service work. Monday morning brings several issues at once: 14 jobs from Friday are still open, a supplier has delayed materials for six Tuesday jobs, the CRM contains five duplicate client records, last week’s on-time completion rate fell from 93% to 79%, and the booking automation stopped creating tasks overnight. The operations manager is unavailable for 45 minutes."},{"type":"heading","text":"Part 1: Stabilise the operation"},{"type":"steps","items":["List the issues in priority order and explain why.","Identify which work can continue safely without manager approval.","Identify what should be paused because automation or data integrity is uncertain.","Assign an owner and next checkpoint to each issue.","Draft the manager’s decision-ready summary."]},{"type":"heading","text":"Part 2: Diagnose the process"},{"type":"list","items":["Map the likely dependencies affecting Tuesday jobs.","Design the duplicate-record reconciliation approach.","List the data needed to explain the on-time completion decline.","Describe how you would determine whether the automation failure is isolated or still active.","Identify any repeated failure that should trigger an SOP or process update."]},{"type":"heading","text":"Part 3: Improve and hand off"},{"type":"steps","items":["Propose one low-risk process improvement.","Propose one automation or alert only if the underlying rule is stable.","Write the end-of-shift handoff.","List the evidence that should be attached or linked.","Define what would make each issue complete rather than merely ''in progress''."]},{"type":"callout","title":"Assessment standard","text":"A strong operations answer makes ownership, dependencies, evidence, exceptions, and next actions visible. It does not hide uncertainty or make unauthorised decisions just to make the board look clean."},{"type":"heading","text":"Self-review"},{"type":"list","items":["Did I protect the source of truth?","Did I separate routine work from exceptions?","Did every open item have an owner and checkpoint?","Did I avoid automating an unstable rule?","Did I make the manager’s decisions easy to understand?","Could another operator continue from my notes?"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000012-0000-4000-8000-000000000062';

update public.training_assessments
set
  instructions = 'Complete the Summit Service Group composite operations simulation. Map process dependencies, prioritise operational exceptions, reconcile data issues, assess KPI movement, coordinate vendor and incident follow-up, propose safe process improvements, and produce a decision-ready manager summary plus end-of-shift handoff. The assessment tests operational judgment and work output rather than process trivia.',
  is_published = false,
  updated_at = now()
where id = '23000000-0000-4000-8000-000000000012';
