-- Seed evidence-based practical assessments across the current training library.

update public.training_assessments
set rubric = '[{"id":"evidence","label":"Evidence accuracy","weight":20,"description":"Uses the supplied fictional records accurately, distinguishes verified facts from assumptions, and does not invent missing information."},{"id":"prioritization","label":"Prioritization and judgment","weight":15,"description":"Orders work by urgency, dependency, customer or business impact, and the authority available to the VA."},{"id":"execution","label":"Workflow execution","weight":20,"description":"Produces usable work outputs, follows the requested workflow, and handles exceptions instead of only describing general best practice."},{"id":"boundaries","label":"Professional boundaries and safety","weight":20,"description":"Protects privacy, security, financial or regulatory boundaries and escalates decisions that require authorized or specialist judgment.","hard_fail":true},{"id":"qa","label":"QA and documentation","weight":15,"description":"Checks source data, records changes and exceptions, preserves auditability, and defines how work should be verified before closure."},{"id":"handoff","label":"Communication and handoff","weight":10,"description":"Writes clear client, customer, team, or reviewer communications with owners, next actions, deadlines, and unresolved risks."}]'::jsonb, updated_at = now()
where assessment_type = 'practical';

update public.training_assessments a
set resource_pack = '[{"id":"inbox","title":"Morning inbox and task queue","kind":"brief","content":"08:05 password-reset alert not requested by client\n08:12 customer asks to move tomorrow 10:00 appointment\n08:20 supplier says invoice INV-418 is overdue\n08:25 client writes: ''Supplier call 10 AM Thursday''\nCRM cleanup: 60 rows due 17:00\nResearch: find 3 replacement suppliers with source links"},{"id":"crm","title":"CRM cleanup sample","kind":"csv","content":"company,contact,status,owner\nAcme Co,Jane Cruz,Followup,\nACME CO.,Jane Cruz,follow up,Erin\nNorthstar Ltd,Mark Lee,FU,Paolo\nBrightWorks,,New,\nNorth Star Ltd,Mark Lee,Contacted,Paolo"},{"id":"rules","title":"Client working rules","kind":"policy","content":"Never reset passwords from an unsolicited email. Confirm time zone when a meeting request is ambiguous. Supplier payments require owner approval. Bulk spreadsheet cleanup must be recoverable. Research must include source links and checked date."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'virtual-assistant-foundations';

update public.training_assessments a
set resource_pack = '[{"id":"leads","title":"Lead and property queue","kind":"csv","content":"lead,property,status,issue\nA. Reyes,12 Palm St,New,Viewing requested\nB. Cruz,8 Lake Rd,Active,Seller changed bedroom count\nC. Lim,44 Hill Ave,Active,Vendor asks for price concession\nD. Tan,17 Oak Dr,Active,Maintenance quote exceeds approval limit"},{"id":"listing","title":"Listing source record","kind":"document","content":"12 Palm St\nApproved bedrooms: 3\nApproved bathrooms: 2\nParking: 1 car\nSeller-approved asking price: 780000\nPhoto folder: /Listings/12-Palm/Approved\nDo not publish unverified seller changes until source record is updated by authorized staff."},{"id":"authority","title":"Real-estate authority matrix","kind":"policy","content":"VA may schedule, update CRM, prepare listing assets, collect documents and draft routine messages. VA may not negotiate price, make legal/licensing decisions, give tenancy advice, approve concessions, or change material property facts without authorized confirmation."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'real-estate-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"queue","title":"Clinic administration queue","kind":"brief","content":"Patient A: referral missing provider number\nPatient B: asks whether chest pain needs urgent treatment\nPatient C: reschedule due tomorrow\nPatient D: invoice rejected by payer\nPatient E: email sent to wrong clinic address with attachment\nPatient F: asks what medication side effect means"},{"id":"intake","title":"Patient intake extract","kind":"csv","content":"patient,dob,referral,consent,appointment\nA.S.,1989-02-14,missing,yes,2026-09-25\nB.J.,1976-11-03,yes,yes,2026-09-24\nC.R.,1998-06-30,yes,no,2026-09-27"},{"id":"scope","title":"Practice administration boundaries","kind":"policy","content":"Administrative staff may schedule, confirm demographics, route referrals, send approved reminders, prepare billing exceptions and document patient wording. Clinical urgency, diagnosis, treatment, medication, coding, medical necessity and coverage decisions require authorized clinical or billing staff."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'medical-healthcare-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"inbox","title":"Executive priority queue","kind":"brief","content":"Board chair requests investor deck by 18:00\nFounder calendar has overlapping investor and candidate interviews\nVendor emails new bank details and asks for urgent payment\nFlight cancellation affects tomorrow 09:00 meeting\nRevenue slide says 4.8M but finance note says 4.5M\nPrivate candidate asks whether interview is confidential"},{"id":"calendar","title":"Calendar constraints","kind":"csv","content":"event,start,end,priority\nInvestor call,14:00,15:00,high\nCandidate interview,14:30,15:30,high\nFinance review,16:00,16:30,critical\nAirport transfer,17:00,18:00,high"},{"id":"delegation","title":"Executive delegation rules","kind":"policy","content":"EA may draft, coordinate, research and prepare options. Payments, material investor statements, confidential personnel disclosures and major schedule trade-offs require executive or designated owner approval. Never treat email bank-detail changes as verified."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'executive-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"launch","title":"Campaign launch board","kind":"csv","content":"asset,status,owner,issue\nLanding page,Ready,Web,Booking link fails\nEmail 1,Draft,Marketing,Old price in footer\nCarousel,Approved,Design,None\nCRM segment,Ready,Ops,Includes inactive customers\nPaid ad,Draft,Founder,Claim not approved"},{"id":"brief","title":"Campaign objective and brief","kind":"document","content":"Goal: qualified discovery bookings\nAudience: Australian service businesses with 5-50 staff\nOffer: free 30-minute discovery call\nPrimary CTA: Book discovery\nApproved proof points: 48-hour shortlist target, human-vetted candidates\nDo not claim guaranteed savings or guaranteed hires."},{"id":"qa","title":"Launch QA checklist","kind":"checklist","content":"Check final URL, mobile form, tracking, approved pricing, legal/claim approval, audience exclusions, CRM routing, email suppression, UTM naming, owner for live monitoring, rollback/stop-launch condition."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'marketing-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"ap","title":"Accounts payable exception file","kind":"csv","content":"supplier,invoice,amount,status,issue\nNorth Tools,NT-884,2450,Ready,New bank details in email\nNorth Tools,NT-884,2450,Imported,Possible duplicate\nGreen Office,GO-119,680,Ready,None\nMetro IT,MI-554,1320,Hold,PO missing"},{"id":"bank","title":"Bank reconciliation exceptions","kind":"csv","content":"date,description,amount,book_record\n2026-09-19,Cloud subscription,89.00,None\n2026-09-20,Customer deposit,2200.00,Unmatched\n2026-09-21,Transfer to savings,5000.00,Possible internal transfer"},{"id":"controls","title":"Finance control rules","kind":"policy","content":"VA may prepare bills, evidence, payment batches, AR follow-up and reconciliation exceptions. New supplier bank details require independent verification. VA must not force balances, guess tax/account codes, authorize payments, lodge tax/BAS, or provide accounting/payroll advice."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'bookkeeping-administration';

update public.training_assessments a
set resource_pack = '[{"id":"prospects","title":"Prospect list extract","kind":"csv","content":"company,contact,role,source,status\nAlpha Services,J. King,Ops Manager,LinkedIn,New\nAlpha Services,J. King,Ops Manager,Import,Duplicate\nBeacon Co,L. Tran,Founder,,New\nCoreBuild,M. Diaz,GM,Conference,Do not contact\nDelta Works,R. Singh,Assistant,Website,New"},{"id":"replies","title":"Outreach reply queue","kind":"document","content":"1 Interested, asks for next week\n2 Referral to operations director\n3 Not interested\n4 Opt out immediately\n5 Asks price before call\n6 Complains: ''How did you get my email?''\n7 Interested but not decision maker"},{"id":"sales_rules","title":"Sales support rules","kind":"policy","content":"Respect suppression and opt-out records. Record lead source. Do not fabricate personalization, negotiate terms, promise results, or mark a prospect qualified outside approved criteria. Sensitive complaints about data sourcing must be escalated."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'sales-lead-generation-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"orders","title":"Order exception queue","kind":"csv","content":"order,sku,status,issue\n#4102,LAMP-BLK,Paid,SKU out of stock\n#4103,CHAIR-OAK,Shipped,Customer requests address change\n#4104,RUG-200,Delivered,Customer says not received\n#4105,DESK-WHT,Paid,Platform fraud review"},{"id":"catalog","title":"Catalog QA extract","kind":"csv","content":"sku,title,price,inventory,url\nLAMP-BLK,Black Lamp,89,0,/lamp-black\nLAMP-BLK,Matte Black Lamp,89,14,/black-lamp\nRUG-200,Rug 200cm,149,6,/rug-200\nDESK-WHT,White Desk,399,2,/desk-white"},{"id":"policy","title":"Store exception policy","kind":"policy","content":"Address changes after shipment require carrier workflow. Refunds outside standard policy require manager approval. Fraud-review orders must not be manually forced through. Inventory source of truth is the ERP, not marketplace cached counts."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'ecommerce-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"calendar","title":"Content calendar","kind":"csv","content":"date,channel,asset,status,issue\nFri,Instagram,Carousel,Approved,Old price in slide 4\nFri,Facebook,Video,Approved,None\nFri,Instagram,Reel,Draft,Claim says ''best in Australia''\nFri,Facebook,Link post,Scheduled,Links to staging"},{"id":"community","title":"Comment and DM queue","kind":"document","content":"Comment: ''I was charged twice.''\nComment: ''This ad is misleading.''\nDM: asks for refund outside policy\nDM: creator asks whether brand may use their video in paid ads\nComment: asks product availability"},{"id":"rights","title":"Publishing and UGC rules","kind":"policy","content":"Only approved claims may be published. Broken or staging links block launch. UGC may be reposted only within documented permission; paid-ad usage requires explicit rights. Customer billing complaints must move to the support workflow, not be resolved publicly."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'social-media-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"tickets","title":"Support ticket queue","kind":"csv","content":"ticket,received,issue,sla,status\nA,09:00,Duplicate charge,2h,New\nB,09:03,Installer late for 09:30 booking,1h,New\nC,09:05,Compatibility question not in KB,4h,New\nD,09:10,Refund outside policy,4h,New\nE,09:12,Password reset from mismatched email,1h,New"},{"id":"kb","title":"Knowledge-base excerpts","kind":"document","content":"Refunds: standard window 30 days unless manager exception is documented.\nAccount security: do not disclose or change account access when identity signals conflict.\nCompatibility: if model is absent from approved matrix, escalate to product specialist.\nInstaller delay: confirm dispatch status before promising arrival time."},{"id":"qa","title":"Support QA standard","kind":"checklist","content":"Confirm customer and issue. Use approved policy. Record troubleshooting. Avoid unsupported promises. Protect account/security data. Set owner and next checkpoint. Use internal notes for evidence and customer reply for clear next steps."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'customer-support-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"gsc","title":"Search Console export","kind":"csv","content":"page,query,clicks,impressions,ctr,position\n/services/bookkeeping,bookkeeping services,42,6200,0.68%,8.4\n/blog/small-business-bookkeeping,small business bookkeeping services,31,5100,0.61%,7.9\n/services/payroll,payroll outsourcing,18,2400,0.75%,11.2\n/tax-guide,small business tax guide,54,3100,1.74%,5.2"},{"id":"crawl","title":"Crawler issue export","kind":"csv","content":"url,status,indexability,canonical,sitemap,issue\n/old-bookkeeping,301,Non-indexable,/services/bookkeeping,yes,Redirect in sitemap\n/thank-you,200,Noindex,/thank-you,yes,Noindex in sitemap\n/services/bookkeeping,200,Indexable,/services/bookkeeping,yes,Weak internal links\n/blog/small-business-bookkeeping,200,Indexable,/blog/small-business-bookkeeping,yes,Intent overlap"},{"id":"pages","title":"Page and keyword evidence","kind":"document","content":"Bookkeeping service page: commercial service intent, title ''Bookkeeping Services for Small Business''.\nArticle: informational guide but H1 ''Small Business Bookkeeping Services''.\nKeyword file: bookkeeping services 2400 volume; small business bookkeeping 1900; outsourced bookkeeping 720.\nClient goal: qualified bookkeeping enquiries, not traffic alone."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'seo-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"incidents","title":"Operations exception queue","kind":"csv","content":"issue,age,impact,owner\n14 Friday jobs still open,3d,Customer delays,Dispatch\nMaterials delayed for 6 Tuesday jobs,1d,Schedule risk,Procurement\n5 duplicate CRM records,2d,Reporting risk,Ops\nBooking automation not creating tasks,8h,Lead follow-up risk,Systems"},{"id":"kpi","title":"Weekly KPI extract","kind":"csv","content":"week,on_time_completion,rework,open_backlog\nW35,93%,4%,18\nW36,91%,5%,21\nW37,88%,5%,25\nW38,79%,9%,34"},{"id":"process","title":"Booking process notes","kind":"document","content":"Web form -> CRM lead -> automation creates follow-up task -> coordinator books job -> dispatch assigns technician. Since 00:40 today, CRM leads still arrive but no follow-up task is created. No approved automation change is documented."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'operations-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"plan","title":"Project status extract","kind":"csv","content":"workstream,status,owner,dependency\nDesign,Done,Design,None\nDevelopment,60%,Dev,Approved design\nData migration,Blocked,Ops,Client spreadsheet 4 days late\nQA,Not started,QA,Development + data migration\nOnboarding video,Requested,Marketing,Not in baseline scope"},{"id":"constraints","title":"Project constraints","kind":"document","content":"Target launch: 3 weeks\nQA duration: 3 business days\nOne developer unavailable for 2 days next week\nFounder requests original launch date\nScope baseline does not include onboarding video"},{"id":"governance","title":"Decision rules","kind":"policy","content":"VA/project coordinator may maintain plan, risks, decisions and stakeholder updates. Scope, budget, launch-date trade-offs and resource commitments require project sponsor/owner approval. Unapproved requests must be logged as change requests."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'project-management-for-virtual-assistants';

update public.training_assessments a
set resource_pack = '[{"id":"inputs","title":"Payroll input exceptions","kind":"csv","content":"employee,issue,status\nE014,Timesheet missing manager approval,Hold\nE021,New starter tax form missing,Hold\nE027,New bank details received by email,Verify independently\nE031,Backdated pay increase,Approval pending\nE038,4 hours missing after draft payroll,Investigate"},{"id":"variance","title":"Payroll variance report","kind":"csv","content":"category,prior,current,change\nBase pay,84200,84550,+0.4%\nOvertime,6200,11800,+90.3%\nBonus,0,4200,new\nAllowances,3100,3250,+4.8%\nTotal,93500,103800,+11.0%"},{"id":"controls","title":"Payroll control matrix","kind":"policy","content":"VA prepares and validates inputs. Payroll specialist owns statutory treatment. Manager approvals required for timesheets and pay changes. Bank-detail changes require independent verification. Final payroll approval and payment authorization are separate from preparation."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'payroll-administration';

update public.training_assessments a
set resource_pack = '[{"id":"portfolio","title":"Multi-property operations board","kind":"csv","content":"property,next_event,issue\nA,Checkout 10:00 / check-in 15:00,Damaged bedside lamp\nB,Guest in stay,Locked out 21:40\nC,Inquiry,Requests 25% discount; approved max 10%\nD,Open on channel,Owner block exists in PMS"},{"id":"turnover","title":"Turnover checklist","kind":"checklist","content":"Cleaner completion photo set\nLinen count\nConsumables restock\nDamage note with photos\nMaintenance escalation\nReady-for-arrival confirmation\nAccess-code verification\nNo guest personal data in vendor chat"},{"id":"owner_rules","title":"Owner commercial and incident rules","kind":"policy","content":"Long-stay discount authority: up to 10%. Any larger concession requires owner approval. Lockouts use approved locksmith/on-call process. Calendar source of truth is PMS. Damage claims require evidence and manager review before contacting guest about charges."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'airbnb-short-term-rental-virtual-assistant';

update public.training_assessments a
set resource_pack = '[{"id":"queue","title":"Australian client queue","kind":"brief","content":"Melbourne client: supplier invoice with unclear GST treatment; Perth appointment request; customer refund request; spreadsheet contains unnecessary identity data; overdue document request; manager needs end-of-day update."},{"id":"timezones","title":"Time-zone reference exercise","kind":"dataset","content":"Client HQ: Melbourne\nCustomer: Perth\nVA: Philippines\nMeeting request: ''10:00 tomorrow''\nLearner must identify what needs explicit time-zone confirmation rather than assuming local time."},{"id":"boundaries","title":"Australian VA working boundaries","kind":"policy","content":"Use current client-approved finance, privacy and employment processes. Do not infer GST, tax, payroll, legal or regulatory treatment. Record effective dates when a rule is country-specific."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'australian-va-fundamentals';

update public.training_assessments a
set resource_pack = '[{"id":"jobs","title":"Trades dispatch queue","kind":"csv","content":"job,suburb,request,status\nJ101,Richmond,Active water leak,Unscheduled\nJ102,Carlton,Breaker keeps tripping,Unscheduled\nJ103,Footscray,Hot-water service,Booked 13:00\nJ104,Southbank,Quote follow-up,Waiting approval\nJ105,Brunswick,Part unavailable,Booked tomorrow"},{"id":"dispatch","title":"Dispatch constraints","kind":"document","content":"Tech A: plumbing only, available 09:00-15:00\nTech B: electrical only, available 10:30-17:00\nTech C: mixed maintenance, fully booked\nUrgency categories must come from approved business rules; VA does not diagnose safety/technical cause."},{"id":"authority","title":"Trades admin authority","kind":"policy","content":"VA may create jobs, schedule within approved rules, track quotes, coordinate parts and draft updates. Technical diagnosis, electrical/gas/plumbing safety judgments, quote negotiation and spend above approval thresholds stay with qualified staff/owner."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'australian-trades-administration';

update public.training_assessments a
set resource_pack = '[{"id":"jobs","title":"ServiceM8 job data exercise","kind":"csv","content":"client,job,status,issue\nBright Home,J-201,New,Duplicate client record\nMetro Retail,J-202,New,Urgent unscheduled request\nCedar Co,J-203,Quote,Customer asks for discount\nNorth Clinic,J-204,Completed,Return visit required\nLake Cafe,J-205,Invoiced,Payment mismatch"},{"id":"automation","title":"Automation incident","kind":"document","content":"Reminder automation is sending ''technician arriving today'' one day early. Last workflow change was undocumented. Learner must stop/route the issue safely, preserve evidence and avoid changing business rules without approval."},{"id":"scope","title":"Software vs business authority","kind":"policy","content":"ServiceM8 can enable workflow actions; software capability does not grant commercial, technical, accounting or safety authority. Follow current official documentation and the client''s configured process."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'servicem8-for-virtual-assistants';

update public.training_assessments a
set resource_pack = '[{"id":"queue","title":"Allied-health practice queue","kind":"brief","content":"Referral received at wrong inbox; new patient missing consent form; practitioner double-booked; recall reason unclear; third-party invoice rejected; patient asks whether worsening symptoms require urgent treatment."},{"id":"records","title":"Practice record extract","kind":"csv","content":"patient,referral,consent,appointment,billing\nP01,yes,missing,2026-09-25,private\nP02,missing,yes,2026-09-24,third-party\nP03,yes,yes,double-booked,private"},{"id":"scope","title":"Allied-health admin boundaries","kind":"policy","content":"Administrative staff manage intake, referrals, scheduling, recalls, routine messages and billing exceptions. Clinical urgency, diagnosis, treatment, funding eligibility and legal/privacy interpretation stay with authorized practitioners or practice leadership."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'australian-allied-health-administration';

update public.training_assessments a
set resource_pack = '[{"id":"records","title":"Cliniko practice data exercise","kind":"csv","content":"patient,issue\nP01,Possible duplicate record\nP02,Reminder not received\nP03,Appointment rescheduled but old note remains\nP04,Invoice/payment mismatch\nStaff-New,Role appears over-permissioned"},{"id":"workflow","title":"Practice workflow brief","kind":"document","content":"Practice uses Cliniko for patient records, appointments, reminders, invoices and payments. New staff should receive minimum required access. Clinical notes are not edited by admin unless the practice has an explicit authorized workflow."},{"id":"qa","title":"Cliniko QA checklist","kind":"checklist","content":"Confirm patient identity before merge/change. Check appointment status and reminder history. Reconcile invoice/payment evidence. Review user role against job need. Escalate clinical content and permission uncertainty."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'cliniko-for-virtual-assistants';

update public.training_assessments a
set resource_pack = '[{"id":"finance","title":"Australian finance-admin queue","kind":"csv","content":"item,status,issue\nBill A,Imported,Possible duplicate\nBill B,Ready,Supplier bank detail changed\nInvoice C,Overdue,Customer disputes amount\nBank line 1,Unmatched,Unknown expense\nBank line 2,Unmatched,Possible transfer\nPayroll,Pending,Overtime dispute"},{"id":"gst","title":"GST/BAS-sensitive exception sheet","kind":"csv","content":"transaction,amount,code,issue\nSoftware renewal,330,GST,Invoice missing\nImported goods,1200,GST,Classification unclear\nBank fee,45,GST,Unexpected code"},{"id":"scope","title":"Australian bookkeeping boundary","kind":"policy","content":"VA may prepare source documents, AP/AR, reconciliation evidence and draft reports. GST/BAS treatment, lodgement, tax advice, accounting adjustments and payroll/statutory judgments require authorized qualified review."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'australian-bookkeeping-administration';

update public.training_assessments a
set resource_pack = '[{"id":"bank","title":"Xero bank reconciliation exercise","kind":"csv","content":"bank_line,suggested_match,amount,issue\nBL01,Bill-804,550.00,Exact amount\nBL02,Bill-811,828.00,Bill is 820.00\nBL03,None,95.00,Unknown subscription\nBL04,Transfer-22,5000.00,Possible internal transfer"},{"id":"monthend","title":"Xero month-end exception list","kind":"document","content":"2 overdue sales invoices; 1 duplicate-looking supplier bill; 3 unreconciled bank lines; one expense with unusual GST code; payroll adjustment request with no approval; P&L variance materially above expectation."},{"id":"controls","title":"Xero admin control rules","kind":"policy","content":"Suggested matches, bank rules and automation are not accounting authority. Use current official Xero AU documentation. GST/BAS, payroll/STP, write-offs, unusual coding and prior-period changes require authorized finance review."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'xero-workflows-for-virtual-assistants';

update public.training_assessments a
set resource_pack = '[{"id":"transactions","title":"MYOB finance-admin exercise","kind":"csv","content":"item,status,issue\nSupplier bill 901,Entered,Possible duplicate\nBank deposit 17,Unmatched,Reference missing\nCustomer invoice 440,Overdue,No follow-up note\nGST report,Draft,Large quarter-on-quarter variance\nEmployee change,Pending,Pay category question"},{"id":"product","title":"MYOB product context","kind":"document","content":"Training target: current MYOB Business workflows for sales/purchases, banking, GST reporting and payroll/admin handoff. Learner must verify interface/feature names against current official MYOB documentation rather than assume another MYOB product behaves the same."},{"id":"scope","title":"MYOB review boundary","kind":"policy","content":"VA may prepare transactions, evidence and draft reports. GST/BAS decisions, lodgement, payroll interpretation, prior-period corrections and professional accounting/tax advice remain with qualified authorized staff."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'myob-workflows-for-virtual-assistants';

update public.training_assessments a
set resource_pack = '[{"id":"provider","title":"NDIS provider admin queue","kind":"brief","content":"Participant complaint about worker conduct; unsigned service agreement change; roster/support-log mismatch; rejected payment request; late-cancellation billing question; SIL registration task references old pre-July-2026 guidance."},{"id":"records","title":"Evidence tracking sheet","kind":"csv","content":"item,status,owner\nService agreement change,Unsigned,Service manager\nSupport log,Missing 2 entries,Team lead\nClaim 118,Rejected,Finance\nSIL registration evidence,Old checklist,Compliance lead"},{"id":"scope","title":"NDIS administration boundary","kind":"policy","content":"VA tracks records, dates, evidence and approved workflows. Funding decisions, support planning, clinical judgment, safeguarding determinations, registration interpretation and compliance/legal advice stay with responsible qualified owners and current official NDIS Commission guidance."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'ndis-administration-fundamentals';

update public.training_assessments a
set resource_pack = '[{"id":"portfolio","title":"Property management queue","kind":"csv","content":"property,issue\n12 Palm St,Applicant asks whether children affect approval\n8 Lake Rd,Rent receipt mismatch\n44 Hill Ave,Urgent water leak report\n17 Oak Dr,Inspection needs reschedule\n5 River Rd,Owner emailed new bank details\n22 King St,Bond deduction request"},{"id":"jurisdiction","title":"Jurisdiction check","kind":"document","content":"Properties are in more than one Australian state/territory. Entry notices, bond handling, rent processes and tenancy rules must use the agency''s current jurisdiction-specific workflow. The VA must identify jurisdiction before acting."},{"id":"authority","title":"Property-management authority","kind":"policy","content":"VA may coordinate records, notices using approved templates, contractors, rent admin and communications. Tenant selection, legal rights, trust/bond decisions, disputed access and licensing/legal interpretation stay with authorized local property-management staff."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'property-management-administration-australia';

update public.training_assessments a
set resource_pack = '[{"id":"file","title":"Broker file checklist","kind":"csv","content":"item,status\nID documents,Complete\nPayslips,Missing latest\nBank statements,Complete\nLiving expenses,Inconsistent values\nExisting liabilities,One statement missing\nProperty contract,Complete"},{"id":"research","title":"Lender research extract","kind":"csv","content":"lender,rate,policy_note,checked_date\nLender A,5.89%,Policy A requires 2 payslips,2026-09-23\nLender B,5.79%,Policy B has tighter expense verification,2026-09-23\nLender C,6.05%,Faster stated turnaround,2026-09-23"},{"id":"scope","title":"Mortgage administration boundary","kind":"policy","content":"VA may gather documents, enter fact-find data, record lender facts, package applications and track conditions. Product recommendation, best-interests assessment, borrowing-capacity judgment, credit assistance and financial advice belong to the licensed/authorized broker."}]'::jsonb, updated_at = now()
from public.training_courses c
where a.course_id = c.id and c.slug = 'mortgage-broking-administration-australia';

