-- Write the existing Customer Support Virtual Assistant course.
-- Content remains draft-only until reviewer metadata and explicit publication are recorded.

update public.training_courses
set
  summary = 'A practical customer support course for Virtual Assistants covering queue triage, ticket ownership, knowledge-base use, troubleshooting, refunds, complaints, service quality, CRM handoffs, and customer-support judgment.',
  estimated_minutes = 300,
  status = 'draft',
  published_at = null,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '20000000-0000-4000-8000-000000000010';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Support is an operating function, not just answering messages"},{"type":"paragraph","text":"A Customer Support Virtual Assistant helps customers move from a question or problem to the correct next step. That can happen through email, live chat, contact forms, social inboxes, phone notes, help desks, CRMs, or internal escalation channels. The tool changes, but the job is the same: understand the request, act inside the rules, leave an accurate record, and make sure the issue does not disappear."},{"type":"heading","text":"Know the channel before you answer"},{"type":"list","items":["Email usually allows more context and careful review.","Live chat rewards speed, but speed must not replace accuracy.","Social messages may be public or semi-public, so move sensitive details into an approved private channel.","Phone support may require stronger note-taking because the conversation itself is not searchable later.","Help-desk tickets are part of an operational queue, so status, owner, priority, and internal notes matter as much as the reply."]},{"type":"heading","text":"What good support produces"},{"type":"list","items":["The customer understands what happened or what happens next.","The business has a usable record of the issue.","The ticket has the correct owner and status.","Any promised follow-up has a date, task, or trigger.","Exceptions are escalated instead of hidden.","The customer is not forced to repeat information already available in the record."]},{"type":"callout","title":"Do not confuse activity with resolution","text":"Sending a reply is not the same as solving a ticket. A ticket is only truly resolved when the customer has the correct outcome or a clearly owned next step."},{"type":"scenario","title":"Three incoming channels","text":"A customer emails about a missing order, sends a Facebook message five minutes later, and opens live chat. Explain how you would recognise the duplicate contact, avoid sending three conflicting replies, and preserve one clear case history."},{"type":"heading","text":"Before you touch a queue"},{"type":"list","items":["Learn the support hours and service-level expectations.","Know refund, replacement, cancellation, and escalation boundaries.","Know which channel is the official source of truth.","Know which categories require another team such as billing, technical, logistics, or management.","Know what customer information you are allowed to view, edit, or share."]},{"type":"heading","text":"Key takeaway"},{"type":"paragraph","text":"Your value is not measured by how many messages you send. It is measured by how reliably you move customer issues to the correct outcome while protecting context, policy, and trust."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000011';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Empathy without accuracy is still bad support"},{"type":"paragraph","text":"A warm tone cannot compensate for a wrong answer. Strong support combines four things: accurate facts, clear ownership, appropriate empathy, and a next step the business can actually deliver."},{"type":"heading","text":"A useful response structure"},{"type":"steps","items":["Acknowledge the actual issue, not just the emotion.","Confirm the fact you can verify.","State what you can do now.","Explain what will happen next and who owns it.","Give a realistic timing expectation if one exists.","Ask only for information that is genuinely missing."]},{"type":"heading","text":"Avoid empty empathy"},{"type":"paragraph","text":"Phrases such as ''I completely understand your frustration'' can sound scripted when the reply does not address the problem. A better response demonstrates understanding through action: ''I can see the delivery was due yesterday and the tracking has not updated since Monday. I’m checking this with the courier now.''"},{"type":"heading","text":"Ownership does not mean overpromising"},{"type":"list","items":["Own the follow-up you are responsible for.","Do not promise a refund, replacement, discount, deadline, or technical fix outside your authority.","If another team owns the next step, tell the customer what you have sent and when you will check back.","If you cannot confirm a time, say what checkpoint you can commit to instead."]},{"type":"callout","title":"Never invent certainty to sound helpful","text":"Customers usually prefer a clear, truthful update over a confident promise that later fails."},{"type":"scenario","title":"Delayed order","text":"A customer says, ''This is ridiculous. I paid for express shipping and nothing arrived.'' The tracking page shows a carrier delay but no new delivery date. Draft a response that acknowledges the issue, states verified facts, avoids inventing a delivery promise, and gives a real next action."},{"type":"heading","text":"Quality check before sending"},{"type":"list","items":["Did I answer the customer’s actual question?","Did I make any promise the policy does not support?","Did I repeat information the customer already gave us?","Did I leave the customer with a clear next step?","Would another agent understand the case from my reply and notes?"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000012';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Triage decides what deserves attention first"},{"type":"paragraph","text":"A queue should not be worked simply from oldest to newest or newest to oldest. Priority comes from business impact, customer impact, deadline, safety, security, payment, operational dependency, and any service-level rules the client has defined."},{"type":"heading","text":"Triage in six checks"},{"type":"steps","items":["Identify the customer and account.","Identify the actual issue category.","Check whether there is an immediate deadline or material consequence.","Check whether the case is a duplicate or part of an existing ticket.","Decide whether you can handle it or it needs another owner.","Assign the correct priority, status, tags, and route."]},{"type":"heading","text":"Typical high-priority signals"},{"type":"list","items":["Account or security access problem","Payment captured incorrectly or repeated charge","Customer cannot use a critical service","Time-sensitive cancellation or appointment issue","Privacy concern or data sent to the wrong person","Safety issue","Large operational outage affecting multiple customers","Executive, legal, regulator, chargeback, or serious escalation language when the client’s policy flags it"]},{"type":"callout","title":"Priority is about consequence","text":"A customer using capital letters is not automatically more urgent than a quiet customer reporting a payment or security problem."},{"type":"scenario","title":"Morning queue","text":"You have five tickets: a password reset, a duplicate credit-card charge, a product question for next month, an angry complaint about yesterday’s late delivery, and a request to cancel an appointment starting in 90 minutes. Put them in a reasonable order and explain what client rules could change your ranking."},{"type":"heading","text":"Routing mistakes to avoid"},{"type":"list","items":["Sending a ticket to a team without enough context.","Changing the category just to get it out of your queue.","Marking urgent because the customer is impatient rather than because delay has consequence.","Creating a new ticket when an existing case already contains the history.","Assigning to a person who is off shift without a fallback plan."]},{"type":"heading","text":"Triage output"},{"type":"paragraph","text":"A well-triaged ticket should tell the next person what happened, why it matters, what has already been checked, and what action is expected from them."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000021';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Internal notes are part of the product"},{"type":"paragraph","text":"Customers see the reply, but the business depends on the internal record. Poor notes create repeated questions, duplicate work, inconsistent promises, and bad handoffs."},{"type":"heading","text":"Write notes for the next person"},{"type":"list","items":["What the customer reported","Important dates, order numbers, account references, or evidence","What you verified","What action you took","What you promised","What is still pending","Who owns the next action","When follow-up is due"]},{"type":"heading","text":"Use tags and statuses consistently"},{"type":"paragraph","text":"Tags and statuses are useful only when the team uses them the same way. Follow the client’s definitions. Do not create private meanings such as using ''pending'' for cases you simply do not want to answer yet."},{"type":"heading","text":"A practical status model"},{"type":"list","items":["Open: active work is needed from the support team.","Pending: waiting on the customer, supplier, or another external party, if that matches the client’s help-desk definition.","On hold: intentionally paused for an internal dependency or date, if supported by the tool and SOP.","Resolved: the issue has reached the intended outcome and no further support action is expected.","Closed: final administrative closure where the system distinguishes it from resolved."]},{"type":"callout","title":"Tool labels vary","text":"Zendesk, HubSpot, Intercom, Gorgias, Freshdesk, and other platforms do not always use the same status logic. Follow the client’s documented workflow instead of assuming the label means the same thing everywhere."},{"type":"scenario","title":"Bad handoff","text":"An agent leaves the note ''Customer upset. Sent to billing.'' Rewrite the note so the billing team knows the charge, what the customer claims, what evidence was checked, what the support agent already told the customer, and what billing needs to decide."},{"type":"heading","text":"Handoff rule"},{"type":"paragraph","text":"Never make another team reconstruct the whole case from a long thread if you can summarise the verified issue in a few useful lines."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000022';

update public.training_lessons
set
  content = '[{"type":"heading","text":"A knowledge base supports judgment; it does not replace it"},{"type":"paragraph","text":"Knowledge-base articles, macros, templates, SOPs, product documentation, and saved replies help support teams answer consistently. The mistake is treating them as scripts that should be pasted regardless of the customer’s actual situation."},{"type":"heading","text":"How to use a knowledge article"},{"type":"steps","items":["Identify the customer’s exact problem.","Find the article that matches the product, plan, version, region, or policy.","Check whether the article is current and approved.","Pull only the steps relevant to this customer.","Rewrite or frame the information so it answers the question clearly.","Record any mismatch between the article and what you observed."]},{"type":"heading","text":"When a saved reply becomes dangerous"},{"type":"list","items":["It contains an old price or policy.","It assumes the customer uses a feature they do not have.","It promises a time frame that changed.","It asks for information already present in the ticket.","It contains a link that no longer works.","It sounds inappropriate for a complaint, cancellation, billing dispute, or sensitive issue."]},{"type":"callout","title":"Do not make the customer translate your documentation","text":"A support reply should connect the documentation to the customer’s case. Sending a link with ''please read this'' often pushes the support work back onto the customer."},{"type":"scenario","title":"Macro mismatch","text":"The approved macro says a refund appears within five business days, but the current policy article says the time depends on the payment provider. Explain what you should do before sending either statement."},{"type":"heading","text":"Improve the knowledge base"},{"type":"list","items":["Flag repeated questions that have no article.","Report steps that no longer match the product.","Suggest clearer screenshots or examples when customers repeatedly misunderstand a step.","Record the exact customer language that could improve search keywords.","Do not edit official policy content unless you are authorised to do so."]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000031';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Troubleshooting is controlled elimination"},{"type":"paragraph","text":"A support VA often helps customers with routine setup, account, order, scheduling, or software issues. Troubleshooting should follow approved checks and stop when the issue requires technical access, specialist judgment, security intervention, or a decision outside your role."},{"type":"heading","text":"Basic troubleshooting sequence"},{"type":"steps","items":["Confirm the exact symptom in the customer’s words.","Confirm the product, account, device, order, plan, location, or workflow involved.","Check known incidents, status pages, or internal alerts when applicable.","Follow the approved diagnostic steps in order.","Record what was tried and the result.","Escalate with evidence if the issue remains unresolved."]},{"type":"heading","text":"Useful evidence"},{"type":"list","items":["Exact error message","Timestamp and time zone","Order or account reference","Browser, device, app version, or environment when relevant","Screenshots that do not expose unnecessary sensitive information","Steps already attempted","Whether the issue is reproducible","Whether other customers are affected"]},{"type":"heading","text":"Stop and escalate when"},{"type":"list","items":["The issue could involve account compromise, fraud, or unauthorised access.","The next step requires admin privileges you do not have.","The customer may lose data or money if the step is wrong.","The approved troubleshooting guide ends without resolution.","The issue requires engineering, legal, medical, financial, or other specialist judgment.","You would need to invent a workaround that has not been approved."]},{"type":"callout","title":"Do not experiment on customer accounts","text":"If a step is not in the approved process and could change or delete customer data, escalate rather than guessing."},{"type":"scenario","title":"Login failure","text":"A customer says they cannot sign in. Password reset emails are not arriving. The account exists and the email address appears correct. List the safe checks you can perform, the evidence you should collect, and the point where you would escalate."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000032';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Policy protects consistency"},{"type":"paragraph","text":"Refunds, credits, cancellations, replacements, and exceptions affect money and customer expectations. A support VA should know the approved policy and authority limit before promising an outcome."},{"type":"heading","text":"Before offering a financial remedy"},{"type":"steps","items":["Confirm the customer and transaction.","Check the applicable policy and date.","Confirm whether the request is inside the normal rule.","Check whether the customer has already received a remedy.","Identify your approval limit, if any.","If the case is outside policy, escalate with a concise summary and recommendation rather than promising the exception."]},{"type":"heading","text":"Separate fact from discretion"},{"type":"paragraph","text":"You may be able to confirm that an order arrived late. That does not automatically mean you can decide the refund amount. The verified fact and the business decision are different parts of the case."},{"type":"list","items":["Fact: order delivered two days late.","Policy: express-shipping fee may be refundable under stated conditions.","Authority: support agents can refund shipping fees up to the client’s approved limit.","Exception: customer also requests full product refund despite keeping the item.","Escalation: manager decides the out-of-policy portion."]},{"type":"callout","title":"Never promise first and seek approval later","text":"A customer promise becomes a business commitment. Get the required approval before stating that the exception will happen."},{"type":"scenario","title":"Cancellation after cutoff","text":"A customer asks to cancel a service after the stated cancellation deadline because of an emergency. Write the reply you can send before management decides whether to make an exception."},{"type":"heading","text":"Record the remedy"},{"type":"list","items":["What policy applied","Who approved the exception, if any","Amount or remedy offered","Customer acceptance","Transaction or credit reference","Any follow-up still required"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000041';

update public.training_lessons
set
  content = '[{"type":"heading","text":"De-escalation starts with control of the facts"},{"type":"paragraph","text":"An angry customer may be completely right, partly right, or reacting to incomplete information. Your first job is not to win the argument. It is to understand the verified issue, lower avoidable friction, and move toward the correct resolution."},{"type":"heading","text":"Do"},{"type":"list","items":["Let the customer explain the issue without interrupting unnecessarily.","Acknowledge the specific failure or concern you can verify.","Use calm, direct language.","Explain the next action clearly.","Set a realistic checkpoint.","Escalate threats, safety issues, privacy concerns, legal language, or serious policy exceptions under the client’s rules."]},{"type":"heading","text":"Do not"},{"type":"list","items":["Tell the customer to calm down.","Blame another team, courier, supplier, or the customer.","Argue about tone before addressing the actual issue unless abuse crosses the client’s safety policy.","Promise compensation you cannot approve.","Copy a cheerful macro into a serious complaint.","Close the ticket just because the customer stopped replying."]},{"type":"heading","text":"A useful sentence pattern"},{"type":"paragraph","text":"Use: ''I can see [verified issue]. I’ve [action taken]. The next step is [next action], and I’ll update you by [real checkpoint].'' This is more useful than a long apology with no operational commitment."},{"type":"callout","title":"Empathy does not require admitting something you cannot verify","text":"You can acknowledge the customer’s experience without inventing responsibility: ''I can see why that would be frustrating. I’m checking the booking history now.''"},{"type":"scenario","title":"Public complaint","text":"A customer posts publicly that your client ''stole my money'' after a refund delay. Explain what you would say publicly, what should move to a private channel, what evidence you would check, and what may need escalation."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000042';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Service quality needs measurable definitions"},{"type":"paragraph","text":"Support teams often track response time, resolution time, backlog, reopen rate, customer satisfaction, and service-level agreements or targets. The exact metric definitions vary by client, so never assume two dashboards measure the same thing."},{"type":"heading","text":"Know the difference"},{"type":"list","items":["First response time: how long before the customer receives the first meaningful response under the client’s definition.","Resolution time: how long until the issue reaches the defined resolved state.","Backlog: unresolved work remaining in the queue.","Reopened ticket: a case that returns to active work after being resolved or closed.","SLA or target: a service commitment or internal goal tied to specific conditions."]},{"type":"heading","text":"How to work an SLA queue"},{"type":"steps","items":["Identify tickets closest to breach.","Check whether the priority and SLA are correct.","Work cases you can resolve immediately.","Escalate blocked high-risk cases early.","Do not send meaningless replies only to stop the response timer.","Update status accurately so reporting reflects reality."]},{"type":"callout","title":"Gaming the metric hurts the customer","text":"A fast empty reply can improve one dashboard number while making the support experience worse. The correct goal is useful, timely progress."},{"type":"scenario","title":"Backlog spike","text":"The queue normally has 40 open tickets but now has 180 after a product issue. Describe how you would separate outage-related tickets, urgent account issues, routine questions, and duplicates so the team can recover without treating every ticket the same."},{"type":"heading","text":"Useful backlog report"},{"type":"list","items":["Total open by priority","Oldest unresolved tickets","Tickets at risk of SLA breach","Top issue categories","Blocked cases by owning team","Duplicate or incident-related volume","Actions needed from management"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000051';

update public.training_lessons
set
  content = '[{"type":"heading","text":"QA should improve decisions, not punish agents"},{"type":"paragraph","text":"Support quality assurance reviews how consistently tickets follow the client’s standards. A useful QA process looks at accuracy, policy compliance, tone, ownership, documentation, privacy, and the quality of the resolution."},{"type":"heading","text":"A practical review rubric"},{"type":"list","items":["Accuracy: were facts and policy correct?","Resolution: did the reply move the issue toward the correct outcome?","Ownership: were follow-ups and dependencies clearly owned?","Communication: was the message clear and appropriate to the situation?","Documentation: could another agent understand the case?","Policy: were refund, privacy, security, and escalation rules followed?","Efficiency: did the agent avoid unnecessary back-and-forth?"]},{"type":"heading","text":"Write coaching notes that are actionable"},{"type":"paragraph","text":"Weak coaching says ''be more empathetic''. Strong coaching says ''acknowledge the missed delivery before asking for another screenshot; the customer had already provided the tracking number in the first message.''"},{"type":"steps","items":["Quote or identify the specific behaviour.","Explain why it matters.","Show the better action or wording.","Link the relevant SOP or policy.","State whether this is a one-off correction or a repeated pattern to monitor."]},{"type":"callout","title":"Do not invent QA authority","text":"If you are asked to review tickets but not to discipline staff or change policy, keep your feedback inside the authorised scope."},{"type":"scenario","title":"QA review","text":"An agent gave the correct refund but failed to document the approval and told the customer ''we always do this'' even though it was an exception. Score the case across accuracy, policy, communication, and documentation, then write one coaching note."}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000052';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Support work often becomes CRM data"},{"type":"paragraph","text":"A customer conversation may change account status, sales opportunity, renewal risk, onboarding progress, service history, product feedback, or an internal task. The support ticket and CRM should not tell conflicting stories."},{"type":"heading","text":"What belongs in a CRM handoff"},{"type":"list","items":["Verified customer or company","Issue summary","Relevant product, order, plan, or service","Business impact","Actions already taken","Customer sentiment when operationally useful","Promise or deadline already given","Next owner","Follow-up date","Link to source ticket or conversation"]},{"type":"heading","text":"Cross-team handoff standard"},{"type":"steps","items":["State why the other team is needed.","Summarise the verified facts.","Remove irrelevant emotional commentary.","State what the customer has already been told.","State what decision or action is required.","Keep ownership until the handoff is actually accepted when the client’s process requires it."]},{"type":"callout","title":"Forwarding is not a handoff","text":"Sending a ticket to another team without a summary, owner, or required action creates hidden work and delayed customers."},{"type":"scenario","title":"Support to sales","text":"A customer asks whether they can upgrade to a larger plan after repeatedly hitting limits. Support can explain current-plan limits but pricing requires sales. Write the CRM note and handoff so sales knows the customer’s current plan, issue, urgency, and what support already explained."},{"type":"heading","text":"Common handoff failures"},{"type":"list","items":["Duplicate tasks in two systems with different owners","No deadline","No link back to the source conversation","Customer promised something the receiving team cannot deliver","Internal opinion recorded as if it were customer fact","Sensitive data copied into a system that does not need it"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000061';

update public.training_lessons
set
  content = '[{"type":"heading","text":"Final composite support simulation"},{"type":"paragraph","text":"This simulation combines queue triage, customer communication, policy, troubleshooting, notes, and handoffs. The fictional company is designed from common support patterns rather than any single real client."},{"type":"scenario","title":"Northstar Home Co.","text":"At 9:00 AM you open the support queue for Northstar Home Co., a fictional e-commerce and installation business. Ticket A says a customer was charged twice overnight. Ticket B is an angry message about an installer who has not arrived for a 9:30 AM appointment. Ticket C asks whether a product will work with an older model the knowledge base does not mention. Ticket D requests a refund outside the standard return period and says a manager approved it by phone, but there is no note. Ticket E is a password-reset request from an email address that does not match the account."},{"type":"heading","text":"Part 1: Triage"},{"type":"steps","items":["Rank the five tickets and explain your reasoning.","Identify duplicates or security checks you would look for.","Assign the likely owner or escalation path for each case.","State what you can safely do before receiving additional approval."]},{"type":"heading","text":"Part 2: Customer responses"},{"type":"list","items":["Draft the first response to the duplicate-charge customer.","Draft the first response to the missed-appointment customer.","Draft the response to the out-of-policy refund request without denying or promising the exception.","Explain why the password-reset request requires controlled verification rather than simply changing the account email."]},{"type":"heading","text":"Part 3: Internal records"},{"type":"steps","items":["Write an internal note for the installer issue.","Write a billing handoff for the duplicate charge.","Write a product/technical escalation for the compatibility question.","Record the missing evidence for the claimed manager-approved refund.","Set the next checkpoint for every unresolved case."]},{"type":"callout","title":"Assessment standard","text":"The best answer is not the one that sounds most apologetic. It is the one that protects the customer, follows policy, records evidence, assigns ownership, and moves each issue to a safe next step."},{"type":"heading","text":"Self-review"},{"type":"list","items":["Did you prioritise by consequence rather than emotion?","Did you avoid promises outside your authority?","Did you preserve customer context?","Did every unresolved case have an owner and checkpoint?","Did you treat security and payment issues carefully?","Could another support agent continue every case from your notes?"]}]'::jsonb,
  is_published = false,
  last_reviewed_at = null,
  reviewed_by = null,
  content_version = greatest(content_version, 1),
  updated_at = now()
where id = '22000010-0000-4000-8000-000000000062';

update public.training_assessments
set
  instructions = 'Complete the Northstar Home Co. composite customer-support simulation. Triage the queue, draft customer replies, apply policy boundaries, identify troubleshooting and security escalations, write CRM/internal notes, and hand unresolved cases to the correct owner with a clear checkpoint. The assessment tests judgment and work output rather than support trivia.',
  is_published = false,
  updated_at = now()
where id = '23000000-0000-4000-8000-000000000010';
