import { ArrowRight, Building2, CheckCircle2, DollarSign, Target } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { completeClientOnboardingAction } from "@/app/actions/profile";

export default async function ClientOnboardingPage(){
  const {user,profile}=await requireRole("client");
  const supabase=await createClient();
  const {data:company}=await supabase.from("client_profiles").select("*").eq("user_id",user.id).maybeSingle();
  return <>
    <div className="onboarding-hero card"><span className="badge badge-success">Welcome to your hiring workspace</span><h1>Let’s get your hiring request started.</h1><p>Share the essentials in a few minutes. You can describe the help you need in your own words—we’ll guide the rest.</p><div className="onboarding-outcomes"><span><CheckCircle2 size={15}/> Create a hiring brief</span><span><CheckCircle2 size={15}/> Recruiter matches candidates</span><span><CheckCircle2 size={15}/> You review and hire</span></div></div>
    <form action={completeClientOnboardingAction} className="client-onboarding-grid">
      <section className="card onboarding-step-card"><div className="onboarding-step-icon"><Building2 size={20}/></div><span className="small muted">Step 1</span><h2>Your company</h2><div className="field"><label>Your name</label><input name="full_name" required minLength={2} maxLength={100} defaultValue={profile.full_name||""}/></div><div className="field"><label>Company name</label><input name="company_name" required minLength={2} maxLength={140} defaultValue={company?.company_name||""}/></div><div className="field"><label>Timezone</label><input name="timezone" required placeholder="Australia/Sydney, US Eastern, GMT+8" defaultValue={company?.timezone||""}/></div></section>
      <section className="card onboarding-step-card"><div className="onboarding-step-icon"><Target size={20}/></div><span className="small muted">Step 2</span><h2>What do you need help with?</h2><p className="small muted">Choose a few common areas for inspiration, then tell us what success looks like. No job-description writing required.</p><div className="pill-list onboarding-ideas"><span>Admin & scheduling</span><span>Customer support</span><span>Sales / lead generation</span><span>Social media</span><span>Bookkeeping</span><span>E-commerce</span></div><div className="field"><label>What would you like this person to handle?</label><textarea name="hiring_needs" required minLength={20} maxLength={1200} defaultValue={company?.hiring_needs||company?.hiring_notes||""} placeholder="Example: I need help managing my Shopify store, answering customer emails, and keeping product listings current—about 30 hours a week."/><span className="small muted">We’ll turn this into a structured hiring brief you can review before recruiting starts.</span></div><div className="field"><label>Company or team location</label><input name="location" defaultValue={company?.location||""} placeholder="Sydney, Australia"/></div></section>
      <section className="card onboarding-step-card"><div className="onboarding-step-icon"><DollarSign size={20}/></div><span className="small muted">Step 3</span><h2>Budget</h2><div className="grid-2"><div className="field"><label>Min USD/hr</label><input type="number" name="budget_min" min="5" step="0.5" required defaultValue={company?.budget_min||5}/></div><div className="field"><label>Max USD/hr</label><input type="number" name="budget_max" min="5" step="0.5" required defaultValue={company?.budget_max||10}/></div></div><p className="small muted">This is planning context, not a public offer. Each job post can use its own rate range.</p></section>
      <div className="card onboarding-finish"><div><strong>Ready to create your hiring brief?</strong><p className="small muted">Save these details, then review a guided role brief before recruiting starts.</p></div><button className="btn btn-primary btn-lg" type="submit">Continue to hiring brief <ArrowRight size={17}/></button></div>
    </form>
  </>;
}
