import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { submitSkillsTestAction, submitVettingVideoAction } from "@/app/actions/vetting";
import { getVettingReadiness, vettingStatusLabel } from "@/lib/vetting";
import { dateShort } from "@/lib/format";
import { VETTING_PROFILE_MIN } from "@/lib/constants";

export default async function VaVettingPage(){
  const {user}=await requireRole("va");
  const admin=createAdminClient();
  const [{data:va},{data:accountProfile},{data:vetting},{data:scorecard}]=await Promise.all([
    admin.from("va_profiles").select("*").eq("user_id",user.id).single(),
    admin.from("profiles").select("avatar_url").eq("id",user.id).single(),
    admin.from("va_vetting").select("*").eq("va_id",user.id).single(),
    admin.from("vetting_scorecards").select("*").eq("va_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle()
  ]);
  const {data:test}=va?.primary_category?await admin.from("skills_tests").select("*").eq("category",va.primary_category).eq("active",true).maybeSingle():{data:null};
  const {data:attempt}=test?await admin.from("va_test_attempts").select("*,skills_tests(title,category,passing_score)").eq("va_id",user.id).eq("test_id",test.id).order("submitted_at",{ascending:false}).limit(1).maybeSingle():{data:null};
  const testScore=attempt?.final_score??attempt?.auto_score??null;
  const readiness=getVettingReadiness(va,vetting,testScore,scorecard?.total_score??null,accountProfile?.avatar_url);
  const questions=Array.isArray(test?.questions)?test.questions:[];
  const profileReady=readiness.completion.score>=VETTING_PROFILE_MIN&&Boolean(va?.resume_path);
  const testPassed=typeof testScore==="number"&&testScore>=(test?.passing_score??70);
  return <>
    <div className="page-head"><div><h1>Become a verified VA</h1><p>Complete each screening step to become eligible for recruiter matching and public discovery.</p></div><span className={`badge ${["approved","bench"].includes(vetting?.stage||"")?"badge-success":"badge-warning"}`}>{vettingStatusLabel(vetting?.stage)}</span></div>
    {vetting?.stage==="recruiter_review"?<div className="info-banner"><strong>Your recruiter is reviewing your application.</strong> No action is needed right now. Reviews are usually completed within 1–3 business days, and we’ll notify you when there is an update.</div>:null}
    <div className="stats"><div className="stat-card"><span className="small muted">Vetting progress</span><strong>{readiness.score}%</strong></div><div className="stat-card"><span className="small muted">Profile strength</span><strong>{readiness.completion.score}%</strong></div><div className="stat-card"><span className="small muted">Skills test</span><strong>{testScore!=null?`${testScore}%`:"Not taken"}</strong></div><div className="stat-card"><span className="small muted">Recruiter score</span><strong>{scorecard?.total_score?`${scorecard.total_score}%`:"Pending"}</strong></div></div>
    <div className="dashboard-grid"><div className="stack">
      <section className="card" id="status"><div className="row-between"><div><h3 style={{margin:0}}>Your progress: {readiness.items.filter((item)=>item.done).length} / {readiness.items.length}</h3><p className="small muted" style={{margin:"5px 0 0"}}>Profile, category test, video intro, recruiter scorecard, then final approval.</p></div></div><div className="checklist" style={{marginTop:12}}>{readiness.items.map((item)=><Link className="check-item" href={item.href} key={item.label}><span className={`check-icon ${item.done?"done":""}`}>{item.done?"✓":""}</span><span><strong>{item.label}</strong></span><span className="small muted">{item.done?"Done":vetting?.stage==="recruiter_review"?"Recruiter review":"Next"}</span></Link>)}</div></section>
      <section className="card" id="skills-test"><div className="row-between"><div><h3 style={{margin:0}}>Category skills test</h3><p className="small muted" style={{margin:"5px 0 0"}}>{va?.primary_category?`Screening for ${va.primary_category}.`:"Choose your primary category first."}</p></div>{attempt?<span className={`badge ${testPassed?"badge-success":"badge-warning"}`}>{testPassed?"Passed":"Retake needed"}</span>:null}</div>
        {!va?.primary_category?<div className="empty"><p>Select a primary VA category in your profile before taking the test.</p><Link className="btn" href="/workspace/va/profile#expertise">Update profile</Link></div>:!profileReady?<div className="empty"><p>Complete at least {VETTING_PROFILE_MIN}% of your structured profile and upload your resume before taking the category test.</p><Link className="btn" href="/workspace/va/profile">Complete application profile</Link></div>:attempt&&testPassed?<div className="stack" style={{marginTop:16}}><div className="score-strip"><div><span className="small muted">Submitted</span><strong>{dateShort(attempt.submitted_at)}</strong></div><div><span className="small muted">Score</span><strong>{testScore}%</strong></div><div><span className="small muted">Passing score</span><strong>{attempt.skills_tests?.passing_score??70}%</strong></div></div><p className="small muted">Your written scenario remains visible to the recruiter as part of the review. Contact support if your primary category changes and you need a different test.</p></div>:test?<form action={submitSkillsTestAction} className="stack" style={{marginTop:18}}><div className="alert">{attempt?`Your previous score was ${testScore}%. Retake the test to reach the ${test.passing_score}% passing score. `:""}{test.instructions} Recommended time: {test.duration_minutes} minutes.</div>{questions.map((q:any,index:number)=><div className="field test-question" key={q.id}><label>{index+1}. {q.prompt}</label>{q.type==="choice"?<div className="choice-list">{(q.options||[]).map((option:string)=><label className="choice" key={option}><input type="radio" name={`q_${q.id}`} value={option} required/><span>{option}</span></label>)}</div>:<textarea name={`q_${q.id}`} required minLength={40} placeholder="Write a clear, practical response."/>}</div>)}<div><button className="btn btn-primary" type="submit">Submit skills test</button></div></form>:<div className="empty">A skills test has not been configured for this category yet.</div>}
      </section>
      <section className="card" id="video-intro"><h3>2-minute video introduction</h3><p className="muted">Introduce yourself, explain your strongest VA work, describe the clients you work best with, and give one example of a problem you solved.</p>{testPassed?<form action={submitVettingVideoAction} className="form-grid"><div className="field span-2"><label>Private video URL</label><input type="url" name="video_url" required defaultValue={vetting?.video_url||""} placeholder="https://www.loom.com/share/..."/><span className="small muted">Use Loom, Google Drive, YouTube unlisted, or another private link your recruiter can open.</span></div><div><button className="btn btn-primary" type="submit">{vetting?.video_url?"Update video":"Submit video"}</button></div></form>:<div className="empty"><p>Pass the category skills test before submitting your video introduction.</p><a className="btn" href="#skills-test">Go to skills test</a></div>}</section>
      {scorecard?<section className="card" id="review"><div className="row-between"><div><h3 style={{margin:0}}>Recruiter scorecard</h3><p className="small muted" style={{margin:"5px 0 0"}}>A consistent 5-part rubric is used for every candidate.</p></div><strong className="score-big">{scorecard.total_score}%</strong></div><div className="score-grid"><div><span>Role skills</span><strong>{scorecard.role_skills}/5</strong></div><div><span>Communication</span><strong>{scorecard.communication}/5</strong></div><div><span>Judgment</span><strong>{scorecard.judgment}/5</strong></div><div><span>Reliability</span><strong>{scorecard.reliability}/5</strong></div><div><span>Client readiness</span><strong>{scorecard.client_readiness}/5</strong></div></div><p className="small muted" style={{marginBottom:0}}>Recommendation: {scorecard.recommendation}. Final approval is handled separately from the recruiter review. Your status will update here when the final decision is recorded.</p></section>:null}
    </div><aside className="profile-sidebar"><div className="card"><h3>What clients see</h3><p className="small muted">Only VAs who pass vetting can appear in the public talent directory. Your private test answers, recruiter notes, video URL, contact details, and uploaded resume are never public.</p></div></aside></div>
  </>;
}
