import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { dateShort } from "@/lib/format";
import { matchLabel } from "@/lib/matching";
import { respondToInviteAction, withdrawApplicationAction } from "@/app/actions/applications";
import { jobPublicHref } from "@/lib/public-routing";

export default async function VaApplicationsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const params=await searchParams;const {user}=await requireRole("va");const supabase=await createClient();const [{data:apps},{data:invites}]=await Promise.all([supabase.from("applications").select("*,jobs(id,slug,title,company_name,status)").eq("va_id",user.id).order("applied_at",{ascending:false}),supabase.from("job_invites").select("*,jobs(id,slug,title,company_name,hours_per_week,min_hourly_rate)").eq("va_id",user.id).order("created_at",{ascending:false})]);return <>
  {params.applied?<div className="success-banner" role="status"><CheckCircle2 size={17}/> Application sent. The client can now review your vetted profile and application note.</div>:null}{params.invite?<div className="success-banner" role="status">Invitation {params.invite}. {params.invite==="accepted"?"If this created a new application, it now appears below with a private conversation.":"The client has been updated."}</div>:null}
  <div className="page-head"><div><h1>Applications</h1><p>Track applications, invitations, and interview progress without losing the conversation.</p></div></div>
  {(invites||[]).some((x:any)=>x.status==="pending")?<div className="card" style={{marginBottom:18}}><h3>Client invitations</h3><p className="small muted">Review the role before accepting. Accepting creates an application and conversation if one does not already exist.</p><div className="stack">{(invites||[]).filter((x:any)=>x.status==="pending").map((i:any)=><div className="card row-between wrap" key={i.id}><div><strong>{i.jobs?.title}</strong><div className="small muted">{i.jobs?.company_name||"Client"}</div>{i.note?<p className="small" style={{marginBottom:0}}>{i.note}</p>:null}</div><div className="row"><form action={respondToInviteAction}><input type="hidden" name="invite_id" value={i.id}/><button className="btn btn-primary btn-sm" name="decision" value="accepted">Accept</button></form><form action={respondToInviteAction}><input type="hidden" name="invite_id" value={i.id}/><button className="btn btn-sm" name="decision" value="declined">Decline</button></form></div></div>)}</div></div>:null}
  <div className="table-wrap responsive-table">{apps?.length?<table><thead><tr><th>Job</th><th>Fit</th><th>Status</th><th>Applied</th><th></th></tr></thead><tbody>{apps.map((a:any)=>{const score=Number(a.match_score||0);return <tr key={a.id}><td data-label="Job"><strong>{a.jobs?.title}</strong><div className="small muted">{a.jobs?.company_name||"Confidential client"}</div></td><td data-label="Fit"><strong>{matchLabel(score)}</strong><div className="small muted">{score}/100</div></td><td data-label="Status"><span className={`badge ${a.status==="hired"?"badge-success":a.status==="interview"?"badge-warning":""}`}>{String(a.status).replaceAll("_"," ")}</span></td><td data-label="Applied">{dateShort(a.applied_at)}</td><td><div className="row wrap"><Link className="btn btn-sm" href={jobPublicHref(a.jobs || { id: a.job_id })}>Job</Link>{!["hired","rejected","withdrawn"].includes(a.status)?<form action={withdrawApplicationAction}><input type="hidden" name="application_id" value={a.id}/><button className="btn btn-sm btn-danger" type="submit">Withdraw</button></form>:null}</div></td></tr>})}</tbody></table>:<div className="empty">You have not applied to a job yet. <Link href="/workspace/va/jobs" className="text-link">Browse matching jobs</Link>.</div>}</div></>}
